--------------------------------------------------------
--  File created - Tuesday-June-10-2025   
--------------------------------------------------------
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\TABLES\DIMTHRESHOLDMASTER.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\TABLES\DIMTHRESHOLDMASTER_MOD.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\TABLES\GTT_BRANCH.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\TABLES\GTT_DIMREGION.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\TABLES\TT_CODE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\TABLES\TT_DIMTHRESHOLDMASTER_3.sql
--@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\DATA_TABLE\DIMTHRESHOLDMASTER.tsv
--@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\DATA_TABLE\DIMTHRESHOLDMASTER_MOD.tsv
--@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\DATA_TABLE\GTT_BRANCH.tsv
--@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\DATA_TABLE\GTT_DIMREGION.tsv
--@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\DATA_TABLE\TT_CODE.tsv
--@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\DATA_TABLE\TT_DIMTHRESHOLDMASTER_3.tsv
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\PROCEDURES\DIMTHRESHOLDMASTER_LOCATION_LOCATIONCOCDE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\PROCEDURES\TRESHOLDQUICKSERACHSELECT.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\PROCEDURES\TRESHOLDSELECT.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\PROCEDURES\TRESHOLDSELECT_DATA.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\PROCEDURES\TRESHOLD_META.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\PROCEDURES\TRESHOLD_SHOW_SELECT.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\SYNONYMS\UTILS.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORACLE SCRIPTS 2025\ALERT_RBL_MISDB_PROD\CONSTRAINTS\GTT_DIMREGION.sql
