--------------------------------------------------------
--  DDL for Procedure DIMSECURITIZATION_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."DIMSECURITIZATION_INSERT" /*==============================================
 AUTHER : Triloki Khanna
 CREATE DATE : 27-12-2019
 MODIFY DATE : 27-12-2019
 DESCRIPTION : INSERT DATA FOR Securitization ID
 --EXEC PRO.DimSecuritization_Insert


 ================================================*/
--BEGIN
 --IF OBJECT_ID('TEMPDB..#SecuritizationCode') IS NOT NULL
 --   DROP TABLE #SecuritizationCode
 --DECLARE  @vEffectivefrom  Int SET @vEffectiveFrom=(SELECT TimeKey FROM [dbo].Automate_Advances WHERE EXT_FLG='Y')
 --DECLARE @TimeKey  Int SET @TimeKey=(SELECT TimeKey FROM [dbo].Automate_Advances WHERE EXT_FLG='Y')
 --DECLARE @DATE AS DATE =(SELECT Date FROM [dbo].Automate_Advances WHERE EXT_FLG='Y')
 --DECLARE @SecuritizationAlt_Key INT=0 
 --SELECT @SecuritizationAlt_Key=MAX(SecuritizationAlt_Key) FROM  [dbo].[DimSecuritization] 
 -----@SecuritizationAlt_Key + ROW_NUMBER()OVER(ORDER BY (SELECT 1))
 --   SELECT distinct SecuritizationCode SecuritizationCode INTO #SecuritizationCode  FROM dbo.AdvAcBasicDetail  A where ( A.SecuritizationCode is not null and  A.SecuritizationCode<>'0' and A.SecuritizationCode<>'' )
 --                                                             AND A.EffectiveFromTimeKey<=@TimeKey AND A.EffectiveToTimeKey>=@TimeKeY
 --   EXCEPT
 --   SELECT SecuritizationCode FROM dbo.DimSecuritization where EffectiveToTimeKey=49999
 --   INSERT INTO DimSecuritization
 --   (
 -- SecuritizationAlt_Key
 --,SecuritizationCode
 --,SecuritizationName
 --,SecuritizationShortName
 --,SecuritizationShortNameEnum
 --,SecuritizationGroup
 --,SecuritizationSubGroup
 --,SecuritizationSegment
 --,SrcSysSecuritizationCode
 --,SrcSysSecuritizationName
 --,DestSysSecuritizationCode
 --,AuthorisationStatus
 --,EffectiveFromTimeKey
 --,EffectiveToTimeKey
 --,CreatedBy
 --,DateCreated
 --,ModifiedBy
 --,DateModifie
 --,ApprovedBy
 --,DateApproved
 --   )
 --SELECT 
 --@SecuritizationAlt_Key + ROW_NUMBER()OVER(ORDER BY (SELECT 1))
 --,SecuritizationCode=A.SecuritizationCode
 --,SecuritizationName=A.SecuritizationCode
 --,SecuritizationShortName=null
 --,SecuritizationShortNameEnum=null
 --,SecuritizationGroup='Owned'
 --,SecuritizationSubGroup=null
 --,SecuritizationSegment=null
 --,SrcSysSecuritizationCode=null
 --,SrcSysSecuritizationName=null
 --,DestSysSecuritizationCode=null
 --,AuthorisationStatus=NULL
 --,EffectiveFromTimeKey=(SELECT TimeKey FROM [dbo].Automate_Advances WHERE EXT_FLG='Y')
 --,EffectiveToTimeKey=49999
 --,CreatedBy='SSIS'
 --,DateCreated=GETDATE()
 --,ModifyBy=NULL
 --,DateModified=NULL
 --,ApprovedBy=NULL
 --,DateApproved=NULL
 --FROM #SecuritizationCode A 
 --update dbo.DIMSECURITIZATION set SourceAlt_Key=1 where SourceAlt_Key is NULL
 --update dbo.DIMSECURITIZATION set EffectiveFromDate=EffectiveFromTimeKey where EffectiveFromDate is NULL
 -- DROP TABLE #SecuritizationCode
 --END

AS

BEGIN

   NULL;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."DIMSECURITIZATION_INSERT" TO "ADF_CDR_RBL_STGDB";
