--------------------------------------------------------
--  DDL for Procedure MARKINGFLGPROCESSING
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."MARKINGFLGPROCESSING" /*==========================================
 AUTHER : SANJEEV KUMAR SHARMA
 CREATE DATE : 04-04-2018
 MODIFY DATE : 04-04-2018
 DESCRIPTION : MARKING OF FLG PROCESSING
 --EXEC MarkingFlgProcessing  @TIMEKEY
==============================================*/
(
  v_TIMEKEY IN NUMBER
)
AS
   v_cursor SYS_REFCURSOR;

BEGIN
    DECLARE v_SQLERRM VARCHAR(1000);
   BEGIN

      BEGIN
         UPDATE MAIN_PRO.CUSTOMERCAL
            SET FlgProcessing = 'Y'
          WHERE  ( EffectiveFromTimeKey <= v_TIMEKEY
           AND EffectiveTOTimeKey >= v_TIMEKEY );

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
   v_SQLERRM:=SQLERRM;
      OPEN  v_cursor FOR
         SELECT 'ERROR PROCEDURE :' || utils.error_procedure || ' ERROR MESSAGE:' || V_SQLERRM 
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING" TO "ADF_CDR_RBL_STGDB";
