--------------------------------------------------------
--  DDL for Procedure RECALCULATE_BALANCE_AGAIN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" /*=========================================
 AUTHER : TRILOKI KHANNA
 CREATE DATE : 29-06-2020
 MODIFY DATE : 29-06-2020
 DESCRIPTION :Recalculate_Balance_Again
 EXEC [PRO].[Recalculate_Balance_Again] 4925
=============================================*/
(
  v_TIMEKEY IN NUMBER
)
AS

BEGIN

   /*----------------Calculate Balance Again in Account cal table ---------------------------- */
   MERGE INTO MAIN_PRO.ACCOUNTCAL A
   USING (SELECT A.ROWID row_id, NVL(PrincOutStd, 0) AS Balance
   FROM MAIN_PRO.ACCOUNTCAL A ) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET Balance = src.Balance;
   MERGE INTO MAIN_PRO.ACCOUNTCAL A
   USING (SELECT A.ROWID row_id, NVL(PrincOutStd, 0) + NVL(IntOverdue, 0) AS Balance
   FROM MAIN_PRO.ACCOUNTCAL A 
    WHERE a.FinalAssetClassAlt_Key = 1) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET Balance = src.Balance;
   --UPDATE A SET Balance=isnull(Balance,0)- isnull(AdvanceRecovery,0)
   MERGE INTO MAIN_PRO.ACCOUNTCAL A
   USING (SELECT A.ROWID row_id, (CASE 
   WHEN (NVL(A.Balance, 0) - (NVL(A.AdvanceRecovery, 0))) < 0 THEN (NVL(A.Balance, 0) - (NVL(A.AdvanceRecovery, 0)))
   ELSE (NVL(A.Balance, 0) - (NVL(A.AdvanceRecovery, 0)))
      END) AS Balance
   FROM MAIN_PRO.ACCOUNTCAL A 
    WHERE NVL(AdvanceRecovery, 0) > 0) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET Balance = src.Balance;
   --UPDATE  A SET BALANCE=0  FROM PRO.ACCOUNTCAL A  WHERE ISNULL(BALANCE,0)<0
   ---UPDATE NotionalInttAmt ---- 
   MERGE INTO MAIN_PRO.ACCOUNTCAL A
   USING (SELECT A.ROWID row_id, CASE 
   WHEN NVL(InttRate, 0) > 0 THEN (NVL(Balance, 0) * NVL(InttRate, 0)) / 100
   ELSE 0
      END AS NotionalInttAmt
   FROM MAIN_PRO.ACCOUNTCAL A ) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET NotionalInttAmt = src.NotionalInttAmt;
   IF utils.object_id('TEMPDB..tt_CUSTTOTOSCUST') IS NOT NULL THEN
    EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_CUSTTOTOSCUST ';
   END IF;
   DELETE FROM tt_CUSTTOTOSCUST;
   UTILS.IDENTITY_RESET('tt_CUSTTOTOSCUST');

   INSERT INTO tt_CUSTTOTOSCUST ( 
   	SELECT CUSTOMERENTITYID ,
           SUM(NVL(BALANCE, 0))  BALANCE  
   	  FROM MAIN_PRO.ACCOUNTCAL 
   	  GROUP BY CUSTOMERENTITYID );
   UPDATE MAIN_PRO.CUSTOMERCAL
      SET TOTOSCUST = 0;
   MERGE INTO MAIN_PRO.CUSTOMERCAL A
   USING (SELECT A.ROWID row_id, BALANCE
   FROM MAIN_PRO.CUSTOMERCAL A
          JOIN tt_CUSTTOTOSCUST B   ON A.CustomerEntityID = B.CUSTOMERENTITYID ) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET A.TOTOSCUST = BALANCE;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN" TO "ADF_CDR_RBL_STGDB";
