--------------------------------------------------------
--  DDL for Procedure UPDATEASSETCLASSFORPROVISION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" /*==================================      
AUTHER : SANJEEV KUMAR SHARMA      
CREATE DATE : 25-03-2017      
MODIFY DATE : 25-03-2017      
DESCRIPTION : UPDATE  USER ASSET CLASS AND TXN ASSET CLASS AND SYSTEMASSETCLASS      
--EXEC UpdateAssetClassForProvision @Timekey=4463      
==========================================*/
(
  v_Timekey IN NUMBER
)
AS
   v_cursor SYS_REFCURSOR;

BEGIN
    
    DECLARE V_SQLERRM VARCHAR(150);
   BEGIN

      BEGIN
         /*----------******UPDATING CUSTOMERASSET_CLASS TO ALL ACCOUNTS OF the CUSTOMER     
                           FOR PROVISION  COMPUTATION AT ACCOUNT LEVEL****----------------------*/
         MERGE INTO MAIN_PRO.ACCOUNTCAL B
         USING (SELECT B.ROWID row_id, a.SrcAssetClassAlt_Key 
                    FROM MAIN_PRO.CUSTOMERCAL A
                    JOIN MAIN_PRO.ACCOUNTCAL B   
                        ON A.CustomerEntityID = B.CustomerEntityID ) src
             ON ( B.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET B.InitialAssetClassAlt_Key = SRC.SrcAssetClassAlt_Key,
                                      B.FinalAssetClassAlt_Key = SRC.SrcAssetClassAlt_Key;

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
   V_SQLERRM:=SQLERRM;
      OPEN  v_cursor FOR
         SELECT 'ERROR PROCEDURE :' || utils.error_procedure || 'ERROR MESSAGE :' || V_SQLERRM
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION" TO "ADF_CDR_RBL_STGDB";
