--------------------------------------------------------
--  DDL for Procedure UPDATEUNSERVISEDINTT_ACCOUNTWISE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" /*======================          
AUTHER : SANJEEV KUMAR SHARAMA          
CREATE DATE : 06-03-2017          
MODIFY DATE : 06-03-2017          
DESCRIPTION : UPDATE unServisedIntt AccountWise          
=======================================*/
(
  v_TimeKey IN NUMBER
)
AS
   ----- Update Net Balance Calculate Amount In AdvacCal Table in NetBalance column            
   
   v_cursor SYS_REFCURSOR;

BEGIN
DECLARE V_SQLERRM VARCHAR(150);
   BEGIN
      DECLARE
         v_ProcessingDate VARCHAR2(200);

      BEGIN
         SELECT Date_ 

           INTO v_ProcessingDate
           FROM RBL_MISDB_PROD.SysDayMatrix 
          WHERE  Timekey = v_TimeKey;

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
   V_SQLERRM :=SQLERRM ;
      OPEN  v_cursor FOR
         SELECT 'Procedure Name :' || utils.error_procedure || 'Error Message :' || V_SQLERRM 
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE" TO "ADF_CDR_RBL_STGDB";
