--------------------------------------------------------
--  Constraints for Table ADVNFACBASICDETAIL
--------------------------------------------------------

  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACBASICDETAIL" MODIFY ("AC_KEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACBASICDETAIL" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACBASICDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACBASICDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACBASICDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACBASICDETAIL" ADD CONSTRAINT "ADVNFACBASICDETAIL_ACCOUNTENTITYID" PRIMARY KEY ("ACCOUNTENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
