--------------------------------------------------------
--  Constraints for Table ADVNFACFINANCIALDETAIL
--------------------------------------------------------

  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACFINANCIALDETAIL" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACFINANCIALDETAIL" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACFINANCIALDETAIL" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACFINANCIALDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACFINANCIALDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACFINANCIALDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."ADVNFACFINANCIALDETAIL" ADD CONSTRAINT "ADVNFACFINANCIALDETAIL_PK" PRIMARY KEY ("ACCOUNTENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
