--------------------------------------------------------
--  Constraints for Table CUSTOMERBASICDETAIL
--------------------------------------------------------

  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL" MODIFY ("CUSTOMERNAME" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL" MODIFY ("CUSTOMER_KEY" NOT NULL ENABLE);
