--------------------------------------------------------
--  Constraints for Table DERIVATIVEDETAIL
--------------------------------------------------------

  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."DERIVATIVEDETAIL" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."DERIVATIVEDETAIL" MODIFY ("DERIVATIVEENTITYID" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."DERIVATIVEDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "PREMOC_RBL_MISDB_PROD"."DERIVATIVEDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
