--------------------------------------------------------
--  DDL for Table SS2K5_FOREIGN_KEY_COLUMNS
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "ACL_RBL_MISDB_PROD"."SS2K5_FOREIGN_KEY_COLUMNS" 
   (	"DB_ID" NUMBER(10,0), 
	"CONSTRAINT_COLUMN_ID" NUMBER(10,0), 
	"CONSTRAINT_OBJECT_ID" NUMBER(10,0), 
	"PARENT_OBJECT_ID" NUMBER(10,0), 
	"PARENT_COLUMN_ID" NUMBER(10,0), 
	"REFERENCED_COLUMN_ID" NUMBER(10,0), 
	"REFERENCED_OBJECT_ID" NUMBER(10,0)
   ) ON COMMIT PRESERVE ROWS ;
