--------------------------------------------------------
--  DDL for Table STAGE_TERADATA_ALL_RI_PARENTS
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "ACL_RBL_MISDB_PROD"."STAGE_TERADATA_ALL_RI_PARENTS" 
   (	"INDEXNAME" VARCHAR2(128 CHAR), 
	"PARENTDB" VARCHAR2(128 CHAR), 
	"PARENTTABLE" VARCHAR2(128 CHAR), 
	"PARENTKEYCOLUMN" VARCHAR2(128 CHAR), 
	"CHILDDB" VARCHAR2(128 CHAR), 
	"CHILDTABLE" VARCHAR2(128 CHAR), 
	"CHILDKEYCOLUMN" VARCHAR2(128 CHAR), 
	"CREATORNAME" VARCHAR2(128 CHAR)
   ) ON COMMIT PRESERVE ROWS ;
