--------------------------------------------------------
--  DDL for Table STAGE_TERADATA_SHOWTBLCHECKS
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "ACL_RBL_MISDB_PROD"."STAGE_TERADATA_SHOWTBLCHECKS" 
   (	"MDID" NUMBER, 
	"DATABASENAME" VARCHAR2(128 CHAR), 
	"TABLENAME" VARCHAR2(128 CHAR), 
	"CHECKNAME" VARCHAR2(128 CHAR), 
	"CHECKTYPE" CHAR(1 BYTE), 
	"TABLECHECK" CLOB, 
	"COLUMNNAME" VARCHAR2(128 CHAR), 
	"CREATORNAME" VARCHAR2(128 CHAR)
   ) ON COMMIT PRESERVE ROWS 
 LOB ("TABLECHECK") STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE ) ;
