--------------------------------------------------------
--  DDL for Procedure ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" 
-- =============================================
 -- Author:		<Author,,Name>
 -- Create date: <Create Date,,>
 -- Description:	<Description,,>
 -- =============================================

AS
   v_MAX NUMBER(10,0);
-- Add the parameters for the stored procedure here

BEGIN

   -- SET NOCOUNT ON added to prevent extra result sets from
   -- interfering with SELECT statements.
   -- Insert statements for procedure here
   EXECUTE IMMEDIATE ' TRUNCATE TABLE TempAdvCustCommunicationDetail ';
   INSERT INTO TempAdvCustCommunicationDetail
     ( CustomerEntityId, RelationEntityId
   --,RelationAddEntityId
   , AddressCategoryAlt_Key, AddressTypeAlt_Key, Add1, Add2, Add3, CountryAlt_Key, CityAlt_Key, CityName, PinCode, RefCustomerId, IsMainAddress, EffectiveFromTimeKey, EffectiveToTimeKey
   --,STD_Code_Res
   , PhoneNo_Res
   --,STD_Code_Off
   , PhoneNo_Off, CreatedBy, DateCreated )
     ( SELECT A.CustomerEntityId ,
              A.RelationEntityId ,
              NULL ,
              NULL ,
              B.PermanentAddress_AddressLine1 ,
              B.PermanentAddress_AddressLine2 ,
              B.PermanentAddress_AddressLine3 ,
              --DC.CountryAlt_Key,
              UTILS.CONVERT_TO_NUMBER('',5,0) CountryAlt_Key  ,
              --DCC.CityAlt_Key,
              UTILS.CONVERT_TO_NUMBER('',5,0) CityAlt_Key  ,
              --RCT.REF_DESC AS CityName,
              B.PermanentAddress_City_Location CityName  ,
              REPLACE(B.PermanentAddress_Pincode, ' ', ' ') PinCode  ,
              A.RefCustomerId RefCustomerId  ,
              'Y' IsMainAddress  ,
              A.EffectiveFromTimeKey ,
              A.EffectiveToTimeKey ,
              B.PrimaryMobile PhoneNo_Res  ,
              NULL PhoneNo_Off  ,
              A.CreatedBy ,
              A.DateCreated 
       FROM TempAdvCustRelationship A
              JOIN RBL_STGDB.CUSTOMERADDRESS_SOURCESYSTEM_STG B   ON A.RefCustomerId = B.CustomerID );
   MERGE INTO TACCMD 
   USING (SELECT TACCMD.ROWID row_id, ACCMD.RelationAddEntityId
   FROM TACCMD ,CURDAT_UATRestore_RBL_MISDB.AdvCustCommunicationDetail ACCMD
          JOIN TempAdvCustCommunicationDetail TACCMD   ON ACCMD.CustomerEntityId = TACCMD.CustomerEntityId
          AND ACCMD.IsMainAddress = TACCMD.IsMainAddress
          AND ACCMD.EffectiveToTimeKey = 49999 ) src
   ON ( TACCMD.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET TACCMD.RelationAddEntityId = src.RelationAddEntityId;
   SELECT MAX(RelationAddEntityId)  

     INTO v_MAX
     FROM ( SELECT NVL(MAX(RelationAddEntityId) , 0) RelationAddEntityId  
            FROM curdat_UATRestore_RBL_MISDB.AdvCustCommunicationDetail ACCMD
            UNION 
            SELECT NVL(MAX(RelationAddEntityId) , 0) RelationAddEntityId  
            FROM UATRestore_RBL_MISDB.AdvCustCommunicationDetail_Mod ACCMD ) A;
   UPDATE TempADVCUSTCOMMUNICATIONDETAIL
      SET RELATIONADDENTITYID = v_MAX + 1
    WHERE  RELATIONADDENTITYID IS NULL;
   MERGE INTO B 
   USING (SELECT B.ROWID row_id, A.CityAlt_Key
   FROM B ,UATRestore_RBL_MISDB.DIMCITY A
          JOIN TempAdvCustCommunicationDetail B   ON A.CityName = B.CityName 
    WHERE A.EffectiveToTimeKey = 49999) src
   ON ( B.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET A.CityAlt_Key = src.CityAlt_Key;
   UPDATE TempADVCUSTCOMMUNICATIONDETAIL
      SET COUNTRYALT_KEY = 100
    WHERE  NVL(COUNTRYALT_KEY, 0) = 0;
   MERGE INTO a 
   USING (SELECT a.ROWID row_id, b.DistrictAlt_Key
   FROM a ,TempAdvCustCommunicationDetail a
          JOIN UATRestore_RBL_MISDB.dimpincode b   ON a.pincode = b.pincode 
    WHERE b.EffectiveToTimeKey = 49999) src
   ON ( a.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET b.DistrictAlt_Key = src.DistrictAlt_Key;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "MAIN_PRO";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "MAIN_PRO";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "RBL_TEMPDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."ADVCUSTCOMMUNICATIONDETAIL_TEMP_NEWDB" TO "ADF_CDR_RBL_STGDB";
