--------------------------------------------------------
--  DDL for Table WRITEOFFDATA
--------------------------------------------------------

  CREATE TABLE "DWH_RBL_MISDB_PROD"."WRITEOFFDATA" 
   (	"REPORTDATA" DATE, 
	"HOSTSYSTEM" VARCHAR2(20 BYTE), 
	"CUSTOMERACID" VARCHAR2(30 BYTE), 
	"CUSTOMERID" VARCHAR2(50 BYTE), 
	"UCIC" VARCHAR2(50 BYTE), 
	"WRITEOFFFLAG" VARCHAR2(1 BYTE), 
	"WRITEOFFDATE" DATE, 
	"WRITEOFFAMOUNT" NUMBER(18,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
