--------------------------------------------------------
--  Ref Constraints for Table MD_GROUP_MEMBERS
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."MD_GROUP_MEMBERS" ADD CONSTRAINT "MD_GROUPMEMBERS_MD_USERS_FK1" FOREIGN KEY ("USER_ID_FK")
	  REFERENCES "RBL_MISDB_PROD"."MD_USERS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RBL_MISDB_PROD"."MD_GROUP_MEMBERS" ADD CONSTRAINT "MD_GROUPMEMBERS_MD_GROUPS_FK2" FOREIGN KEY ("GROUP_MEMBER_ID_FK")
	  REFERENCES "RBL_MISDB_PROD"."MD_GROUPS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RBL_MISDB_PROD"."MD_GROUP_MEMBERS" ADD CONSTRAINT "MD_GROUPMEMBERS_MD_GROUPS_FK1" FOREIGN KEY ("GROUP_ID_FK")
	  REFERENCES "RBL_MISDB_PROD"."MD_GROUPS" ("ID") ON DELETE CASCADE ENABLE;
