--------------------------------------------------------
--  DDL for Materialized View MD_REGEX_SCHEMA_MVIEW
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "ACL_RBL_MISDB_PROD"."MD_REGEX_SCHEMA_MVIEW" ("PROJECT_ID", "CONNECTION_ID", "CONNECTION_NAME", "CATALOG_ID", "CATALOG_NAME", "SCHEMA_ID", "SCHEMA_NAME", "ITEM", "VALUE")
  SEGMENT CREATION DEFERRED
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_MVIEW
        group by PROJECT_NAME, PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM;

   COMMENT ON MATERIALIZED VIEW "ACL_RBL_MISDB_PROD"."MD_REGEX_SCHEMA_MVIEW"  IS 'snapshot table for snapshot ACL_RBL_MISDB_PROD.MD_REGEX_SCHEMA_MVIEW';
