--------------------------------------------------------
--  DDL for Procedure ACCELERATEDPROVISION_DOWNLOADDATA_18112023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

(
  iv_Timekey IN NUMBER,
  v_UserLoginId IN VARCHAR2,
  v_ExcelUploadId IN NUMBER,
  v_UploadType IN VARCHAR2
)
AS
   v_Timekey NUMBER(10,0) := iv_Timekey;
   v_cursor SYS_REFCURSOR;
--,@Page SMALLINT =1     
--   ,@perPage INT = 30000   
----DECLARE @Timekey INT=49999
----	,@UserLoginId VARCHAR(100)='FNASUPERADMIN'
----	,@ExcelUploadId INT=4
----	,@UploadType VARCHAR(50)='Interest reversal'

BEGIN

   --Select @Timekey=Max(Timekey) from dbo.SysDayMatrix  
   --  where  Date=cast(getdate() as Date)
   --  		  PRINT @Timekey  
   SELECT Timekey 

     INTO v_Timekey
     FROM SysDataMatrix 
    WHERE  MOC_Initialised = 'Y'
             AND NVL(MOC_Frozen, 'N') = 'N';
   --DECLARE @PageFrom INT, @PageTo INT   
   --SET @PageFrom = (@perPage*@Page)-(@perPage) +1  
   --SET @PageTo = @perPage*@Page  
   IF ( v_UploadType = 'Acce Provision Upload' ) THEN

   BEGIN
      --SELECT * FROM(
      OPEN  v_cursor FOR
         SELECT 'Acce Provision Details' TableName  ,
                UploadID ,
                CustomerId ,
                AccountId ,
                UCICID ,
                B.ParameterName ,
                UTILS.CONVERT_TO_VARCHAR2(EffectiveDate,10,p_style=>103) EffectiveDate  ,
                Secured_Unsecured ,
                AdditionalProvision ,
                AdditionalProvACCT ,
                A.SegmentNameAlt_key SegmentName  ,
                D.AssetClassName 
           FROM AcceleratedProvision_Mod A
                  LEFT JOIN ( SELECT ParameterAlt_Key ,
                                     ParameterName ,
                                     'AcceleratedProvisionDuration' Tablename  
                              FROM DimParameter 
                               WHERE  DimParameterName = 'DimAccProvDuration' ) B   ON A.AcceProDuration = B.ParameterAlt_Key
                  LEFT JOIN ( SELECT AssetClassAlt_Key ,
                                     AssetClassName ,
                                     'AssetClass' Tablename  
                              FROM DimAssetClass 
                               WHERE  EffectiveFromTimeKey <= v_Timekey
                                        AND EffectiveToTimeKey >= v_Timekey
                                        AND AssetClassAlt_Key NOT IN ( 1 )
                             ) D   ON A.AssetClassNameAlt_key = D.AssetClassAlt_Key
          WHERE  UploadId = v_ExcelUploadId
                   AND EffectiveFromTimeKey <= v_Timekey
                   AND EffectiveToTimeKey >= v_Timekey ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCELERATEDPROVISION_DOWNLOADDATA_18112023" TO "ADF_CDR_RBL_STGDB";
