--------------------------------------------------------
--  DDL for Procedure ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" 
-------------------------------
 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

(
  iv_Timekey IN NUMBER,
  v_UserLoginId IN VARCHAR2,
  v_ExcelUploadId IN NUMBER,
  v_UploadType IN VARCHAR2
)
AS
   v_Timekey NUMBER(10,0) := iv_Timekey;
   --SELECT * FROM(
   v_cursor SYS_REFCURSOR;
--,@Page SMALLINT =1     
--   ,@perPage INT = 30000   
----DECLARE @Timekey INT=49999
----	,@UserLoginId VARCHAR(100)='FNASUPERADMIN'
----	,@ExcelUploadId INT=4
----	,@UploadType VARCHAR(50)='Interest reversal'

BEGIN

   SELECT TimeKey 

     INTO v_Timekey
     FROM SysDataMatrix 
    WHERE  CurrentStatus = 'C';
   SELECT LastMonthDateKey 

     INTO v_Timekey
     FROM SysDayMatrix 
    WHERE  Timekey = v_Timekey;
   DBMS_OUTPUT.PUT_LINE(v_Timekey);
   --DECLARE @PageFrom INT, @PageTo INT   
   --SET @PageFrom = (@perPage*@Page)-(@perPage) +1  
   --SET @PageTo = @perPage*@Page  
   IF ( v_UploadType = 'Account MOC Upload' ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT AccountID ,
                'Details' TableName  ,
                UploadID ,
                POS ,
                InterestReceivable ,
                AdditionalProvisionAbsolute ,
                RestructureFlag ,
                A.RestructureDate ,
                FITLFlag ,
                DFVAmount ,
                RePossessionFlag ,
                A.RePossessionDate ,
                InherentWeaknessFlag ,
                InherentWeaknessDate ,
                SARFAESIFlag ,
                A.SARFAESIDate ,
                UnusualBounceFlag ,
                A.UnusualBounceDate ,
                UnclearedEffectsFlag ,
                UnclearedEffectsDate ,
                FraudAccountFlag ,
                A.FraudDate ,
                MOCSource ,
                A.MOCReason 
           FROM AccountLevelMOC_Mod A
                  JOIN PRO_RBL_MISDB_PROD.AccountCal_Hist B   ON A.AccountID = B.CustomerAcID
          WHERE  UploadId = v_ExcelUploadId
                   AND A.EffectiveFromTimeKey <= v_Timekey
                   AND A.EffectiveToTimeKey >= v_Timekey ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCNPAMOC_DOWNLOADDATA_BACKUP_12122021" TO "ADF_CDR_RBL_STGDB";
