--------------------------------------------------------
--  DDL for Procedure ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" 
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   OPEN  v_cursor FOR
      SELECT ENTITYKEY	,
                MENUID	,
                SCREENNAME	,
                CTRLNAME	,
                RESOURCEKEY	,
                FLDDATATYPE	,
                COL_LG	,
                COL_MD	,
                COL_SM	,
                MINLENGTH	,
                MAXLENGTH	,
                ERRORCHECK	,
                DATASEQ	,
                FLDGRIDVIEW	,
                CRITICALERRORTYPE	,
                SCREENFIELDNO	,
                ISEDITABLE	,
                ISVISIBLE	,
                ISUPPER	,
                ISMANDATORY	,
                ALLOWCHAR	,
                DISALLOWCHAR	,
                DEFAULTVALUE	,
                ALLOWTOOLTIP	,
                REFERENCECOLUMNNAME	,
                REFERENCETABLENAME	,
                MOC_FLAG	,
                USERID	,
                CREATEDBY	,
                DATECREATED	,
                MODIFIEDBY	,
                DATEMODIFIED	,
                SCREENFIELDGROUP	,
                HIGHERLEVELEDIT	,
                APPLICABLEFORWORKFLOW	,
                ISEXTRACTEDEDITABLE	,
                ISMOCVISIBLE	,
             'ACBUSegment' TableName  
        FROM MetaScreenFieldDetail 
       WHERE  ScreenName = 'AccountBusinessSegmentMaster' ;
      DBMS_SQL.RETURN_RESULT(v_cursor);

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACCOUNTBUSINESSSEGMENTMASTER_METASCREEN" TO "ADF_CDR_RBL_STGDB";
