--------------------------------------------------------
--  DDL for Procedure ACLDATACHECK_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."ACLDATACHECK_04122023" 
AS
   ------/* ACL PROCESS STEP ERROR */
   ------DECLARE 26267 Int =(select TimeKey from Automate_Advances where EXT_FLG='Y')
   ------DECLARE @Date date=(select Date from Automate_Advances where EXT_FLG='Y')
   ------DECLARE @CNT1 INT =0
   ------select * from pro.ACCOUNTCAL
   /* ACL TOTAL NO OF ACCOUNT */
   v_cursor SYS_REFCURSOR;

BEGIN

   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.ACCOUNTCAL 
       WHERE  EffectiveFromTimeKey = 26282 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.AccountCal_Hist 
       WHERE  EffectiveFromTimeKey <= 26282
                AND EffectiveToTimeKey >= 26282 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   /* TOTAL NO OF NPA ACCOUNT  */
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.ACCOUNTCAL 
       WHERE  FinalAssetClassAlt_Key > 1
                AND EffectiveFromTimeKey = 26282 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.AccountCal_Hist 
       WHERE  EffectiveFromTimeKey <= 26282
                AND EffectiveToTimeKey >= 26282
                AND FinalAssetClassAlt_Key > 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM ACL_NPA_DATA 
       WHERE  Process_Date = '15-12-2021'
                AND FinalAssetClassAlt_Key > 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   /* TOTAL NO OF ACCOUNT DEGRADE */
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.ACCOUNTCAL 
       WHERE  FinalAssetClassAlt_Key > 1
                AND InitialAssetClassAlt_Key = 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.AccountCal_Hist 
       WHERE  EffectiveFromTimeKey <= 26282
                AND EffectiveToTimeKey >= 26282
                AND FinalAssetClassAlt_Key > 1
                AND InitialAssetClassAlt_Key = 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM ReverseFeedData 
       WHERE  DateofData = '2021-12-15'
                AND AssetClass > 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   /* TOTAL NO OF ACCOUNT UPGRADE */
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.ACCOUNTCAL 
       WHERE  FinalAssetClassAlt_Key = 1
                AND InitialAssetClassAlt_Key > 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.AccountCal_Hist 
       WHERE  EffectiveFromTimeKey <= 26282
                AND EffectiveToTimeKey >= 26282
                AND FinalAssetClassAlt_Key = 1
                AND InitialAssetClassAlt_Key > 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM ReverseFeedData 
       WHERE  DateofData = '2021-12-15'
                AND AssetClass = 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   /* TOTAL NO OF CUSTOMERS */
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.CUSTOMERCAL  ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.CustomerCal_Hist 
       WHERE  EffectiveFromTimeKey <= 26282
                AND EffectiveToTimeKey >= 26282 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   /* TOTAL NO OF CUSTOMERS NPA	*/
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.CUSTOMERCAL 
       WHERE  SysAssetClassAlt_Key > 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.CustomerCal_Hist 
       WHERE  EffectiveFromTimeKey <= 26282
                AND EffectiveToTimeKey >= 26282
                AND SysAssetClassAlt_Key > 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   /* TOTAL NO OF CUSTOMERS DEGRADE	*/
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.CUSTOMERCAL 
       WHERE  SysAssetClassAlt_Key > 1
                AND SrcAssetClassAlt_Key = 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.CustomerCal_Hist 
       WHERE  EffectiveFromTimeKey <= 26282
                AND EffectiveToTimeKey >= 26282
                AND SysAssetClassAlt_Key > 1
                AND SrcAssetClassAlt_Key = 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   /* TOTAL NO OF CUSTOMERS UPGRADE*/
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.CUSTOMERCAL 
       WHERE  SysAssetClassAlt_Key = 1
                AND SrcAssetClassAlt_Key > 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT COUNT(1)  
        FROM PRO_RBL_MISDB_PROD.CustomerCal_Hist 
       WHERE  EffectiveFromTimeKey <= 26282
                AND EffectiveToTimeKey >= 26282
                AND SysAssetClassAlt_Key = 1
                AND SrcAssetClassAlt_Key > 1 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."ACLDATACHECK_04122023" TO "ADF_CDR_RBL_STGDB";
