--------------------------------------------------------
--  DDL for Procedure BUYOUTDOWNLOADDATA_ENQUIRY_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" 
(
  v_ExcelUploadId IN NUMBER
)
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   DECLARE
      v_Timekey NUMBER(10,0);
   ----DECLARE @Timekey INT=49999
   ----	,@UserLoginId VARCHAR(100)='FNASUPERADMIN'
   ----	,@ExcelUploadId INT=4
   ----	,@UploadType VARCHAR(50)='Interest reversal'

   BEGIN
      SELECT UTILS.CONVERT_TO_NUMBER(B.timekey,10,0) 

        INTO v_Timekey
        FROM SysDataMatrix A
               JOIN SysDayMatrix B   ON A.TimeKey = B.TimeKey
       WHERE  A.CurrentStatus = 'C';
      DBMS_OUTPUT.PUT_LINE(v_Timekey);

   END;

   BEGIN
      OPEN  v_cursor FOR
         SELECT 'Details' TableName  ,
                UploadID ,
                --,SummaryID
                SlNo ,
                AUNo ,
                PoolName ,
                Category ,
                BuyoutPartyLoanNo ,
                CustomerName ,
                PAN ,
                AadharNo ,
                PrincipalOutstanding ,
                InterestReceivable ,
                Charges ,
                AccuredInterest ,
                DPD ,
                AssetClass 

           ------,ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS ROW_NUM
           FROM BuyoutDetails_Mod 
          WHERE  UploadId = v_ExcelUploadId
                   AND EffectiveFromTimeKey <= v_Timekey
                   AND EffectiveToTimeKey >= v_Timekey ;
         DBMS_SQL.RETURN_RESULT(v_cursor);
      OPEN  v_cursor FOR
         SELECT 'Summary' TableName  ,
                ROW_NUMBER() OVER ( ORDER BY AUNo  ) SrNo  ,
                UploadID ,
                SummaryID ,
                AUNo ,
                PoolName ,
                Category ,
                TotalNoofBuyoutParty ,
                TotalPrincipalOutstandinginRs ,
                TotalInterestReceivableinRs ,
                BuyoutOSBalanceinRs ,
                TotalChargesinRs ,
                TotalAccuredInterestinRs 

           ------,ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS ROW_NUM
           FROM BuyoutSummary_Mod 
          WHERE  UploadId = v_ExcelUploadId
                   AND EffectiveFromTimeKey <= v_Timekey
                   AND EffectiveToTimeKey >= v_Timekey ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."BUYOUTDOWNLOADDATA_ENQUIRY_04122023" TO "ADF_CDR_RBL_STGDB";
