--------------------------------------------------------
--  DDL for Procedure CALYPSOCUSTNPAMOC_DOWNLOADDATA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" 
(
  iv_Timekey IN NUMBER,
  v_UserLoginId IN VARCHAR2,
  v_ExcelUploadId IN NUMBER,
  v_UploadType IN VARCHAR2,
  v_CURSOR OUT SYS_REFCURSOR
)
AS
   v_Timekey NUMBER(10,0) := iv_Timekey;
   v_COUNT INT;
   
--,@Page SMALLINT =1     
--   ,@perPage INT = 30000   
----DECLARE v_TIMEKEY INT=49999
----	,@UserLoginId VARCHAR(100)='FNASUPERADMIN'
----	,v_ExcelUploadId INT=4
----	,v_UploadType VARCHAR(50)='Interest reversal'


BEGIN

   --SET v_TIMEKEY =(Select TimeKey from SysDataMatrix where CurrentStatus='C') 
   --SET v_TIMEKEY =(Select LastMonthDateKey from SysDayMatrix where Timekey=v_TIMEKEY) 
   SELECT Timekey 

     INTO v_Timekey
     FROM SysDataMatrix 
    WHERE  MOC_Initialised = 'Y'
             AND NVL(MOC_Frozen, 'N') = 'N';
   DBMS_OUTPUT.PUT_LINE(v_Timekey);--DECLARE @PageFrom INT, @PageTo INT   
   --SET @PageFrom = (@perPage*@Page)-(@perPage) +1  
   --SET @PageTo = @perPage*@Page  
   --SELECT * FROM(
   IF v_UploadType = 'Calypso Customer MOC Upload'  
    THEN
       SELECT COUNT(1) INTO v_COUNT FROM CalypsoCustomerLevelMOC_Mod A INNER JOIN InvestmentIssuerDetail B ON A.UCIFID = B.UCIFID WHERE UploadId = v_ExcelUploadId AND A.EffectiveFromTimeKey <= v_TIMEKEY AND A.EffectiveToTimeKey >= v_TIMEKEY AND B.EffectiveFromTimeKey <= v_TIMEKEY AND B.EffectiveToTimeKey >= v_TIMEKEY ; 
           IF v_COUNT>0 
           THEN
            OPEN v_CURSOR FOR
                    SELECT DISTINCT A.UCIFID AS UCICID , 'Details' AS TableName , UploadID , B.IssuerName AS CustomerName , A.AssetClass , CAST( NPADate AS VARCHAR (25) )
                   AS NPADate , AdditionalProvision , A.MOCType , A.MOCReason , CAST( A.MOCDate AS VARCHAR(25))
                   AS MOCDate , MOCSource 
           FROM CalypsoCustomerLevelMOC_Mod A INNER JOIN InvestmentIssuerDetail B ON A.UCIFID = B.UCIFID WHERE UploadId = v_ExcelUploadId AND A.EffectiveFromTimeKey <= v_TIMEKEY AND A.EffectiveToTimeKey >= v_TIMEKEY AND B.EffectiveFromTimeKey <= v_TIMEKEY AND B.EffectiveToTimeKey >= v_TIMEKEY  ;
            END IF;
    END IF;
EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CALYPSOCUSTNPAMOC_DOWNLOADDATA" TO "ADF_CDR_RBL_STGDB";
