--------------------------------------------------------
--  DDL for Procedure COLLATERALVALUEAUTOPOPULATE_18082021
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

(
  v_collateralID IN NUMBER,--=4
  v_valueDate IN NVARCHAR2,
  v_Periodinmonths IN VARCHAR2 DEFAULT ' ' 
)
AS
   --='2021-03-01'
   v_valueDate1 NVARCHAR2(10);
   v_valueDate2 VARCHAR2(200);
   v_cursor SYS_REFCURSOR;

BEGIN

   --Print @valueDate
   v_valueDate1 := SUBSTR(v_valueDate, 7, 4) || '-' || SUBSTR(v_valueDate, 4, 2) || '-' || SUBSTR(v_valueDate, 1, 2) ;
   v_valueDate2 := UTILS.CONVERT_TO_VARCHAR2(v_valueDate1,200) ;
   DECLARE
      v_timekey NUMBER(10,0) := ( SELECT TimeKey 
        FROM SysDataMatrix 
       WHERE  CurrentStatus = 'C' );
      v_temp NUMBER(1, 0) := 0;
   --Print '@valueDate1'
   --Print @valueDate1
   --Print '@valueDate2'
   --Print @valueDate2

   BEGIN
      BEGIN
         SELECT 1 INTO v_temp
           FROM DUAL
          WHERE EXISTS ( SELECT 1 
                         FROM CollateralValueDetails 
                          WHERE  EffectiveFromTimeKey <= v_timekey
                                   AND EffectiveToTimeKey >= v_timekey
                                   AND CollateralID = v_collateralID
                                   AND ValuationDate = v_valueDate2 );
      EXCEPTION
         WHEN OTHERS THEN
            NULL;
      END;

      IF v_temp = 1 THEN

      BEGIN
         OPEN  v_cursor FOR
            SELECT 1 ,
                   'ValueAutoPoPulate' TableName  
              FROM DUAL  ;
            DBMS_SQL.RETURN_RESULT(v_cursor);

      END;
      ELSE
      DECLARE
         v_CollateralType NUMBER(10,0);
         v_CollateralSubType NUMBER(10,0);

      BEGIN
         SELECT CollateralTypeAlt_Key 

           INTO v_CollateralType
           FROM CollateralMgmt 
          WHERE  EffectiveFromTimeKey <= v_timekey
                   AND EffectiveToTimeKey >= v_timekey
                   AND CollateralID = v_collateralID;
         SELECT CollateralSubTypeAlt_Key 

           INTO v_CollateralSubType
           FROM CollateralMgmt 
          WHERE  EffectiveFromTimeKey <= v_timekey
                   AND EffectiveToTimeKey >= v_timekey
                   AND CollateralID = v_collateralID;
         --Select (Documents+' '+Validritycriteria)ExpiryBusinessRule,ExpirationPeriod,@Periodinmonths Periodinmonths
         --DATEADD(M,ExpirationPeriod,@valueDate2)ValueExpirationDate 
         --,'AutoPopulateDetails' TableName
         --From DimValueExpiration Where EffectiveFromTimeKey<=@timekey and EffectiveToTimeKey>=@timekey
         --And SecurityTypeAlt_Key = @CollateralType
         --And SecuritySubTypeAlt_Key = @CollateralSubType
         OPEN  v_cursor FOR
            SELECT utils.dateadd('M', UTILS.CONVERT_TO_NUMBER(v_Periodinmonths,10,0), v_valueDate2) ValueExpirationDate  ,
                   'AutoPopulateDetails' TableName  
              FROM DUAL  ;
            DBMS_SQL.RETURN_RESULT(v_cursor);

      END;
      END IF;

   END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."COLLATERALVALUEAUTOPOPULATE_18082021" TO "ADF_CDR_RBL_STGDB";
