--------------------------------------------------------
--  DDL for Procedure CORRECTFINACLEDATA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."CORRECTFINACLEDATA" 
AS

BEGIN

   --delete from ENPA_Host_System_Status_tbl
   --where Report_Date='2022-06-14' and Host_System_Name='INDUS'
   --insert into ENPA_Host_System_Status_tbl
   --select Account_No,Host_System_Name,Main_Classification,Report_Date,Remarks,Closed_Date
   --,Create_On  from finaclehost
   -- update ReverseFeedDataInsertSync
   --set FinalAssetClassAlt_Key=1
   --where CustomerAcID='SLMUM006200006328' and ProcessDate='2022-06-14'
   UPDATE ENPA_Host_System_Status_tbl
      SET Remarks = 'Closed'
    WHERE  Account_No = 'SLMUM006200006328'
     AND Report_Date = '2022-06-14';
   DELETE ENPA_Host_System_Status_tbl

    WHERE  Report_Date = '2022-06-14'
             AND Host_System_Name = 'indus';
   INSERT INTO ENPA_Host_System_Status_tbl
     ( SELECT Account_No ,
              Host_System_Name ,
              Main_Classification ,
              Report_Date ,
              Remarks ,
              Closed_Date ,
              Create_On 
       FROM finaclehost  );
   UPDATE ENPA_Host_System_Status_tbl
      SET Remarks = 'Closed'
    WHERE  Account_No = 'SLMUM006200006328'
     AND Report_Date = '2022-06-14';

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CORRECTFINACLEDATA" TO "ADF_CDR_RBL_STGDB";
