--------------------------------------------------------
--  DDL for Procedure CURRENTPROVISION_DETAILS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" 
(
  v_SecuredType IN VARCHAR2 DEFAULT ' ' ,
  v_Segment IN VARCHAR2 DEFAULT ' ' ,
  v_AccountId IN VARCHAR2 DEFAULT NULL 
)
AS
   --IF OBJECT_ID('TempDB..#temp') IS NOT NULL  
   --             DROP TABLE  #temp;  
   v_BorrowerName VARCHAR2(80) := ' ';
   v_CustomerEntityId NUMBER(10,0) := 0;
   v_AccountEntityId NUMBER(10,0) := 0;
   v_segmentcode VARCHAR2(10) := ' ';
   v_AssetClassName VARCHAR2(50) := ' ';
   v_segmentDescription VARCHAR2(10) := ' ';
   v_TimeKey NUMBER(10,0);
   v_cursor SYS_REFCURSOR;

BEGIN

   --SET @Timekey =(Select Timekey from SysDataMatrix where CurrentStatus='C')  
   SELECT Timekey 

     INTO v_Timekey
     FROM SysDataMatrix 
    WHERE  MOC_Initialised = 'Y'
             AND NVL(MOC_Frozen, 'N') = 'N';
   IF ( v_SecuredType = 'Secured' ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT D.ProvisionSecured 
           FROM PRO_RBL_MISDB_PROD.AccountCal_Hist C
                  LEFT JOIN DimProvision_Seg D   ON C.ProvisionAlt_Key = D.ProvisionAlt_Key
          WHERE  C.CustomerAcID = v_AccountId
                   AND C.EffectiveFromTimeKey <= v_Timekey
                   AND C.EffectiveToTimeKey >= v_Timekey ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_SecuredType = 'UnSecured' ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT D.ProvisionUnSecured 
           FROM PRO_RBL_MISDB_PROD.AccountCal_Hist C
                  LEFT JOIN DimProvision_Seg D   ON C.ProvisionAlt_Key = D.ProvisionAlt_Key
          WHERE  C.CustomerAcID = v_AccountId
                   AND C.EffectiveFromTimeKey <= v_Timekey
                   AND C.EffectiveToTimeKey >= v_Timekey ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CURRENTPROVISION_DETAILS" TO "ADF_CDR_RBL_STGDB";
