--------------------------------------------------------
--  DDL for Procedure CUST_GRID_PUI_PROD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" 
-- [Cust_grid_PUI] '1714222715864042'
 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

(
  v_AccountID IN VARCHAR2
)
AS
   v_Timekey NUMBER(10,0);
   v_cursor SYS_REFCURSOR;

BEGIN

   SELECT Timekey 

     INTO v_Timekey
     FROM SysDataMatrix 
    WHERE  CurrentStatus = 'C';
   --SET @Timekey=25999
   OPEN  v_cursor FOR
      SELECT CustomerID ,
             UCIFID ,
             AccountID ,
             CustomerName ,
             ProjectCategoryAlt_Key ,
             PC.ProjectCategoryDescription ,
             ProjectSubCategoryAlt_key ,
             PCS.ProjectCategorySubTypeDescription ,
             ProjectOwnerShipAlt_Key ,
             ProjectAuthorityAlt_key ,
             UTILS.CONVERT_TO_VARCHAR2(OriginalDCCO,10,p_style=>103) OriginalDCCO  ,
             OriginalProjectCost ,
             OriginalDebt ,
             ProjectSubCatDescription ,
             'UpdatePUI' TableName  
        FROM AdvAcPUIDetailMain PUI
               JOIN ProjectCategory PC   ON PC.ProjectCategoryAltKey = PUI.ProjectCategoryAlt_Key
               AND PUI.EffectiveFromTimeKey <= v_Timekey
               AND PUI.EffectiveToTimeKey >= v_Timekey
               AND PC.EffectiveFromTimeKey <= v_Timekey
               AND PC.EffectiveToTimeKey >= v_Timekey
               LEFT JOIN ProjectCategorySubType PCS   ON PCS.ProjectCategorySubTypeAltKey = PUI.ProjectSubCategoryAlt_key
               AND PC.ProjectCategoryAltKey = PCS.ProjectCategoryTypeAltKey
               AND PCS.EffectiveFromTimeKey <= v_Timekey
               AND PCS.EffectiveToTimeKey >= v_Timekey
       WHERE  PUI.AccountID = v_AccountID ;
      DBMS_SQL.RETURN_RESULT(v_cursor);--select * from AdvAcPUIDetailMain
   --select * from ProjectCategory ---where ProjectCategoryAltKey=2
   --select * from ProjectCategorySubType

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CUST_GRID_PUI_PROD" TO "ADF_CDR_RBL_STGDB";
