--------------------------------------------------------
--  DDL for Procedure DGU_ALL_DPD_REPORT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" 
AS
   v_Date VARCHAR2(200) := ( SELECT UTILS.CONVERT_TO_VARCHAR2(date_,200) 
     FROM Automate_Advances 
    WHERE  EXT_FLG = 'Y' );
   v_timekey NUMBER(10,0) := ( SELECT Timekey 
     FROM Automate_Advances 
    WHERE  EXT_FLG = 'Y' );

BEGIN

   EXECUTE IMMEDIATE ' TRUNCATE TABLE DGU_AccountDPD_Report ';
   INSERT INTO DGU_AccountDPD_Report
     ( SELECT B.Date_ ProcessDate  ,
              D.UCIF_ID ,
              c.RefCustomerID CustomerID  ,
              c.CustomerAcID AccountID  ,
              A.DPD_IntService ,
              A.DPD_NoCredit ,
              A.DPD_Overdrawn ,
              A.DPD_Overdue ,
              A.DPD_Renewal ,
              A.DPD_StockStmt ,
              A.DPD_PrincOverdue ,
              A.DPD_IntOverdueSince ,
              A.DPD_OtherOverdueSince ,
              A.DPD_MAX ,
              v_Date 
       FROM PRO_RBL_MISDB_PROD.Accountcal_hist_DPD a
              JOIN Automate_Advances b   ON a.TimeKey = b.Timekey
              JOIN AdvAcBasicDetail c   ON c.AccountEntityID = a.AccountEntityid
              AND c.EffectiveFromTimeKey <= v_timekey
              AND c.EffectiveToTimeKey >= v_timekey
              JOIN CustomerBasicDetail D   ON c.CustomerEntityId = D.CustomerEntityId
              AND D.EffectiveFromTimeKey <= v_timekey
              AND D.EffectiveToTimeKey >= v_timekey
        WHERE  a.TimeKey = v_timekey );

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DGU_ALL_DPD_REPORT" TO "ADF_CDR_RBL_STGDB";
