--------------------------------------------------------
--  DDL for Procedure EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" 
AS
   v_Timekey NUMBER(10,0);
   v_CustomerACID VARCHAR2(50);
   v_cursor SYS_REFCURSOR;

BEGIN

   SELECT TimeKey 

     INTO v_Timekey
     FROM SysDataMatrix 
    WHERE  CurrentStatus = 'C';

   BEGIN
      OPEN  v_cursor FOR
         SELECT ParameterAlt_Key ,
                ParameterName ,
                'DegrationFlag' TableName  
           FROM DimParameter A
          WHERE  DimParameterName = 'UploadFLagType'
                   AND ParameterName IN ( 'TWO','Fraud Committed' --,'Restructure','Benami Loans','Sub Lending','Absconding','IBPC','Securitization','PUI','SaletoARC','SMA-0','RP (Resolution Plan)')
                  )

                   AND A.EffectiveFromTimeKey <= v_Timekey
                   AND A.EffectiveToTimeKey >= v_Timekey ;
         DBMS_SQL.RETURN_RESULT(v_cursor);
      SourceSystemDropDown() ;

   END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."EXCEPTIONALDEGRATIONCUSTOMERFLAGDROPDOWN_BACKUP_25022022" TO "ADF_CDR_RBL_STGDB";
