--------------------------------------------------------
--  DDL for Procedure GETADHOCCUSTOMERDETAILS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" 
-----------------------------------------

(
  --declare
  v_UCIF_ID IN VARCHAR2 DEFAULT ' ' 
)
AS
   v_Timekey NUMBER(10,0);
   v_cursor SYS_REFCURSOR;
--  exec GetAdhocCustomerDetails @UCIF_ID='55'

BEGIN

   SELECT TimeKey 

     INTO v_Timekey
     FROM SysDataMatrix 
    WHERE  CurrentStatus = 'C';
   --SET @Timekey =(Select LastMonthDateKey from SysDayMatrix where Timekey=@Timekey) 
   IF  --SQLDEV: NOT RECOGNIZED
   ----IF ((@UCIF_ID ='' or (@UCIF_ID is null)))
   --begin
   IF tt_tmp_1_4  --SQLDEV: NOT RECOGNIZED
   DELETE FROM tt_tmp_1_4;
   UTILS.IDENTITY_RESET('tt_tmp_1_4');

   INSERT INTO tt_tmp_1_4 SELECT * 
        FROM ( SELECT A.UCIF_ID UCICID  ,
                      A.RefCustomerID CustomerId  ,
                      A.CustomerName ,
                      'AdhocCustDetails' TableName  ,
                      ROW_NUMBER() OVER ( ORDER BY A.refCustomerID DESC  ) RowNumber  
               FROM PRO_RBL_MISDB_PROD.CustomerCal_Hist A

               --inner join  PRO.CustomerCal_Hist B

               --on          A.CustomerId = B.RefCustomerID
               WHERE  A.UCIF_ID = v_UCIF_ID
                        AND A.EffectiveFromTimeKey <= v_Timekey
                        AND A.EffectiveToTimeKey >= v_Timekey ) 
             --end 
             R
       WHERE  RowNumber = 1;
   OPEN  v_cursor FOR
      SELECT * 
        FROM tt_tmp_1_4  ;
      DBMS_SQL.RETURN_RESULT(v_cursor);--select * from AdhocACL_ChangeDetails
   --select		
   --A.UCIF_ID
   --,A.CustomerId
   --,B.CustomerName 
   -- from		AdhocACL_ChangeDetails A
   --inner join  PRO.CustomerCal_Hist B
   --on          A.CustomerId = B.RefCustomerID
   --where      A. UCIF_ID ='55'
   --AND A.EffectiveFromTimeKey<=25992
   --AND A.EffectiveToTimeKey>=49999

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETADHOCCUSTOMERDETAILS" TO "ADF_CDR_RBL_STGDB";
