--------------------------------------------------------
--  DDL for Procedure GETSPCOMPARISONDTLS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" /* CREATED BY DF627 ON 18-07-24 FOR DISPLAYING THE CHANGES BETWEEN 2 SP'S */ CREATE PROC "dbo" . "GetSpComparisonDtls" AS BEGIN DROP TABLE IF  --SQLDEV: NOT RECOGNIZED
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   -- Drop temporary table if it exists
   -- Create a temporary table with the data from SpComparisonDtls
   IF tt_SpComparisonDtls ;  --SQLDEV: NOT RECOGNIZED
   DELETE FROM tt_SpComparisonDtls;
   UTILS.IDENTITY_RESET('tt_SpComparisonDtls');

   INSERT INTO tt_SpComparisonDtls ( 
   	SELECT * 
   	  FROM RBL_MISDB_PROD.SpComparisonDtls  );
   -- Update temporary table to set SpCode_v1 to NULL if it doesn't contain alphanumeric characters
   UPDATE tt_SpComparisonDtls
      SET SpCode_v1 = NULL
    WHERE  REGEXP_LIKE(SpCode_v1, '%[A-Za-z0-9]%');
   -- Update temporary table to set SpCode_v2 to NULL if it doesn't contain alphanumeric characters
   UPDATE tt_SpComparisonDtls
      SET SpCode_v2 = NULL
    WHERE  REGEXP_LIKE(SpCode_v2, '%[A-Za-z0-9]%');
   -- Select data from the temporary table with change descriptions
   OPEN  v_cursor FOR
      SELECT SpName ,
             SpCreatedBy ,
             SpCreatedDate ,
             NVL(SpCode_v1, ' ') SpCode_v1  ,
             SpLineNo_v1 ,
             SpModifiedDate_v1 ,
             SpModifiedBy_v1 ,
             NVL(SpCode_v2, ' ') SpCode_v2  ,
             SpLineNo_v2 ,
             SpModifiedDate_v2 ,
             SpModifiedBy_v2 ,
             CASE 
                  WHEN SpCode_v1 <> SpCode_v2
                    AND SpLineNo_v1 = SpLineNo_v2 THEN 'Code is modified'
                  WHEN NVL(SpCode_v1, ' ') <> ' '
                    AND NVL(SpCode_v2, ' ') = ' '
                    AND SpLineNo_v1 = SpLineNo_v2 THEN 'Code is removed'
                  WHEN NVL(SpCode_v1, ' ') = ' '
                    AND NVL(SpCode_v2, ' ') <> ' '
                    AND SpLineNo_v1 = SpLineNo_v2 THEN 'Code is added'
                  WHEN SpLineNo_v1 IS NULL
                    AND NVL(SpLineNo_v2, ' ') <> ' ' THEN 'New Lines are added'
                  WHEN SpLineNo_v2 IS NULL
                    AND NVL(SpLineNo_v1, ' ') <> ' ' THEN 'Existing Lines were removed'
             ELSE 'Code is same'
                END Change_Description  ,
             ProcessDate 
        FROM tt_SpComparisonDtls 
       WHERE  UTILS.CONVERT_TO_VARCHAR2(ProcessDate,200) = utils.dateadd('DD', -1
                                                                         --WHERE SPNAME = 'dbo.customerselect' --and ProcessDate = '2024-07-08 17:59:08.483'
                                                                         , UTILS.CONVERT_TO_VARCHAR2(SYSDATE,200))
        ORDER BY SpName,
                 ProcessDate DESC,
                 CASE 
                      WHEN SpLineNo_v1 IS NULL THEN SpLineNo_v2
                 ELSE SpLineNo_v1
                    END ;
      DBMS_SQL.RETURN_RESULT(v_cursor);-- Drop the temporary table
   TABLE IF  --SQLDEV: NOT RECOGNIZED
   IF tt_SpComparisonDtls ;  --SQLDEV: NOT RECOGNIZED

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GETSPCOMPARISONDTLS" TO "ADF_CDR_RBL_STGDB";
