--------------------------------------------------------
--  DDL for Procedure GLTALLYOUTPUT_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" 
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   DELETE FROM tt_BALANCESHEET_2;
   UTILS.IDENTITY_RESET('tt_BALANCESHEET_2');

   INSERT INTO tt_BALANCESHEET_2 ( 
   	SELECT BranchCode ,
           GLCODE ,
           SUM(BALANCE)  BALANCE  
   	  FROM AdvAcBasicDetail A
             JOIN AdvAcBalanceDetail B   ON A.AccountEntityId = B.AccountEntityId
             JOIN DimGL C   ON A.GLAlt_Key = C.GLAlt_Key
             AND C.EffectiveToTimeKey = 49999
   	 WHERE  A.EffectiveToTimeKey = 49999
              AND B.EffectiveToTimeKey = 49999
   	  GROUP BY BranchCode,GLCODE );
   OPEN  v_cursor FOR
      SELECT * ,
             (srcamount - crismacbalance) DIFF  
        FROM ( SELECT A.DT Date_  ,
                      A.sol_ID BranchCode  ,
                      GL_SUB_HEAD_CODE GlCode  ,
                      d_amt Debit_Amount  ,
                      c_amt Credit_Amount  ,
                      (CASE 
                            WHEN d_amt < c_amt THEN NVL(c_amt, 0) - NVL(d_amt, 0)
                      ELSE NVL(d_amt, 0) - NVL(c_amt, 0)
                         END) SrcAmount  ,
                      NVL(b.BALANCE, 0) CrisMacBalance  
               FROM DWH_DWH_sTG.gsh a
                      LEFT JOIN tt_BALANCESHEET_2 B   ON A.GL_SUB_HEAD_CODE = B.GLCode
                      AND A.sol_id = B.BranchCode
                WHERE  a.sol_Id = '0071'
                         AND ( c_amt > 0
                         OR d_amt > 0
                         OR BALANCE > 0 ) ) x
        ORDER BY GlCode ;
      DBMS_SQL.RETURN_RESULT(v_cursor);

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."GLTALLYOUTPUT_04122023" TO "ADF_CDR_RBL_STGDB";
