--------------------------------------------------------
--  DDL for Procedure HOSTSYSTEMDATAINSERT_FIS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" 
AS
   v_Date VARCHAR2(200) := ( SELECT utils.dateadd('DAY', -1, Date_) 
     FROM Automate_Advances 
    WHERE  Ext_flg = 'Y' );
--@Date date

BEGIN

   DELETE ENPA_Host_System_Status_tbl_FIS

    WHERE  Report_Date = v_Date
             AND Host_System_Name IN ( 'FIS' )
   ;
   INSERT INTO ENPA_Host_System_Status_tbl_FIS
     ( Account_No, Host_System_Name, Report_Date, Create_On )
     ( SELECT CustomerAcID AccountID  ,
              SourceName SourceSystemName  ,
              ProcessDate Dateofdata  ,
              SYSDATE 
       FROM ReverseFeedDataInsertSync 
        WHERE  UTILS.CONVERT_TO_VARCHAR2(ProcessDate,200) IN ( v_Date )

                 AND FinalAssetClassAlt_Key > 1
                 AND SourceName IN ( 'FIS' )
      );

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."HOSTSYSTEMDATAINSERT_FIS" TO "ADF_CDR_RBL_STGDB";
