--------------------------------------------------------
--  DDL for Procedure INSERT_SETTLEMENT_LITIGATION_RF
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" 
AS
   v_timekey NUMBER(10,0);

BEGIN

   SELECT Timekey 

     INTO v_Timekey
     FROM Automate_Advances 
    WHERE  EXT_FLG = 'Y';
   INSERT INTO RF_Settlement_Litigation
     ( AccountId, DateOfData, AcctFlag, EffectiveFromTimeKey, EffectiveToTimeKey, CreatedBy, DateCreated )
     ( SELECT A.ACID ,
              UTILS.CONVERT_TO_VARCHAR2(SYSDATE,200) DateOfData  ,
              'L' AcctFlag  ,
              v_timekey ,
              49999 ,
              'SSIS User' ,
              SYSDATE 
       FROM ExceptionFinalStatusType a
              LEFT JOIN RF_Settlement_Litigation b   ON a.ACID = b.AccountId
              AND b.EffectiveFromTimeKey <= v_timekey
              AND b.EffectiveToTimeKey >= v_timekey
              AND b.AcctFlag = 'L'
              JOIN RBL_MISDB_PROD.AdvAcBasicDetail C   ON C.CustomerACID = A.ACID
              AND C.EffectiveFromTimeKey <= v_timekey
              AND C.EffectiveToTimeKey >= v_timekey
              JOIN DIMSOURCEDB D   ON D.SourceAlt_Key = c.SourceAlt_Key
              AND D.EffectiveFromTimeKey <= v_timekey
              AND D.EffectiveToTimeKey >= v_timekey
        WHERE  a.StatusType = 'Litigation'
                 AND b.AccountId IS NULL
                 AND a.EffectiveFromTimeKey <= v_timekey
                 AND a.EffectiveToTimeKey >= v_timekey
                 AND D.SourceName = 'Finacle'
                 AND c.FacilityType IN ( 'CC','OD' )
      );
   INSERT INTO RF_Settlement_Litigation
     ( AccountId, DateOfData, AcctFlag, EffectiveFromTimeKey, EffectiveToTimeKey, CreatedBy, DateCreated )
     ( SELECT A.ACID AccountId  ,
              UTILS.CONVERT_TO_VARCHAR2(SYSDATE,200) DateOfData  ,
              'S' AcctFlag  ,
              v_timekey ,
              49999 ,
              'SSIS User' ,
              SYSDATE 
       FROM ExceptionFinalStatusType a -----OTS_Details a

              LEFT JOIN RF_Settlement_Litigation b   ON a.ACID = b.AccountId
              AND b.EffectiveFromTimeKey <= v_timekey
              AND b.EffectiveToTimeKey >= v_timekey
              AND b.AcctFlag = 'S'
              JOIN RBL_MISDB_PROD.AdvAcBasicDetail C   ON C.CustomerACID = A.ACID
              AND C.EffectiveFromTimeKey <= v_timekey
              AND C.EffectiveToTimeKey >= v_timekey
              JOIN DIMSOURCEDB D   ON D.SourceAlt_Key = c.SourceAlt_Key
              AND D.EffectiveFromTimeKey <= v_timekey
              AND D.EffectiveToTimeKey >= v_timekey
        WHERE  a.StatusType = 'Settlement'
                 AND b.AccountId IS NULL
                 AND a.EffectiveFromTimeKey <= v_timekey
                 AND a.EffectiveToTimeKey >= v_timekey
                 AND D.SourceName = 'Finacle'
                 AND c.FacilityType IN ( 'CC','OD' )
      );

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INSERT_SETTLEMENT_LITIGATION_RF" TO "ADF_CDR_RBL_STGDB";
