--------------------------------------------------------
--  DDL for Procedure INVESTMENTTXNDETAILSELECT_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" CREATE PROC "dbo" . "InvestmentTxnDetailSelect_04122023" @MenuId SMALLINT = 0 , @Mode TINYINT = 0 , @ParentColumnValue INT = 0 , @TimeKey INT = 49999 AS BEGIN DROP TABLE IF  --SQLDEV: NOT RECOGNIZED
(
  v_MenuId IN NUMBER DEFAULT 0 ,
  v_Mode IN NUMBER DEFAULT 0 ,
  v_ParentColumnValue IN NUMBER DEFAULT 0 ,
  v_TimeKey IN NUMBER DEFAULT 49999 
)
AS
   v_cursor SYS_REFCURSOR;
--DECLARE   @MenuId SMALLINT =637
--		, @Mode TINYINT =0
--		, @ParentColumnValue INT  =1
--		, @TimeKey INT = 49999

BEGIN

   IF tt_InvestmentTxnDetail_2  --SQLDEV: NOT RECOGNIZED
   DELETE FROM tt_InvestmentTxnDetail_2;
   UTILS.IDENTITY_RESET('tt_InvestmentTxnDetail_2');

   INSERT INTO tt_InvestmentTxnDetail_2 ( 
   	SELECT 'GridData' TableName  ,
           A.TxnEntityID BaseColumn  ,
           UTILS.CONVERT_TO_VARCHAR2(AcqDt,10,p_style=>103) AcqDt  ,
           ParameterName AcqModeAlt_Key  ,
           NVL(A.AuthorisationStatus, 'A') AuthorisationStatus  ,
           NVL(A.ModifiedBy, A.CreatedBy) CrModApBy  ,
           UTILS.CONVERT_TO_NUMBER(A.D2Ktimestamp,10,0) D2Ktimestamp  ,
           ChangeFields ,
           'N' IsMainTable  
   	  FROM InvestmentTxnDetail_MOD A
             JOIN ( SELECT TxnEntityID ,
                           MAX(EntityKey)  EntityKey  
                    FROM InvestmentTxnDetail_MOD 
                     WHERE  ( EffectiveFromTimeKey <= v_TimeKey
                              AND EffectiveToTimeKey >= v_TimeKey )
                              AND AuthorisationStatus IN ( 'NP','MP','DP','RM' )

                              AND AcqType = CASE 
                                                 WHEN v_MenuId = 636 THEN 'A'
                                                 WHEN v_MenuId = 637 THEN 'S'   END
                              AND InstrumentEntityID = v_ParentColumnValue
                      GROUP BY TxnEntityID ) B   ON A.EntityKey = B.EntityKey
             LEFT JOIN DimParameter DP   ON DP.EffectiveFromTimeKey <= v_TimeKey
             AND DP.EffectiveToTimeKey >= v_TimeKey
             AND DP.DimParameterName = CASE 
                                            WHEN v_MenuId = 636 THEN 'DimAcquistionOfSecurity'
                                            WHEN v_MenuId = 637 THEN 'DimSaleSecurity'   END
             AND A.AcqModeAlt_Key = DP.ParameterAlt_Key );
   INSERT INTO tt_InvestmentTxnDetail_2
     ( SELECT 'GridData' TableName  ,
              A.TxnEntityID BaseColumn  ,
              UTILS.CONVERT_TO_VARCHAR2(AcqDt,10,p_style=>103) AcqDt  ,
              ParameterName AcqModeAlt_Key  ,
              NVL(A.AuthorisationStatus, 'A') AuthorisationStatus  ,
              NVL(A.ModifiedBy, A.CreatedBy) CrModApBy  ,
              UTILS.CONVERT_TO_NUMBER(A.D2Ktimestamp,10,0) D2Ktimestamp  ,
              NULL ChangeFields  ,
              'Y' IsMainTable  
       FROM InvestmentTxnDetail A
              LEFT JOIN DimParameter DP   ON DP.EffectiveFromTimeKey <= v_TimeKey
              AND DP.EffectiveToTimeKey >= v_TimeKey
              AND DP.DimParameterName = CASE 
                                             WHEN v_MenuId = 636 THEN 'DimAcquistionOfSecurity'
                                             WHEN v_MenuId = 637 THEN 'DimSaleSecurity'   END
              AND A.AcqModeAlt_Key = DP.ParameterAlt_Key
        WHERE  ( A.EffectiveFromTimeKey <= v_TimeKey
                 AND A.EffectiveToTimeKey >= v_TimeKey )
                 AND NVL(A.AuthorisationStatus, 'A') = 'A'
                 AND AcqType = CASE 
                                    WHEN v_MenuId = 636 THEN 'A'
                                    WHEN v_MenuId = 637 THEN 'S'   END
                 AND InstrumentEntityID = v_ParentColumnValue );
   IF v_Mode = 16 THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT * 
           FROM tt_InvestmentTxnDetail_2 
          WHERE  IsMainTable = 'N' ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   ELSE

   BEGIN
      OPEN  v_cursor FOR
         SELECT * 
           FROM tt_InvestmentTxnDetail_2  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENTTXNDETAILSELECT_04122023" TO "ADF_CDR_RBL_STGDB";
