--------------------------------------------------------
--  DDL for Procedure MOCINITIALIZESELECTDATE_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" 
AS
   v_EXT_DATE VARCHAR2(20) := ( SELECT ExtDate 
     FROM SysDataMatrix 
    WHERE  CurrentStatus = 'C' );
   --print @EXT_DATE
   v_MONTH_END_DATE VARCHAR2(20) := ( SELECT EOMONTH(ExtDate) 
     FROM SysDataMatrix 
    WHERE  TIMEKEY = ( SELECT MAX(TIMEKEY)  + 1 
                       FROM SysDataMatrix 
                        WHERE  MOC_FROZEN = 'Y' ) );
   v_temp NUMBER(1, 0) := 0;
   v_cursor SYS_REFCURSOR;

BEGIN

   --Declare  @Check_date date =(select ExtDate from SYSDATAMATRIX where ( MOC_Initialised<>'Y' OR MOC_Frozen<>'Y'))
   --if  @Check_date is null
   BEGIN
      SELECT 1 INTO v_temp
        FROM DUAL
       WHERE NOT EXISTS ( SELECT 1 
                          FROM SysDataMatrix 
                           WHERE  ( MOC_Initialised = 'Y'
                                    OR MOC_Frozen = 'Y' ) );
   EXCEPTION
      WHEN OTHERS THEN
         NULL;
   END;

   IF v_temp = 1 THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT UTILS.CONVERT_TO_VARCHAR2(utils.dateadd('DD', -1, utils.dateadd('QQ', utils.datediff('QQ', 0, v_EXT_DATE), 0)),20,p_style=>103) EXTDATE  
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   ELSE

   BEGIN
      IF v_MONTH_END_DATE < v_EXT_DATE THEN

      BEGIN
         OPEN  v_cursor FOR
            SELECT UTILS.CONVERT_TO_VARCHAR2(EXTDATE,20,p_style=>103) EXTDATE  
              FROM SysDataMatrix 
             WHERE  EXTDATE = ( SELECT EOMONTH(ExtDate) 
                                FROM SysDataMatrix 
                                 WHERE  TIMEKEY = ( SELECT MAX(TIMEKEY)  + 1 
                                                    FROM SysDataMatrix 
                                                     WHERE  MOC_FROZEN = 'Y' ) )
                      AND NVL(MOC_INITIALISED, 'N') = 'N'
                      AND NVL(MOC_FROZEN, 'N') = 'N' ;
            DBMS_SQL.RETURN_RESULT(v_cursor);

      END;

      --SELECT Convert(Varchar(20),EXTDATE,103)EXTDATE FROM SYSDATAMATRIX WHERE EXTDATE=(

      --							SELECT EOMONTH(DATE) FROM SYSDAYMATRIX WHERE TIMEKEY=(

      --												SELECT MAX(TIMEKEY)+1 FROM SYSDATAMATRIX WHERE MOC_FROZEN='Y'

      --																)

      --	) AND ISNULL(MOC_INITIALISED,'N')='N' AND ISNULL(MOC_FROZEN,'N')='N'

      --select ExtDate,* from SYSDATAMATRIX where CurrentStatus='C'

      --select CONVERT(varchar,dateadd(d,-(day(getdate())),getdate()),103)
      ELSE

      BEGIN
         OPEN  v_cursor FOR
            SELECT DISTINCT ' ' EXTDATE  
              FROM SysDataMatrix  ;
            DBMS_SQL.RETURN_RESULT(v_cursor);

      END;
      END IF;

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."MOCINITIALIZESELECTDATE_04122023" TO "ADF_CDR_RBL_STGDB";
