--------------------------------------------------------
--  DDL for Procedure PROJ_SUBCATEGORY_PUI
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" 
(
  v_ProjectId IN NUMBER
)
AS
   v_TimeKey NUMBER(10,0);
   --Declare @ProjectId int=1
   v_cursor SYS_REFCURSOR;

BEGIN

   SELECT Timekey 

     INTO v_Timekey
     FROM SysDataMatrix 
    WHERE  CurrentStatus = 'C';
   OPEN  v_cursor FOR
      SELECT ProjectCategorySubTypeAltKey ,
             ProjectCategorySubTypeDescription ,
             'ProjectCategorySubType' TableName  
        FROM ProjectCategorySubType PC
       WHERE  PC.EffectiveFromTimeKey <= v_Timekey
                AND PC.EffectiveToTimeKey >= v_Timekey
                AND ProjectCategoryTypeAltKey = v_ProjectId ;
      DBMS_SQL.RETURN_RESULT(v_cursor);

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROJ_SUBCATEGORY_PUI" TO "ADF_CDR_RBL_STGDB";
