--------------------------------------------------------
--  DDL for Procedure RPT_SYSREPORTOUTPUTTYPE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" /*  
--==================================================================================================================
-Created By    :- Shubham Jain  
-Creation Date :- 06/05/2010  
-Modified By   :-MNS
-Modified Date :-21/06/2013
-Description   :- This is used to fecth Data for Select Report output Type Parameter 
--==================================================================================================================
*/
(
  v_ReportType IN VARCHAR2
)
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   ----Declare 
   ----@ReportType AS Varchar(10)=6
   IF ( v_ReportType IN ( 1,5 )
    ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT 'Summary' CustFacilityLabel  ,
                '3' CustFacilityValue  
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_ReportType IN ( 2 )
    ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT 'Customer Wise' CustFacilityLabel  ,
                '1' CustFacilityValue  
           FROM DUAL 
         UNION ALL 
         SELECT 'Facility Wise' CustFacilityLabel  ,
                '2' CustFacilityValue  
           FROM DUAL 
         UNION ALL 
         SELECT 'Summary' CustFacilityLabel  ,
                '3' CustFacilityValue  
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_ReportType IN ( 6 )
    ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT 'Customer Wise' CustFacilityLabel  ,
                '1' CustFacilityValue  
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_ReportType = 3 ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT 'Summary' CustFacilityLabel  ,
                '3' CustFacilityValue  
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_ReportType = 9 ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT 'Summary' CustFacilityLabel  ,
                '9' CustFacilityValue  
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RPT_SYSREPORTOUTPUTTYPE" TO "ADF_CDR_RBL_STGDB";
