--------------------------------------------------------
--  DDL for Procedure SECURITIZEDSUMMARYGRIDDATA_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" 
(
  v_UserLoginId IN VARCHAR2 DEFAULT NULL ,
  v_Menuid IN NUMBER DEFAULT NULL ,
  v_UploadId IN NUMBER DEFAULT NULL 
)
AS
   v_Timekey NUMBER(10,0);
   v_cursor SYS_REFCURSOR;
--DECLARE @Timekey INT=49999
--	,@UserLoginId VARCHAR(100)='FNASUPERADMIN'
--	,@Menuid INT=161

BEGIN

   SELECT MAX(Timekey)  

     INTO v_Timekey
     FROM RBL_MISDB_PROD.SysDayMatrix 
    WHERE  Date_ = UTILS.CONVERT_TO_VARCHAR2(SYSDATE,200);
   DBMS_OUTPUT.PUT_LINE(v_Timekey);
   OPEN  v_cursor FOR
      SELECT 'SecuritizedData' TableName  ,
             ROW_NUMBER() OVER ( ORDER BY PoolID  ) SrNo  ,
             UploadID ,
             SummaryID ,
             PoolID ,
             PoolName ,
             SecuritisationType ,
             NoOfAccount ,
             POS ,
             SecuritisationExposureAmt ,
             UTILS.CONVERT_TO_VARCHAR2(SecuritisationReckoningDate,20,p_style=>103) SecuritisationReckoningDate  ,
             UTILS.CONVERT_TO_VARCHAR2(SecuritisationMarkingDate,20,p_style=>103) SecuritisationMarkingDate  ,
             --,SecuritisationPortfolio
             UTILS.CONVERT_TO_VARCHAR2(MaturityDate,20,p_style=>103) MaturityDate  ,
             TotalPosBalance ,
             TotalInttReceivable 
        FROM SecuritizedSummary_stg 
       WHERE  UploadID = v_UploadId ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   GetSecuritizedType() ;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITIZEDSUMMARYGRIDDATA_04122023" TO "ADF_CDR_RBL_STGDB";
