--------------------------------------------------------
--  DDL for Procedure SP_RFDEGRADECOUNTREPORT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" 
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   DELETE FROM tt_AA_34;
   UTILS.IDENTITY_RESET('tt_AA_34');

   INSERT INTO tt_AA_34 SELECT DateofData ,
                               SourceSystemName Host_System  ,
                               COUNT(1)  COUNT  
        FROM ReverseFeedData 
       WHERE  AssetClass > 1
        GROUP BY DateofData,SourceSystemName
        ORDER BY DateofData,
                 SourceSystemName;
   ---------Degrade Report-------------------
   DELETE FROM tt_BB_3;
   UTILS.IDENTITY_RESET('tt_BB_3');

   INSERT INTO tt_BB_3 SELECT UTILS.CONVERT_TO_VARCHAR2(SD.Date_,20,p_style=>103) Process_date  ,
                              SourceName Host_System  ,
                              COUNT(1)  COUNT  
        FROM PRO_RBL_MISDB_PROD.AccountCal_Hist B
               JOIN SysDayMatrix SD   ON B.EffectiveFromTimeKey = SD.TimeKey
               JOIN PRO_RBL_MISDB_PROD.CustomerCal_Hist A   ON A.EffectiveFromTimeKey = SD.TimeKey
               AND A.CustomerEntityID = B.CustomerEntityID
               LEFT JOIN DIMSOURCEDB src   ON B.SourceAlt_Key = src.SourceAlt_Key
               AND src.EffectiveToTimeKey = 49999
               LEFT JOIN DimProduct PD   ON PD.ProductAlt_Key = B.PRODUCTALT_KEY
               AND PD.EffectiveToTimeKey = 49999
               LEFT JOIN DimAssetClass A2   ON A2.AssetClassAlt_Key = B.FinalAssetClassAlt_Key
               AND A2.EffectiveToTimeKey = 49999
               LEFT JOIN DimAcBuSegment S   ON B.ActSegmentCode = S.AcBuSegmentCode
               AND S.EffectiveToTimeKey = 49999
               LEFT JOIN DimBranch X   ON B.BranchCode = X.BranchCode
               AND X.EffectiveToTimeKey = 49999
       WHERE  InitialAssetClassAlt_Key = 1
                AND FinalAssetClassAlt_Key > 1
                AND UTILS.CONVERT_TO_VARCHAR2(SD.Date_,200) BETWEEN '07/01/2021' AND '11/01/2021'
        GROUP BY UTILS.CONVERT_TO_VARCHAR2(SD.Date_,20,p_style=>103),SourceName
        ORDER BY UTILS.CONVERT_TO_VARCHAR2(SD.Date_,20,p_style=>103),
                 SourceName;
   OPEN  v_cursor FOR
      SELECT UTILS.CONVERT_TO_VARCHAR2(DateofData,200,p_style=>105) Date_  ,
             A."Host System" ,
             A.COUNT DegradeRFCount  ,
             B.COUNT DegradeReportCount  ,
             (CASE 
                   WHEN A.COUNT = B.COUNT THEN 'TRUE'
             ELSE 'FALSE'
                END) STATUS  
        FROM tt_AA_34 A
               JOIN tt_BB_3 B   ON UTILS.CONVERT_TO_VARCHAR2(DateofData,200,p_style=>105) = UTILS.CONVERT_TO_VARCHAR2(Process_date,200,p_style=>105)
               AND A.Host_System = B.Host_System
        ORDER BY UTILS.CONVERT_TO_VARCHAR2(DateofData,200,p_style=>105) ;
      DBMS_SQL.RETURN_RESULT(v_cursor);

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFDEGRADECOUNTREPORT" TO "ADF_CDR_RBL_STGDB";
