--------------------------------------------------------
--  DDL for Procedure SP_RFACLMISMATCHQUERY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" 
AS
   v_Date VARCHAR2(200) := '01/02/2022';
   v_cursor SYS_REFCURSOR;

BEGIN

   OPEN  v_cursor FOR
      SELECT * 
        FROM ACL_NPA_DATA A
       WHERE  SourceName = 'Finacle'
                AND ( InitialAssetClassAlt_Key = 1
                AND FinalAssetClassAlt_Key > 1 )
                AND UTILS.CONVERT_TO_VARCHAR2(process_Date,200,p_style=>105) = v_Date ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   --		UNION
   OPEN  v_cursor FOR
      SELECT * 
        FROM ACL_UPG_DATA A
       WHERE  SourceName = 'Finacle'
                AND ( InitialAssetClassAlt_Key > 1
                AND FinalAssetClassAlt_Key = 1 )
                AND UTILS.CONVERT_TO_VARCHAR2(process_Date,200,p_style=>105) = v_Date ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   --	UNION
   OPEN  v_cursor FOR
      SELECT * 
        FROM ACL_NPA_DATA A
       WHERE  SourceName = 'Finacle'
                AND InitialAssetClassAlt_Key > 1
                AND FinalAssetClassAlt_Key > 1
                AND ( A.InitialAssetClassAlt_Key <> A.FinalAssetClassAlt_Key
                OR A.InitialNpaDt <> A.FinalNpaDt )
                AND UTILS.CONVERT_TO_VARCHAR2(process_Date,200,p_style=>105) = v_Date ;
      DBMS_SQL.RETURN_RESULT(v_cursor);

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RFACLMISMATCHQUERY" TO "ADF_CDR_RBL_STGDB";
