--------------------------------------------------------
--  DDL for Procedure SYSCURRENTTIMEKEY_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" 
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   /*TODO:SQLDEV*/ SET DATEFORMAT DMY /*END:SQLDEV*/
   DECLARE
      v_TIMEKEY NUMBER(10,0);

   BEGIN
      SELECT A.TimeKey 

        INTO v_TIMEKEY
        FROM SysDayMatrix a
               JOIN SysDataMatrix b   ON A.Date = b.MonthFirstDate
       WHERE  b.CurrentStatus = 'C';
      OPEN  v_cursor FOR
         SELECT UTILS.CONVERT_TO_CHAR(DataEffectiveFromDate,30,p_style=>103) MonthFirstDate  ,
                UTILS.CONVERT_TO_CHAR(DataEffectiveToDate,30,p_style=>103) MonthLastDate  ,
                UTILS.CONVERT_TO_CHAR('01/01/1950',30,p_style=>103) StartDate  ,
                --,@TIMEKEY AS TimeKey       
                MonthName ,
                CASE 
                     WHEN utils.month_(DataEffectiveToDate) <= 9 THEN '0' || UTILS.CONVERT_TO_VARCHAR2(utils.month_(DataEffectiveToDate),30)
                ELSE UTILS.CONVERT_TO_VARCHAR2(utils.month_(DataEffectiveToDate),30)
                   END || UTILS.CONVERT_TO_VARCHAR2(utils.year_(DataEffectiveToDate),30) MonthYear  ,
                Year ,
                Prev_Month_Key PrvTimeKey  ,
                CurrentStatus ,
                v_TIMEKEY EffectiveFromTimeKey  ,
                '49999' EffectiveToTimeKey  ,
                DataEffectiveToDate ,
                UTILS.CONVERT_TO_VARCHAR2(SYSDATE,11,p_style=>103) CurrentDate  ,
                B.TimeKey TimeKey  ,
                A.MonthName || ' (' || UTILS.CONVERT_TO_VARCHAR2(A.MonthFirstDate,10,p_style=>103) || ' - ' || UTILS.CONVERT_TO_VARCHAR2(A.MonthLastDate,10,p_style=>103) || ')' FreezeDate  
           FROM SysDataMatrix A
                  JOIN SysDayMatrix B   ON a.MonthLastDate = b.Date_
          WHERE  CurrentStatus = 'C' ;
         DBMS_SQL.RETURN_RESULT(v_cursor);--	BEGIN    
      --    SELECT TimeKey AS EffectiveFromTimeKey,  
      --     '9999' AS EffectiveToTimeKey  
      -- FROM SysDayMatrix   
      -- WHERE Date = (Select MonthFirstDate from SysDataMatrix  
      -- WHERE CurrentStatus = 'C'  )  
      --END  

   END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SYSCURRENTTIMEKEY_04122023" TO "ADF_CDR_RBL_STGDB";
