--------------------------------------------------------
--  DDL for Procedure UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" /*==================================        
AUTHER : SANJEEV KUMAR SHARMA        
CREATE DATE : 06-03-2017        
MODIFY DATE : 06-03-2017        
DESCRIPTION : Update WriteOffAmt AccountWise       
--EXEC [dbo].[UpdateWriteOffAmt_AccountWise] @TimeKey=4445     
================================================*/
(
  v_TimeKey IN NUMBER
)
AS
   --WHERE A.WriteOff_Flag = 'Y'          
   v_cursor SYS_REFCURSOR;

BEGIN

   BEGIN

      BEGIN
         --Update DBO.AccountCal Set NetBalance = 0          
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, NVL(A.WriteOffAmount, 0) AS WriteOffAmount
         FROM A ,RBL_MISDB_PROD.ACCOUNTCAL A ) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE 
         --SET WriteOffAmount = isnull(A.Balance,0)           
         SET WriteOffAmount = src.WriteOffAmount;

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT SQLERRM ERROR_MESSAGE  
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."UPDATEWRITEOFFAMT_ACCOUNTWISE_04122023" TO "ADF_CDR_RBL_STGDB";
