--------------------------------------------------------
--  DDL for Procedure USERLOGINAUXSELECT_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" 
(
  v_UserLoginID IN VARCHAR2,
  v_TimeKey IN NUMBER
)
AS
   ---------Variable Declaration--------
   v_UserRole_Key NUMBER(10,0);
   v_UserLocationCode VARCHAR2(10);
   v_UserLocation VARCHAR2(10);
   v_cursor SYS_REFCURSOR;

BEGIN

   ---------END--------------------------
   --------------SET VALUE---------------
   SELECT UserRoleAlt_Key 

     INTO v_UserRole_Key
     FROM DimUserInfo 
    WHERE  ( EffectiveFromTimeKey <= v_TimeKey
             AND EffectiveToTimeKey >= v_TimeKey )
             AND UserLoginID = v_UserLoginID;
   SELECT UserLocation 

     INTO v_UserLocation
     FROM DimUserInfo 
    WHERE  ( EffectiveFromTimeKey <= v_TimeKey
             AND EffectiveToTimeKey >= v_TimeKey )
             AND UserLoginID = v_UserLoginID;
   IF v_UserLocation <> 'HI' THEN

   BEGIN
      SELECT UserLocationCode 

        INTO v_UserLocationCode
        FROM DimUserInfo 
       WHERE  ( EffectiveFromTimeKey <= v_TimeKey
                AND EffectiveToTimeKey >= v_TimeKey )
                AND UserLoginID = v_UserLoginID;

   END;
   END IF;
   DBMS_OUTPUT.PUT_LINE(v_UserRole_Key);
   DBMS_OUTPUT.PUT_LINE(v_UserLocation);
   ------------END-----------------------
   IF v_UserRole_Key = 1 THEN

    --SUPER ADMIN
   BEGIN
      OPEN  v_cursor FOR
         SELECT UserLoginID ,
                UserName ,
                UserLocation ,
                UserLocationCode ,
                DimUserRole.UserRoleShortNameEnum RoleDescription  ,
                DimUserRole.UserRoleAlt_Key 
           FROM DimUserInfo 
                  JOIN DimUserRole    ON DimUserInfo.UserRoleAlt_Key = DimUserRole.UserRoleAlt_Key
          WHERE  ( DimUserInfo.EffectiveFromTimeKey <= v_TimeKey
                   AND DimUserInfo.EffectiveToTimeKey >= v_TimeKey )
                   AND UserLoginID <> (v_UserLoginID)
                   AND UserLogged = 1 ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF v_UserRole_Key = 2 THEN

    -- ADMIN
   BEGIN
      OPEN  v_cursor FOR
         SELECT UserLoginID ,
                UserName ,
                UserLocation ,
                UserLocationCode ,
                DimUserRole.UserRoleShortNameEnum RoleDescription  ,
                DimUserRole.UserRole_Key 
           FROM DimUserInfo 
                  JOIN DimUserRole    ON DimUserInfo.UserRoleAlt_Key = DimUserRole.UserRoleAlt_Key
          WHERE  ( DimUserInfo.EffectiveFromTimeKey <= v_TimeKey
                   AND DimUserInfo.EffectiveToTimeKey >= v_TimeKey )
                   AND UserLoginID <> (v_UserLoginID)
                   AND UserLogged = 1
                   AND DimUserInfo.UserRoleAlt_Key IN ( 2,3,4 )
       ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERLOGINAUXSELECT_04122023" TO "ADF_CDR_RBL_STGDB";
