--------------------------------------------------------
--  DDL for Procedure USERGROUPSAUXSELECT_08112021
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" 
--- exec [UserGroupsAuxSelect] 2922

(
  v_timekey IN NUMBER
)
AS
   --SELECT * FROM tt_TmpGroupMenuParent_3
   v_cursor SYS_REFCURSOR;

BEGIN

   ----SELECT EntityKey,DeptGroupId,REPLACE(DeptGroupCode,'#','') AS DeptGroupName,DeptGroupName AS DeptGroupDesc,Menus,DateCreated,EffectiveFromTimeKey,EffectiveToTimeKey 
   ----FROM DimUserDeptGroup
   ----WHERE EffectiveFromTimeKey <=3652 and EffectiveToTimeKey>=3652
   IF utils.object_id('Tempdb..tt_TmpGroupDtl_3') IS NOT NULL THEN
    EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_TmpGroupDtl_3 ';
   END IF;
   DELETE FROM tt_TmpGroupDtl_3;
   UTILS.IDENTITY_RESET('tt_TmpGroupDtl_3');

   INSERT INTO tt_TmpGroupDtl_3 ( 
   	SELECT EntityKey ,
           DeptGroupId ,
           REPLACE(DeptGroupCode, '#', ' ') DeptGroupName  ,
           DeptGroupName DeptGroupDesc  ,
           Menus ,
           DateCreated ,
           EffectiveFromTimeKey ,
           EffectiveToTimeKey 
   	  FROM DimUserDeptGroup 
   	 WHERE  EffectiveFromTimeKey <= v_timekey
              AND EffectiveToTimeKey >= v_timekey );
   IF utils.object_id('Tempdb..tt_TmpGroupMenuParent_3') IS NOT NULL THEN
    EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_TmpGroupMenuParent_3 ';
   END IF;
   DELETE FROM tt_TmpGroupMenuParent_3;
   UTILS.IDENTITY_RESET('tt_TmpGroupMenuParent_3');

   INSERT INTO tt_TmpGroupMenuParent_3 ( 
   	SELECT DeptGroupId ,
           B.ParentId 
   	  FROM ( SELECT DeptGroupId ,
                    DeptGroupName ,
                    DeptGroupDesc ,--,B.ParentId,

                    a_SPLIT.VALUE('.', 'VARCHAR(100)') Menus  
             FROM ( SELECT DeptGroupId ,
                           DeptGroupName ,
                           DeptGroupDesc ,
                           UTILS.CONVERT_TO_CLOB('<M>' || REPLACE(Menus, ',', '</M><M>') || '</M>') Menus  
                    FROM tt_TmpGroupDtl_3  ) A
                     /*TODO:SQLDEV*/ CROSS APPLY Menus.nodes ('/M') AS Split(a) /*END:SQLDEV*/  ) A
             JOIN SysCRisMacMenu B   ON UTILS.CONVERT_TO_NUMBER(A.Menus,10,0) = B.MenuId
   	  GROUP BY DeptGroupId,B.ParentId );
   OPEN  v_cursor FOR
      SELECT EntityKey ,
             T.DeptGroupId ,
             DeptGroupName ,
             DeptGroupDesc ,
             Menus || '|' || ParentID Menus  ,
             'Y' IsMainTable  ,
             DateCreated ,
             EffectiveFromTimeKey ,
             EffectiveToTimeKey --, ParentID

        FROM tt_TmpGroupDtl_3 T
               LEFT JOIN ( SELECT DeptGroupId ,
                                  ParentID 
                           FROM ( SELECT DeptGroupId ,
                                         utils.stuff(( SELECT ',' || UTILS.CONVERT_TO_VARCHAR2(ParentId,10) 
        FROM tt_TmpGroupMenuParent_3 M1
       WHERE  M2.DeptGroupId = M1.DeptGroupId ), 1, 1, ' ') ParentID  
                                  FROM tt_TmpGroupMenuParent_3 M2 ) B
                             GROUP BY DeptGroupId,ParentID ) B   ON T.DeptGroupId = B.DeptGroupId ;
      DBMS_SQL.RETURN_RESULT(v_cursor);

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USERGROUPSAUXSELECT_08112021" TO "ADF_CDR_RBL_STGDB";
