--------------------------------------------------------
--  DDL for Procedure USER_DETAILS_AUDIT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" 
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   OPEN  v_cursor FOR
      SELECT UserLoginID ,
             UserName ,
             Activate ,
             Email_ID ,
             MobileNo ,
             D.DeptGroupName ,
             Designation ,
             IP_Address ,
             LoginTime ,
             LogoutTime ,
             LoginSucceeded ,
             MD.ScreenName menu_name  

        --,case when logstatus='P' then 'Pending' 

        --     when logstatus='R' then 'Reject' 

        --	 when logstatus='A' then 'Approved' end as logstatus
        FROM DimUserInfo a
               JOIN UserLoginHistory c   ON a.UserLoginID = c.UserID
               JOIN DimUserDeptGroup D   ON a.DepartmentId = D.DeptGroupId
               JOIN SysUserActivityLog_Attendence b   ON b.LogCreatedBy = a.UserLoginID
               JOIN MetaScreenFieldDetail MD   ON B.MenuID = MD.MenuId
       WHERE  a.EffectiveToTimeKey = 49999
                AND a.Activate = 'Y'
                AND UTILS.CONVERT_TO_VARCHAR2(LoginTime,200) >= '2022-03-01'
                AND LogoutTime IS NOT NULL
        ORDER BY UserLoginID,
                 LoginTime ;
      DBMS_SQL.RETURN_RESULT(v_cursor);

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USER_DETAILS_AUDIT" TO "ADF_CDR_RBL_STGDB";
