--------------------------------------------------------
--  DDL for Procedure USP_ASSETCLASSNAME
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" 
--Select * from DimAssetClass

(
  v_AssetClassAlt_Key IN NUMBER
)
AS
   v_cursor SYS_REFCURSOR;
--Declare  @AssetClassAlt_Key as int =6

BEGIN

   IF ( v_AssetClassAlt_Key = 1 ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT AssetClassAlt_Key ,
                AssetClassName 
           FROM DimAssetClass 
          WHERE  AssetClassAlt_Key = 2 ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_AssetClassAlt_Key = 2 ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT AssetClassAlt_Key ,
                AssetClassName 
           FROM DimAssetClass 
          WHERE  AssetClassAlt_Key IN ( 1,3 )
       ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_AssetClassAlt_Key = 3 ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT AssetClassAlt_Key ,
                AssetClassName 
           FROM DimAssetClass 
          WHERE  AssetClassAlt_Key IN ( 2,4 )
       ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_AssetClassAlt_Key = 4 ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT AssetClassAlt_Key ,
                AssetClassName 
           FROM DimAssetClass 
          WHERE  AssetClassAlt_Key IN ( 3,5 )
       ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_AssetClassAlt_Key = 5 ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT AssetClassAlt_Key ,
                AssetClassName 
           FROM DimAssetClass 
          WHERE  AssetClassAlt_Key IN ( 4,6 )
       ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;
   IF ( v_AssetClassAlt_Key = 6 ) THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT AssetClassAlt_Key ,
                AssetClassName 
           FROM DimAssetClass 
          WHERE  AssetClassAlt_Key IN ( 5 )
       ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."USP_ASSETCLASSNAME" TO "ADF_CDR_RBL_STGDB";
