--------------------------------------------------------
--  Constraints for Table ACCOUNTCAL_HIST_BACKUP_07082023
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."ACCOUNTCAL_HIST_BACKUP_07082023" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."ACCOUNTCAL_HIST_BACKUP_07082023" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."ACCOUNTCAL_HIST_BACKUP_07082023" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."ACCOUNTCAL_HIST_BACKUP_07082023" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
