--------------------------------------------------------
--  Constraints for Table CUSTOMERCAL_HIST_19102024_1
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."CUSTOMERCAL_HIST_19102024_1" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."CUSTOMERCAL_HIST_19102024_1" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."CUSTOMERCAL_HIST_19102024_1" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."CUSTOMERCAL_HIST_19102024_1" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
