--------------------------------------------------------
--  Constraints for Table GTT_ACDATA
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."GTT_ACDATA" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."GTT_ACDATA" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."GTT_ACDATA" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."GTT_ACDATA" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
