--------------------------------------------------------
--  Constraints for Table PACKAGE_AUDITHIST
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."PACKAGE_AUDITHIST" MODIFY ("IDENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."PACKAGE_AUDITHIST" MODIFY ("PACKAGENAME" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."PACKAGE_AUDITHIST" MODIFY ("TABLENAME" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."PACKAGE_AUDITHIST" MODIFY ("EXECUTIONSTATUS" NOT NULL ENABLE);
