--------------------------------------------------------
--  Constraints for Table TT_ADVACBALANCEDETAIL_6
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."TT_ADVACBALANCEDETAIL_6" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVACBALANCEDETAIL_6" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVACBALANCEDETAIL_6" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
