--------------------------------------------------------
--  Constraints for Table TT_ADVACBALANCEDETAIL_10
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."TT_ADVACBALANCEDETAIL_10" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVACBALANCEDETAIL_10" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVACBALANCEDETAIL_10" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
