--------------------------------------------------------
--  Constraints for Table TT_ADVCUSTNPADETAIL_6
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."TT_ADVCUSTNPADETAIL_6" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVCUSTNPADETAIL_6" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVCUSTNPADETAIL_6" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
