--------------------------------------------------------
--  Constraints for Table TT_ADVCUSTNPADETAIL_8
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."TT_ADVCUSTNPADETAIL_8" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVCUSTNPADETAIL_8" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVCUSTNPADETAIL_8" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
