--------------------------------------------------------
--  Constraints for Table TT_ADVCUSTNPADETAIL_2
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."TT_ADVCUSTNPADETAIL_2" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVCUSTNPADETAIL_2" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVCUSTNPADETAIL_2" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
