--------------------------------------------------------
--  Constraints for Table TT_ADVACFINANCIALDETAIL_5
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."TT_ADVACFINANCIALDETAIL_5" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVACFINANCIALDETAIL_5" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."TT_ADVACFINANCIALDETAIL_5" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
