--------------------------------------------------------
--  DDL for View ACDAILYTXNDETAIL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RBL_MISDB_PROD"."ACDAILYTXNDETAIL" ("ENTITYKEY", "BRANCHCODE", "CUSTOMERID", "CUSTOMERACID", "ACCOUNTENTITYID", "TXNDATE", "TXNTYPE", "TXNSUBTYPE", "TXNTIME", "CURRENCYALT_KEY", "CURRENCYCONVRATE", "TXNAMOUNT", "TXNAMOUNTINCURRENCY", "EXTDATE", "TXNREFNO", "TXNVALUEDATE", "MNEMONICCODE", "PARTICULAR", "AUTHORISATIONSTATUS", "CREATEDBY", "DATECREATED", "MODIFIEDBY", "DATEMODIFIED", "APPROVEDBY", "DATEAPPROVED", "D2KTIMESTAMP", "REMARK", "TRUECREDIT", "ISPROCESSED", "BALANCE") AS 
  SELECT "ENTITYKEY","BRANCHCODE","CUSTOMERID","CUSTOMERACID","ACCOUNTENTITYID","TXNDATE","TXNTYPE","TXNSUBTYPE","TXNTIME","CURRENCYALT_KEY","CURRENCYCONVRATE","TXNAMOUNT","TXNAMOUNTINCURRENCY","EXTDATE","TXNREFNO","TXNVALUEDATE","MNEMONICCODE","PARTICULAR","AUTHORISATIONSTATUS","CREATEDBY","DATECREATED","MODIFIEDBY","DATEMODIFIED","APPROVEDBY","DATEAPPROVED","D2KTIMESTAMP","REMARK","TRUECREDIT","ISPROCESSED","BALANCE" 
     FROM CURDAT_RBL_MISDB_PROD.AcDailyTxnDetail
;
