--------------------------------------------------------
--  DDL for View ADVCREDITCARDBALANCEDETAIL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RBL_MISDB_PROD"."ADVCREDITCARDBALANCEDETAIL" ("ENTITYKEY", "ACCOUNTENTITYID", "CREDITCARDENTITYID", "BALANCE_POS", "BALANCE_LOAN", "BALANCE_INT", "BALANCE_GST", "BALANCE_FEES", "REFSYSTEMACID", "AUTHORISATIONSTATUS", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY", "CREATEDBY", "DATECREATED", "MODIFIEDBY", "DATEMODIFIED", "APPROVEDBY", "DATEAPPROVED", "D2KTIMESTAMP", "MOCSTATUS", "MOCDATE") AS 
  SELECT "ENTITYKEY","ACCOUNTENTITYID","CREDITCARDENTITYID","BALANCE_POS","BALANCE_LOAN","BALANCE_INT","BALANCE_GST","BALANCE_FEES","REFSYSTEMACID","AUTHORISATIONSTATUS","EFFECTIVEFROMTIMEKEY","EFFECTIVETOTIMEKEY","CREATEDBY","DATECREATED","MODIFIEDBY","DATEMODIFIED","APPROVEDBY","DATEAPPROVED","D2KTIMESTAMP","MOCSTATUS","MOCDATE" 
     FROM CurDat_RBL_MISDB_PROD.AdvCreditCardBalanceDetail
;
