--------------------------------------------------------
--  DDL for View ADVSECURITYVALUEDETAIL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL" ("ENTITYKEY", "SECURITYENTITYID", "VALUATIONSOURCEALT_KEY", "VALUATIONDATE", "CURRENTVALUE", "VALUATIONEXPIRYDATE", "AUTHORISATIONSTATUS", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY", "CREATEDBY", "DATECREATED", "MODIFIEDBY", "DATEMODIFIED", "APPROVEDBY", "DATEAPPROVED", "D2KTIMESTAMP", "CURRENTVALUESOURCE", "COLLATERALVALUEATTHETIMEOFLASTREVIEWINRS", "COLLATERALID", "EXPIRYBUSINESSRULE", "PERIODINMONTH", "SECURITYVALUEMAIN") AS 
  SELECT "ENTITYKEY","SECURITYENTITYID","VALUATIONSOURCEALT_KEY","VALUATIONDATE","CURRENTVALUE","VALUATIONEXPIRYDATE","AUTHORISATIONSTATUS","EFFECTIVEFROMTIMEKEY","EFFECTIVETOTIMEKEY","CREATEDBY","DATECREATED","MODIFIEDBY","DATEMODIFIED","APPROVEDBY","DATEAPPROVED","D2KTIMESTAMP","CURRENTVALUESOURCE","COLLATERALVALUEATTHETIMEOFLASTREVIEWINRS","COLLATERALID","EXPIRYBUSINESSRULE","PERIODINMONTH","SECURITYVALUEMAIN" 
     FROM CurDat_RBL_MISDB_PROD.AdvSecurityValueDetail
;
