--------------------------------------------------------
--  DDL for View INVESTMENTISSUERDETAIL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RBL_MISDB_PROD"."INVESTMENTISSUERDETAIL" ("ENTITYKEY", "BRANCHCODE", "ISSUERENTITYID", "ISSUERID", "ISSUERNAME", "RATINGSTATUS", "ISSUERACCPRATING", "ISSUERACCPRATINGDT", "ISSUERRATINGAGENCY", "REF_TXN_SYS_CUST_ID", "ISSUER_CATEGORY_CODE", "GRPENTITYOFBANK", "AUTHORISATIONSTATUS", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY", "CREATEDBY", "DATECREATED", "MODIFIEDBY", "DATEMODIFIED", "APPROVEDBY", "DATEAPPROVED", "SOURCEALT_KEY", "UCIFID", "PANNO", "SETTLEMENT_FLAG", "SETTLEMENT_DATE") AS 
  SELECT "ENTITYKEY","BRANCHCODE","ISSUERENTITYID","ISSUERID","ISSUERNAME","RATINGSTATUS","ISSUERACCPRATING","ISSUERACCPRATINGDT","ISSUERRATINGAGENCY","REF_TXN_SYS_CUST_ID","ISSUER_CATEGORY_CODE","GRPENTITYOFBANK","AUTHORISATIONSTATUS","EFFECTIVEFROMTIMEKEY","EFFECTIVETOTIMEKEY","CREATEDBY","DATECREATED","MODIFIEDBY","DATEMODIFIED","APPROVEDBY","DATEAPPROVED","SOURCEALT_KEY","UCIFID","PANNO","SETTLEMENT_FLAG","SETTLEMENT_DATE" 
     FROM CurDat_RBL_MISDB_PROD.InvestmentIssuerDetail
;
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENTISSUERDETAIL" TO "ETL_TEMP_RBL_TEMPDB";
