--------------------------------------------------------
--  DDL for Index ADVFACNFDETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREMOC_RBL_MISDB_PROD"."ADVFACNFDETAIL_PK" ON "PREMOC_RBL_MISDB_PROD"."ADVFACNFDETAIL" ("ACCOUNTENTITYID", "LCBGNO", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
