--------------------------------------------------------
--  DDL for Function DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" 
(
  v_UserLoginID IN VARCHAR2,
  v_Result OUT NUMBER
)
RETURN NUMBER
AS
   v_temp NUMBER(1, 0) := 0;
   v_cursor SYS_REFCURSOR;

BEGIN

   BEGIN
      SELECT 1 INTO v_temp
        FROM DUAL
       WHERE 0 < ( SELECT COUNT(*)  
                   FROM DPD_90Days_HistoryCSVUpload  );
   EXCEPTION
      WHEN OTHERS THEN
         NULL;
   END;

   IF v_temp = 1 THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT * 
           FROM DPD_90Days_HistoryCSVUpload  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);--WHERE UserLoginId = @UserLoginID
      EXECUTE IMMEDIATE ' TRUNCATE TABLE DPD_90Days_HistoryCSVUpload ';
      OPEN  v_cursor FOR
         SELECT CASE 
                     WHEN NVL(COUNT, 0) = 0 THEN 0
                ELSE COUNT
                   END COUNT  ,
                FILENAME ,
                UserLoginId ,
                'SuccessCountDetails' TableName  
           FROM IRAC_Success_DPDHistory_UploadCount 
          WHERE  UserLoginId = v_UserLoginID ;
         DBMS_SQL.RETURN_RESULT(v_cursor);
      DBMS_OUTPUT.PUT_LINE('Result=1');
      v_Result := 1 ;
      RETURN v_Result;

   END;
   ELSE

   BEGIN
      DBMS_OUTPUT.PUT_LINE('Result=0');
      v_Result := 0 ;
      RETURN v_Result;

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DPD_90DAYS_HISTORYREPORTFRONTEND_PROCESSCOUNT" TO "ADF_CDR_RBL_STGDB";
