--------------------------------------------------------
--  DDL for Function INVESTENBASICDETAILINUP_15122023
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" 
(
  v_BranchCode IN VARCHAR2 DEFAULT ' ' ,
  v_InvEntityId IN NUMBER DEFAULT 0 ,
  v_InvID IN VARCHAR2 DEFAULT ' ' ,
  v_IssuerEntityId IN NUMBER DEFAULT 0 ,
  v_RefIssuerID IN VARCHAR2 DEFAULT ' ' ,
  v_EntityKey IN NUMBER DEFAULT 0 ,
  v_ISIN IN VARCHAR2 DEFAULT ' ' ,
  v_InstrTypeAlt_Key IN NUMBER DEFAULT 0 ,
  v_InstrName IN VARCHAR2 DEFAULT ' ' ,
  v_InvestmentNature IN VARCHAR2 DEFAULT ' ' ,
  v_InternalRating IN NUMBER DEFAULT 0 ,
  iv_InRatingDate IN VARCHAR2 DEFAULT ' ' ,
  iv_InRatingExpiryDate IN VARCHAR2 DEFAULT ' ' ,
  v_ExRating IN NUMBER DEFAULT 0 ,
  v_ExRatingAgency IN NUMBER DEFAULT 0 ,
  iv_ExRatingDate IN VARCHAR2 DEFAULT ' ' ,
  iv_ExRatingExpiryDate IN VARCHAR2 DEFAULT ' ' ,
  v_Sector IN VARCHAR2 DEFAULT ' ' ,
  v_Industry_AltKey IN NUMBER DEFAULT 0 ,
  v_ListedStkExchange IN CHAR,
  v_ExposureType IN VARCHAR2 DEFAULT ' ' ,
  v_SecurityValue IN NUMBER DEFAULT 0.0 ,
  iv_MaturityDt IN VARCHAR2 DEFAULT ' ' ,
  iv_ReStructureDate IN VARCHAR2 DEFAULT ' ' ,
  v_MortgageStatus IN CHAR DEFAULT ' ' ,
  v_NHBStatus IN CHAR DEFAULT ' ' ,
  v_ResiPurpose IN CHAR DEFAULT ' ' ,
  v_ScrCrError IN VARCHAR2 DEFAULT ' ' ,
  v_ExEntityKey IN NUMBER DEFAULT 0 ,
  v_Remark IN VARCHAR2 DEFAULT ' ' ,
  v_MenuID IN NUMBER DEFAULT 0 ,
  v_OperationFlag IN NUMBER DEFAULT 0 ,
  v_AuthMode IN CHAR DEFAULT 'N' ,
  v_IsMOC IN CHAR DEFAULT 'N' ,
  v_EffectiveFromTimeKey IN NUMBER DEFAULT 0 ,
  v_EffectiveToTimeKey IN NUMBER DEFAULT 0 ,
  v_TimeKey IN NUMBER DEFAULT 0 ,
  v_CrModApBy IN VARCHAR2 DEFAULT ' ' ,
  v_D2Ktimestamp OUT NUMBER/* DEFAULT 0*/,
  v_Result OUT NUMBER/* DEFAULT 0*/,
  v_BlnSCD2ForInvestmentBasicDetail IN CHAR DEFAULT 'Y' ,
  v_Basic_ChangeFields IN VARCHAR2 DEFAULT ' ' 
)
RETURN NUMBER
AS
   v_InRatingDate VARCHAR2(10) := iv_InRatingDate;
   v_InRatingExpiryDate VARCHAR2(10) := iv_InRatingExpiryDate;
   v_ExRatingDate VARCHAR2(10) := iv_ExRatingDate;
   v_ExRatingExpiryDate VARCHAR2(10) := iv_ExRatingExpiryDate;
   v_MaturityDt VARCHAR2(10) := iv_MaturityDt;
   v_ReStructureDate VARCHAR2(10) := iv_ReStructureDate;
   v_AuthorisationStatus CHAR(2) := NULL;
   v_CreatedBy VARCHAR2(20) := NULL;
   v_DATECreated DATE := NULL;
   v_Modifiedby VARCHAR2(20) := NULL;
   v_DateModified DATE := NULL;
   v_ApprovedBy VARCHAR2(20) := NULL;
   v_DateApproved DATE := NULL;
   v_ExAccount_Key NUMBER(10,0) := 0;
   v_ErrorHandle NUMBER(10,0) := 0;
   --FOR MOC
   v_MocFromTimeKey NUMBER(10,0) := 0;
   v_MocToTimeKey NUMBER(10,0) := 0;
   v_MocTypeAlt_Key NUMBER(10,0) := 0;
   v_MocDate DATE := NULL;
   v_AppAvail CHAR;

BEGIN

   v_InRatingDate := UTILS.CONVERT_TO_VARCHAR2(NULLIF(v_InRatingDate, ' '),200,p_style=>103) ;
   v_InRatingExpiryDate := UTILS.CONVERT_TO_VARCHAR2(NULLIF(v_InRatingExpiryDate, ' '),200,p_style=>103) ;
   v_ExRatingDate := UTILS.CONVERT_TO_VARCHAR2(NULLIF(v_ExRatingDate, ' '),200,p_style=>103) ;
   v_ExRatingExpiryDate := UTILS.CONVERT_TO_VARCHAR2(NULLIF(v_ExRatingExpiryDate, ' '),200,p_style=>103) ;
   v_MaturityDt := UTILS.CONVERT_TO_VARCHAR2(NULLIF(v_MaturityDt, ' '),200,p_style=>103) ;
   v_ReStructureDate := UTILS.CONVERT_TO_VARCHAR2(NULLIF(v_ReStructureDate, ' '),200,p_style=>103) ;
   v_MocDate := UTILS.CONVERT_TO_VARCHAR2(NULLIF(v_MocDate, ' '),200,p_style=>103) ;
   DBMS_OUTPUT.PUT_LINE('InvestmentBasicDetailInUP');
   SELECT ParameterValue 

     INTO v_AppAvail
     FROM SysSolutionParameter 
    WHERE  ParameterAlt_Key = 6;
   IF ( v_AppAvail = 'N' ) THEN

   BEGIN
      v_Result := -11 ;
      RETURN v_Result;

   END;
   END IF;
   IF v_OperationFlag = 1 THEN

    --- add
   BEGIN
      DBMS_OUTPUT.PUT_LINE(5);
      -----CHECK DUPLICATE BILL NO AT BRANCH LEVEL
      -- CUSTOMERID ALEADY EXISTS
      --SELECT * from SysSolutionParameter WHERE ParameterName= 'ClientName'
      --EntityID asked to sunil sir for mod taBle 
      Seq_InvEntityId  --SQLDEV: NOT RECOGNIZED
      DBMS_OUTPUT.PUT_LINE(v_InvEntityId);

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTENBASICDETAILINUP_15122023" TO "ADF_CDR_RBL_STGDB";
