--------------------------------------------------------
--  DDL for Function INVOKEDUSERSUSPENDUPDATE_08112021
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" 
-- =============================================
 -- Author:		<Shivendra Singh>
 -- Create date: <27/07/2010>
 -- Description:	<In Dimuser info update flage for susped user,,>
 -- =============================================

(
  v_UserLoginID IN VARCHAR2,
  v_LoginPassword IN VARCHAR2,
  v_TimeKey IN NUMBER,-- NITIN : 21 DEC 2010
  v_ModifiedBy IN VARCHAR2,-- shailesh 11/06/2014
  v_Result OUT NUMBER/* DEFAULT 0*/
)
RETURN NUMBER
AS
   --Declare @TimeKey INT -- NITIN : 21 DEC 2010
   --SET @TimeKey =(SELECT  MonthKey  FROM    DimMonthMatrix  WHERE  CurrentStatus = 'C')    -- NITIN : 21 DEC 2010
   --SELECT @Timekey=Max(Timekey) from SysProcessingCycle  
   --  WHERE Extracted='Y' ---and ProcessType='Full' --and PreMOC_CycleFrozenDate IS NULL  
   v_CurrentLoginDate VARCHAR2(200);
   v_temp NUMBER(1, 0) := 0;

BEGIN

   SELECT CurrentLoginDate 

     INTO v_CurrentLoginDate
     FROM DimUserInfo 
    WHERE  ( EffectiveFromTimeKey <= v_TimeKey
             AND EffectiveToTimeKey >= v_TimeKey )
             AND UserLoginID = v_ModifiedBy;
   --IF DATEDIFF(DAY,@CurrentLoginDate,GetDate()) <> 0
   --BEGIN
   --	PRINT -12
   --	SET @Result = -12
   --   return -12 --- User Login Date is prior. Data will not be Saved. Please Close the Application.
   --END   
   BEGIN
      SELECT 1 INTO v_temp
        FROM DUAL
       WHERE NOT EXISTS ( SELECT 1 
                          FROM DimUserInfo 
                           WHERE  UserLoginID = v_UserLoginID
                                    AND ( DimUserInfo.EffectiveFromTimeKey <= v_TimeKey
                                    AND DimUserInfo.EffectiveToTimeKey >= v_TimeKey )
                                    AND SuspendedUser = 'Y' );
   EXCEPTION
      WHEN OTHERS THEN
         NULL;
   END;

   IF v_temp = 1 THEN

   BEGIN
      ROLLBACK;
      utils.resetTrancount;
      v_Result := -1 ;
      RETURN -1;

   END;
   ELSE

   BEGIN
      UPDATE UserLoginHistory
         SET LoginSucceeded = 'Y'
       WHERE  UserID = v_UserLoginID
        AND LoginSucceeded = 'W';
      UPDATE DimUserInfo
         SET SuspendedUser = 'N',
             LoginPassword = v_LoginPassword,
             PasswordChanged = 'N',
             Activate = 'Y' --addded by Vivek
             ,
             CurrentLoginDate = SYSDATE,
             DateModified -- Added By Badri 28/08/2012 date changes
              = SYSDATE
       WHERE  UserLoginID = v_UserLoginID
        AND ( EffectiveFromTimeKey <= v_TimeKey
        AND EffectiveToTimeKey >= v_TimeKey );
      v_Result := 1 ;
      RETURN 1;

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVOKEDUSERSUSPENDUPDATE_08112021" TO "ADF_CDR_RBL_STGDB";
