--------------------------------------------------------
--  DDL for Function PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" 
(
  v_UserLoginID IN VARCHAR2,
  v_Result OUT NUMBER
)
RETURN NUMBER
AS
   v_temp NUMBER(1, 0) := 0;
   v_cursor SYS_REFCURSOR;

BEGIN

   BEGIN
      SELECT 1 INTO v_temp
        FROM DUAL
       WHERE 0 < ( SELECT COUNT(*)  
                   FROM ProvisionComputationCSVUpload  );
   EXCEPTION
      WHEN OTHERS THEN
         NULL;
   END;

   IF v_temp = 1 THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT * 
           FROM ProvisionComputationCSVUpload 
          WHERE  UserLoginId = v_UserLoginID ;
         DBMS_SQL.RETURN_RESULT(v_cursor);
      OPEN  v_cursor FOR
         SELECT * 
           FROM IRAC_Success_ACL_UploadCount  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);
      /*
       --------------------------------------------------------------------------------------------------------------------
       		declare @UCICID_CNT INT =(select count(UCIC_Id) from  DPDCSVUpload where UserLoginId = @UserLoginID )
      		declare @CIF_Id_CNT INT =(select count(CIF_Id) from  DPDCSVUpload where UserLoginId = @UserLoginID)
      		declare @ACCOUNT_Id_CNT INT =(select count(ACCOUNT_Id) from  DPDCSVUpload where UserLoginId = @UserLoginID)

      		IF @UCICID_CNT > 0
      		BEGIN

      		  Select       count(*) 
      		  from         CustomerBasicDetail A
      		  inner join   DPDCSVUpload B  
      		  ON           A.UCIF_ID=B.UCIC_Id
      		  where        EffectiveFromTimeKey <= @TIMEKEY 
      		  AND          EffectiveToTimeKey >= @TIMEKEY

      		END

      			IF @CIF_Id_CNT > 0
      		BEGIN

      		  Select       count(*) 
      		  from         CustomerBasicDetail A
      		  inner join   DPDCSVUpload B  
      		  ON           A.CustomerId=B.CIF_Id
      		  where        EffectiveFromTimeKey <= @TIMEKEY 
      		  AND          EffectiveToTimeKey >= @TIMEKEY

      		END


      		  IF @ACCOUNT_Id_CNT > 0
      		BEGIN

      		  Select       count(*) 
      		  from         AdvAcBasicDetail A
      		  inner join   DPDCSVUpload B  
      		  ON           A.CustomerACID=B.ACCOUNT_Id
      		  where        EffectiveFromTimeKey <= @TIMEKEY 
      		  AND          EffectiveToTimeKey >= @TIMEKEY

      		END
      ----------------------------------------------------------------------------------------------------------------------
      */
      v_Result := 1 ;
      RETURN v_Result;

   END;
   ELSE

   BEGIN
      v_Result := 0 ;
      RETURN v_Result;

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."PROVISIONREPORTFRONTEND_PROCESSCOUNT_07082023" TO "ADF_CDR_RBL_STGDB";
