--------------------------------------------------------
--  DDL for Function SECURITYCHECKDATAVALIDATION_04122023
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

(
  v_MenuID IN NUMBER DEFAULT ' ' ,
  v_Parameter IN VARCHAR2 DEFAULT ' ' ,
  v_Result OUT NUMBER/* DEFAULT 0*/
)
RETURN NUMBER
AS
   v_temp NUMBER(1, 0) := 0;

BEGIN

   DBMS_OUTPUT.PUT_LINE(v_Parameter);
   --Drop Table #final
   --;with T( Cols) as
   --(
   --  select @Parameter
   --),
   ----first split all comma separated into different rows
   --CTE2 AS 
   --(
   --    SELECT 
   --    CAST(N'<H><r>' + replace(Replace(Vals.a.value('.', 'NVARCHAR(50)'),
   --        ' ','|'), '|', '</r><r>') + '</r></H>' as XML) Cols
   --    FROM
   --    (
   --    SELECT *,CAST (N'<H><r>' + Replace(cols,',','</r><r>') + 
   --        '</r></H>' AS XML) AS [vals]
   --    FROM T) d
   --    CROSS APPLY d.[vals].nodes('/H/r') Vals(a)
   --)
   ----IF EXISTS(select * from #final)
   ----Drop Table #final;
   --drop table if exists #final
   ---- split all ' ' demilited values now
   --SELECT distinct  Vals.a.value('(/H/r)[1]', 'VARCHAR(100)') AS ColumnName,
   --Vals.a.value('(/H/r)[2]', 'VARCHAR(100)') AS ColumnValue
   --into #final
   --FROM
   --(
   --SELECT *
   --FROM CTE2) d
   --CROSS APPLY d.[cols].nodes('/H/r') Vals(a)
   DELETE FROM tt_cte_string_split_2;
   UTILS.IDENTITY_RESET('tt_cte_string_split_2');

   INSERT INTO tt_cte_string_split_2 ( 
   	SELECT INSTR(VALUE, '|') CHRIDX  ,
           VALUE ,
           UTILS.CONVERT_TO_VARCHAR2(' ',100) CtrlName  ,
           UTILS.CONVERT_TO_VARCHAR2(' ',500) CtrlValue  
   	  FROM ( SELECT VALUE 
             FROM TABLE(STRING_SPLIT(v_Parameter, '}'))  ) A );
   UPDATE tt_cte_string_split_2
      SET CtrlName = SUBSTR(VALUE, 0, CHRIDX - 1);
   UPDATE tt_cte_string_split_2
      SET CtrlValue = SUBSTR(VALUE, -LENGTH(VALUE) - CHRIDX, LENGTH(VALUE) - CHRIDX);
   BEGIN
      SELECT 1 INTO v_temp
        FROM DUAL
       WHERE ( SELECT COUNT(1)  
               FROM MetaScreenFieldDetail A
                      JOIN tt_cte_string_split_2 B   ON A.CtrlName = B.CtrlName
                WHERE  MenuID = v_MenuID
                         AND IsMandatory = 'Y'
                         AND ( B.CtrlValue = 'NULL'
                         OR b.CtrlValue = ' ' ) ) > 0;
   EXCEPTION
      WHEN OTHERS THEN
         NULL;
   END;

   IF v_temp = 1 THEN

   BEGIN
      v_Result := -1 ;
      RETURN v_Result;

   END;

   --PRINT -1
   ELSE

   BEGIN
      v_Result := 1 ;
      RETURN v_Result;--PRINT 1
      --CASE WHEN 
      --THEN 
      --RETURN -1 
      --ELSE
      --END

   END;
   END IF;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITYCHECKDATAVALIDATION_04122023" TO "ADF_CDR_RBL_STGDB";
