--------------------------------------------------------
--  DDL for Function SP_RENAMEDIAGRAM
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" 
(
  v_diagramname IN VARCHAR2,
  iv_owner_id IN NUMBER DEFAULT NULL ,
  v_new_diagramname IN VARCHAR2
)
RETURN NUMBER
AUTHID DEFINER
AS
   v_owner_id NUMBER(10,0) := iv_owner_id;
   v_theId NUMBER(10,0);
   v_IsDbo NUMBER(10,0);
   v_UIDFound NUMBER(10,0);
   v_DiagId NUMBER(10,0);
   v_DiagIdTarg NUMBER(10,0);
   v_u_name VARCHAR2(128);

BEGIN

   IF ( ( v_diagramname IS NULL )
     OR ( v_new_diagramname IS NULL ) ) THEN

   BEGIN
      utils.raiserror( 0, 'Invalid value' );
      RETURN -1;

   END;
   END IF;
   /*TODO:SQLDEV*/ EXECUTE AS CALLER /*END:SQLDEV*/
   v_theId := DATABASE_PRINCIPAL_ID() ;
   v_IsDbo := /*TODO:SQLDEV*/ IS_MEMBER(u'db_owner') /*END:SQLDEV*/ ;
   IF ( v_owner_id IS NULL ) THEN
    v_owner_id := v_theId ;
   END IF;
   /*TODO:SQLDEV*/ REVERT /*END:SQLDEV*/
   v_u_name := USER ;
   SELECT diagram_id ,
          principal_id 

     INTO v_DiagId,
          v_UIDFound
     FROM RBL_MISDB_PROD.sysdiagrams 
    WHERE  principal_id = v_owner_id
             AND NAME = v_diagramname;
   IF ( v_DiagId IS NULL
     OR ( v_IsDbo = 0
     AND v_UIDFound <> v_theId ) ) THEN

   BEGIN
      utils.raiserror( 0, 'Diagram does not exist or you do not have permission.' );
      RETURN -3;

   END;
   END IF;
   -- if((@u_name is not null) and (@new_diagramname = @diagramname))	-- nothing will change
   --	return 0;
   IF ( v_u_name IS NULL ) THEN
    SELECT diagram_id 

     INTO v_DiagIdTarg
     FROM RBL_MISDB_PROD.sysdiagrams 
    WHERE  principal_id = v_theId
             AND NAME = v_new_diagramname;
   ELSE
      SELECT diagram_id 

        INTO v_DiagIdTarg
        FROM RBL_MISDB_PROD.sysdiagrams 
       WHERE  principal_id = v_owner_id
                AND NAME = v_new_diagramname;
   END IF;
   IF ( ( v_DiagIdTarg IS NOT NULL )
     AND v_DiagId <> v_DiagIdTarg ) THEN

   BEGIN
      utils.raiserror( 0, 'The name is already used.' );
      RETURN -2;

   END;
   END IF;
   IF ( v_u_name IS NULL ) THEN
    UPDATE RBL_MISDB_PROD.sysdiagrams
      SET name = v_new_diagramname,
          principal_id = v_theId
    WHERE  diagram_id = v_DiagId;
   ELSE
      UPDATE RBL_MISDB_PROD.sysdiagrams
         SET name = v_new_diagramname
       WHERE  diagram_id = v_DiagId;
   END IF;
   RETURN 0;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SP_RENAMEDIAGRAM" TO "ADF_CDR_RBL_STGDB";
