--------------------------------------------------------
--  DDL for Function SPLIT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "RBL_MISDB_PROD"."SPLIT" 
(
  iv_String IN NVARCHAR2,
  v_Delimiter IN CHAR
)
RETURN RBL_MISDB_PROD.Split_pkg.tt_v_Results_4_type PIPELINED
AS
   v_String NVARCHAR2(2000) := iv_String;
   v_INDEX NUMBER(10,0);
   v_SLICE NVARCHAR2(2000);
   v_temp SYS_REFCURSOR;
   v_temp_1 TT_V_RESULTS_4%ROWTYPE;
   v_temp_2 SYS_REFCURSOR;
   v_temp_3 TT_V_RESULTS_4%ROWTYPE;

BEGIN
   -- HAVE TO SET TO 1 SO IT DOESNT EQUAL Z
   --     ERO FIRST TIME IN LOOP
   v_INDEX := 1 ;
   -- following line added 10/06/04 as null
   --      values cause issues
   IF v_String IS NULL THEN
    OPEN v_tempv_temp_2 FOR
      SELECT * 
        FROM tt_v_Results_4;

   LOOP
      FETCH v_tempv_temp_2 INTO v_temp_1v_temp_3;
      EXIT WHEN v_tempv_temp_2%NOTFOUND;
      PIPE ROW ( v_temp_1v_temp_3 );
   END LOOP;
   END IF;
   WHILE v_INDEX != 0 
   LOOP 

      BEGIN
         -- GET THE INDEX OF THE FIRST OCCURENCE OF THE SPLIT CHARACTER
         v_INDEX := INSTR(v_STRING, v_Delimiter) ;
         -- NOW PUSH EVERYTHING TO THE LEFT OF IT INTO THE SLICE VARIABLE
         IF v_INDEX != 0 THEN
          v_SLICE := SUBSTR(v_STRING, 0, v_INDEX - 1) ;
         ELSE
            v_SLICE := v_STRING ;
         END IF;
         -- PUT THE ITEM INTO THE RESULTS SET
         INSERT INTO tt_v_Results_4
           ( Items )
           VALUES ( v_SLICE );
         -- CHOP THE ITEM REMOVED OFF THE MAIN STRING
         v_STRING := SUBSTR(v_STRING, -LENGTH(v_STRING) - v_INDEX, LENGTH(v_STRING) - v_INDEX) ;
         -- BREAK OUT IF WE ARE DONE
         IF LENGTH(v_STRING) = 0 THEN
          EXIT;
         END IF;

      END;
   END LOOP;
   OPEN v_tempv_temp_2 FOR
      SELECT * 
        FROM tt_v_Results_4;

   LOOP
      FETCH v_tempv_temp_2 INTO ;
      EXIT WHEN v_tempv_temp_2%NOTFOUND;
      PIPE ROW (  );
   END LOOP;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_MISDB_PROD"."SPLIT" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SPLIT" TO "ADF_CDR_RBL_STGDB";
