--------------------------------------------------------
--  DDL for Index ADVFACDLDETAIL_ACCOUNTENTITYID
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURDAT_RBL_MISDB_PROD"."ADVFACDLDETAIL_ACCOUNTENTITYID" ON "CURDAT_RBL_MISDB_PROD"."ADVFACDLDETAIL" ("ACCOUNTENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
