--------------------------------------------------------
--  DDL for Index CUSTOMERBASICDETAILBACKUP_CUSTOMERENTITYID
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAILBACKUP_CUSTOMERENTITYID" ON "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_BACKUP" ("CUSTOMERENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
