--------------------------------------------------------
--  DDL for Index CUSTOMERBASICDETAIL_CUSTOMERENTITYID
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_CUSTOMERENTITYID" ON "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL" ("CUSTOMERENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
