--------------------------------------------------------
--  DDL for Index INVESTMENTFINANCIALDETAIL_ACCOUNTENTITYID
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_ACCOUNTENTITYID" ON "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL" ("INVENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
