--------------------------------------------------------
--  DDL for Table STAGE_TERADATA_INDICES
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_TEMPDB"."STAGE_TERADATA_INDICES" 
   (	"MDID" NUMBER, 
	"DATABASENAME" VARCHAR2(128 CHAR), 
	"TABLENAME" VARCHAR2(128 CHAR), 
	"INDEXNUMBER" NUMBER(10,0), 
	"INDEXTYPE" CHAR(1 CHAR), 
	"UNIQUEFLAG" CHAR(1 CHAR), 
	"INDEXNAME" VARCHAR2(128 CHAR), 
	"COLUMNNAME" VARCHAR2(128 CHAR), 
	"COLUMNPOSITION" NUMBER(10,0), 
	"CREATORNAME" VARCHAR2(128 CHAR), 
	"INDEXMODE" CHAR(1 CHAR)
   ) ON COMMIT PRESERVE ROWS ;
