--------------------------------------------------------
--  DDL for Table STAGE_SS2K5_COLUMNS
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_TEMPDB"."STAGE_SS2K5_COLUMNS" 
   (	"SVRID_FK" NUMBER(38,0), 
	"DBID_GEN_FK" NUMBER(38,0), 
	"ID_GEN_FK" NUMBER(38,0), 
	"COLID_GEN" NUMBER(38,0), 
	"NAME" VARCHAR2(256 CHAR), 
	"RULE_OBJECT_ID" NUMBER(38,0), 
	"COLUMN_ID" NUMBER(38,0), 
	"MAX_LENGTH" NUMBER(5,0), 
	"PRECISION" NUMBER(5,0), 
	"SCALE" NUMBER(5,0), 
	"IS_NULLABLE" NUMBER(5,0), 
	"USER_TYPE_ID" NUMBER(38,0), 
	"SYSTEM_TYPE_ID" NUMBER(5,0), 
	"DEFAULT_OBJECT_ID" NUMBER(38,0), 
	"OBJECT_ID" NUMBER(38,0)
   ) ON COMMIT PRESERVE ROWS ;
