--------------------------------------------------------
--  DDL for Table STAGE_TERADATA_OFFLINE_PROCS
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_TEMPDB"."STAGE_TERADATA_OFFLINE_PROCS" 
   (	"INDEX" NUMBER, 
	"DBNAME" VARCHAR2(256 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ROUTINETYPE" CHAR(9 BYTE), 
	"CREATE_TIME" VARCHAR2(64 BYTE), 
	"REMARKS" VARCHAR2(510 BYTE), 
	"TEXT" CLOB
   ) ON COMMIT PRESERVE ROWS 
 LOB ("TEXT") STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE ) ;
