--------------------------------------------------------
--  DDL for Table TEMPHOSTSYSTEMSTATUS
--------------------------------------------------------

  CREATE TABLE "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" 
   (	"UCIC_CODE" VARCHAR2(50 CHAR), 
	"CUSTOMERID" VARCHAR2(50 CHAR), 
	"CUSTOMERNAME" VARCHAR2(225 CHAR), 
	"ACCOUNTNO" VARCHAR2(30 CHAR), 
	"HOST_SYSTEM_NAME" VARCHAR2(50 CHAR), 
	"OSBALANCE" NUMBER(16,2), 
	"REPORT_DATE" DATE, 
	"ACTSEGMENTCODE" VARCHAR2(10 CHAR), 
	"ACCOUNT_LEVEL_BUSINESS_SEGMENT" VARCHAR2(20 CHAR), 
	"BUSINESS_SEG_DESC" VARCHAR2(100 CHAR), 
	"BASE_ACCOUNT_SCHEME_CODE" VARCHAR2(20 CHAR), 
	"BASE_ACCOUNT_SCHEME_OWNER" NUMBER(10,0), 
	"HOST_SYSTEM_STATUS" VARCHAR2(5 CHAR), 
	"REMARKS" NUMBER(10,0), 
	"CLOSED_DATE" VARCHAR2(200 CHAR), 
	"CR_DR" VARCHAR2(2 CHAR), 
	"MAIN_CLASSIFICATION" VARCHAR2(100 CHAR), 
	"AUTHORISATIONSTATUS" CHAR(2 CHAR), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"CREATEDBY" VARCHAR2(20 CHAR), 
	"DATECREATED" DATE, 
	"MODIFIEDBY" VARCHAR2(20 CHAR), 
	"DATEMODIFIED" DATE, 
	"APPROVEDBY" VARCHAR2(20 CHAR), 
	"DATEAPPROVED" DATE, 
	"D2KTIMESTAMP" RAW(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."UCIC_CODE" IS 'ORIGINAL NAME:UCIC Code';
   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."HOST_SYSTEM_NAME" IS 'ORIGINAL NAME:Host System Name';
   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."REPORT_DATE" IS 'ORIGINAL NAME:Report Date';
   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."ACCOUNT_LEVEL_BUSINESS_SEGMENT" IS 'ORIGINAL NAME:Account Level Business Segment';
   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."BUSINESS_SEG_DESC" IS 'ORIGINAL NAME:Business Seg Desc';
   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."BASE_ACCOUNT_SCHEME_CODE" IS 'ORIGINAL NAME:Base Account Scheme Code';
   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."BASE_ACCOUNT_SCHEME_OWNER" IS 'ORIGINAL NAME:Base Account Scheme Owner';
   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."HOST_SYSTEM_STATUS" IS 'ORIGINAL NAME:Host System Status';
   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."CLOSED_DATE" IS 'ORIGINAL NAME:Closed Date';
   COMMENT ON COLUMN "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS"."CR_DR" IS 'ORIGINAL NAME:Cr/Dr';
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" TO "ADF_CDR_RBL_STGDB";
