--------------------------------------------------------
--  DDL for Table TEMPADVCREDITCARDBALANCEDETAIL_JAN2024
--------------------------------------------------------

  CREATE TABLE "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" 
   (	"ENTITYKEY" NUMBER(19,0), 
	"ACCOUNTENTITYID" NUMBER(10,0), 
	"CREDITCARDENTITYID" NUMBER(10,0), 
	"BALANCE_POS" NUMBER(16,2), 
	"BALANCE_LOAN" NUMBER(16,2), 
	"BALANCE_INT" NUMBER(16,2), 
	"BALANCE_GST" NUMBER(16,2), 
	"BALANCE_FEES" NUMBER(16,2), 
	"REFSYSTEMACID" VARCHAR2(30 CHAR), 
	"AUTHORISATIONSTATUS" NUMBER(10,0), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"CREATEDBY" VARCHAR2(20 CHAR), 
	"DATECREATED" DATE, 
	"MODIFIEDBY" NUMBER(10,0), 
	"DATEMODIFIED" NUMBER(10,0), 
	"APPROVEDBY" NUMBER(10,0), 
	"DATEAPPROVED" NUMBER(10,0), 
	"D2KTIMESTAMP" NUMBER(10,0), 
	"MOCSTATUS" NUMBER(10,0), 
	"MOCDATE" NUMBER(10,0), 
	"ISCHANGED" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_TEMPDB"."TEMPADVCREDITCARDBALANCEDETAIL_JAN2024" TO "ADF_CDR_RBL_STGDB";
