--------------------------------------------------------
--  DDL for Table ACCELERATEDPROVCALC_HIST_25042023
--------------------------------------------------------

  CREATE TABLE "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" 
   (	"DATEAPPROVED" DATE, 
	"UCIFENTITYID" NUMBER(19,0), 
	"CUSTOMERENTITYID" NUMBER(19,0), 
	"ACCOUNTENTITYID" NUMBER(19,0), 
	"ACCEPRODURATION" NUMBER(5,0), 
	"SECURED_UNSECURED" VARCHAR2(15 CHAR), 
	"PROVTYPES" VARCHAR2(10 CHAR), 
	"ADDITIONALPROVACCT" NUMBER(18,2), 
	"ADDITIONALPROVISION" NUMBER(5,2), 
	"CURRENTPROVISIONPER" NUMBER(5,2), 
	"PROVISIONSECURED" NUMBER(5,2), 
	"PROVISIONUNSECURED" NUMBER(5,2), 
	"NPA_QTR_NO" CHAR(2 CHAR), 
	"SEGMENT" VARCHAR2(50 CHAR), 
	"PROVISIONRULE" VARCHAR2(50 CHAR), 
	"LOWERDPD" NUMBER(5,0), 
	"UPPERDPD" NUMBER(5,0), 
	"TIMEKEY" NUMBER(10,0), 
	"ACCLRTDADDLPROV" NUMBER(20,2), 
	"BUCKETCREDITCARD" VARCHAR2(50 CHAR), 
	"BUCKETEXCEPTCC" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ACCELERATEDPROVCALC_HIST_25042023" TO "ADF_CDR_RBL_STGDB";
