--------------------------------------------------------
--  DDL for Table ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW
--------------------------------------------------------

  CREATE TABLE "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" 
   (	"ENTITYKEY" NUMBER(19,0), 
	"ACCOUNTENTITYID" NUMBER(10,0), 
	"ASSETCLASSALT_KEYONINVOCATION" NUMBER(5,0), 
	"PRERESTRUCTUREASSETCLASSALT_KEY" NUMBER(5,0), 
	"PRERESTRUCTURENPA_DATE" VARCHAR2(200 CHAR), 
	"PROVPERONRESTRUCURE" NUMBER(5,2), 
	"RESTRUCTURETYPEALT_KEY" NUMBER(5,0), 
	"COVID_OTR_CATGALT_KEY" NUMBER(5,0), 
	"RESTRUCTUREDT" VARCHAR2(200 CHAR), 
	"SP_EXPIRYDATE" VARCHAR2(200 CHAR), 
	"DPD_ASONRESTRUCTURE" NUMBER(5,0), 
	"RESTRUCTUREFAILUREDATE" VARCHAR2(200 CHAR), 
	"DPD_BREACH_DATE" VARCHAR2(200 CHAR), 
	"ZERODPD_DATE" VARCHAR2(200 CHAR), 
	"SP_EXPIRYEXTENDEDDATE" VARCHAR2(200 CHAR), 
	"CURRENTPOS" NUMBER(20,2), 
	"CURRENTTOS" NUMBER(20,2), 
	"RESTRUCTUREPOS" NUMBER(20,2), 
	"RES_POS_TO_CURRENTPOS_PER" NUMBER(5,2), 
	"CURRENTDPD" NUMBER(5,0), 
	"TOTALDPD" NUMBER(5,0), 
	"VDPD" NUMBER(5,0), 
	"ADDLPROVPER" NUMBER(5,2), 
	"PROVRELEASEPER" NUMBER(5,2), 
	"APPLIEDNORMALPROVPER" NUMBER(5,2), 
	"FINALPROVPER" NUMBER(5,2), 
	"PREDEGPROVPER" NUMBER(5,2), 
	"UPGRADEDATE" VARCHAR2(200 CHAR), 
	"SURVPERIODENDDATE" VARCHAR2(200 CHAR), 
	"DEGDURSP_PERIODPROVPER" NUMBER(5,2), 
	"NONFINDPD" NUMBER(5,0), 
	"INITIALASSETCLASSALT_KEY" NUMBER(5,0), 
	"FINALASSETCLASSALT_KEY" NUMBER(5,0), 
	"RESTRUCTUREPROVISION" NUMBER(18,2), 
	"SECUREDPROVISION" NUMBER(18,2), 
	"UNSECUREDPROVISION" NUMBER(18,2), 
	"FLGDEG" CHAR(1 CHAR), 
	"FLGUPG" CHAR(1 CHAR), 
	"DEGDATE" VARCHAR2(200 CHAR), 
	"RC_PENDING" CHAR(1 CHAR), 
	"FINALNPADT" VARCHAR2(200 CHAR), 
	"RESTRUCTURESTAGE" VARCHAR2(50 CHAR), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"D2KTIMESTAMP" RAW(50), 
	"DEGREASON" VARCHAR2(100 CHAR), 
	"INVESTMENTGRADE" VARCHAR2(50 CHAR), 
	"POS_10PERPAIDDATE" VARCHAR2(200 CHAR), 
	"DPD_MAXNONFIN" NUMBER(5,0), 
	"DPD_MAXFIN" NUMBER(5,0), 
	"FLGMORAT" CHAR(1 CHAR), 
	"PRERESTRUCTURENPA_PROV" NUMBER(5,2), 
	"RESTRUCTUREFACILITYTYPEALT_KEY" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "MAIN_PRO"."ADVACRESTRUCTURECAL_HIST_BACKUP_ALL_NEW" TO "ADF_CDR_RBL_STGDB";
