--------------------------------------------------------
--  DDL for Table GTT_TEMPSMA_CLASS
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "MAIN_PRO"."GTT_TEMPSMA_CLASS" 
   (	"ACCOUNTENTITYID" NUMBER(10,0), 
	"INITIAL_SMA_CLASS" VARCHAR2(5 CHAR), 
	"FINAL_SMA_CLASS" VARCHAR2(5 CHAR), 
	"SMA_DT" VARCHAR2(200 CHAR), 
	"SMA_CHANGE_DATE" DATE, 
	"FLGSMA" CHAR(1 CHAR), 
	"DPD_SMA" NUMBER(10,0), 
	"SMA_REASON" CLOB, 
	"DPD_MAX" NUMBER(10,0), 
	"ISCHANGED" VARCHAR2(3 BYTE)
   ) ON COMMIT DELETE ROWS 
 LOB ("SMA_REASON") STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE ) ;
