--------------------------------------------------------
--  DDL for Table TT_CUSTOMER_MOVEMENT_HISTOR_6
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "MAIN_PRO"."TT_CUSTOMER_MOVEMENT_HISTOR_6" 
   (	"UCIF_ID" VARCHAR2(50 BYTE), 
	"REFCUSTOMERID" VARCHAR2(50 BYTE), 
	"SOURCESYSTEMCUSTOMERID" VARCHAR2(50 BYTE), 
	"CUSTOMERNAME" VARCHAR2(225 BYTE), 
	"SYSASSETCLASSALT_KEY" NUMBER(10,0), 
	"SYSNPA_DT" VARCHAR2(200 BYTE), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"MOVEMENTFROMSTATUS" VARCHAR2(10 BYTE), 
	"MOVEMENTTOSTATUS" VARCHAR2(10 BYTE), 
	"TOTOSCUST" NUMBER(18,2)
   ) ON COMMIT DELETE ROWS ;
