--------------------------------------------------------
--  DDL for Table TT_DPD_35
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "MAIN_PRO"."TT_DPD_35" 
   (	"ACCOUNTENTITYID" NUMBER(10,0), 
	"UCIFENTITYID" NUMBER(10,0), 
	"CUSTOMERENTITYID" NUMBER(10,0), 
	"CUSTOMERACID" VARCHAR2(30 CHAR), 
	"REFCUSTOMERID" VARCHAR2(50 CHAR), 
	"SOURCESYSTEMCUSTOMERID" VARCHAR2(50 CHAR), 
	"UCIF_ID" VARCHAR2(50 CHAR), 
	"INTNOTSERVICEDDT" VARCHAR2(200 CHAR), 
	"LASTCRDATE" VARCHAR2(200 CHAR), 
	"CONTIEXCESSDT" VARCHAR2(200 CHAR), 
	"OVERDUESINCEDT" VARCHAR2(200 CHAR), 
	"REVIEWDUEDT" VARCHAR2(200 CHAR), 
	"STOCKSTDT" VARCHAR2(200 CHAR), 
	"REFPERIODINTSERVICE" NUMBER(5,0), 
	"REFPERIODNOCREDIT" NUMBER(5,0), 
	"REFPERIODOVERDRAWN" NUMBER(5,0), 
	"REFPERIODOVERDUE" NUMBER(5,0), 
	"REFPERIODREVIEW" NUMBER(5,0), 
	"REFPERIODSTKSTATEMENT" NUMBER(5,0), 
	"DPD_INTSERVICE" NUMBER, 
	"DPD_NOCREDIT" NUMBER, 
	"DPD_OVERDRAWN" NUMBER(10,0), 
	"DPD_OVERDUE" NUMBER(10,0), 
	"DPD_RENEWAL" NUMBER, 
	"DPD_STOCKSTMT" NUMBER, 
	"DPD_MAX" NUMBER
   ) ON COMMIT DELETE ROWS ;
