--------------------------------------------------------
--  DDL for Index MD_DERIVATIVES_PERF_IDX4
--------------------------------------------------------

  CREATE INDEX "ACL_RBL_MISDB_PROD"."MD_DERIVATIVES_PERF_IDX4" ON "ACL_RBL_MISDB_PROD"."MD_DERIVATIVES" ("DERIVED_ID", "DERIVED_TYPE", "DERIVED_CONNECTION_ID_FK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 165 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
