--------------------------------------------------------
--  Constraints for Table PACKAGE_AUDIT_16012024
--------------------------------------------------------

  ALTER TABLE "RBL_STGDB"."PACKAGE_AUDIT_16012024" MODIFY ("PACKAGENAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_STGDB"."PACKAGE_AUDIT_16012024" MODIFY ("TABLENAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_STGDB"."PACKAGE_AUDIT_16012024" MODIFY ("EXECUTIONSTATUS" NOT NULL ENABLE);
