--------------------------------------------------------
--  DDL for Procedure REVERSEFEEDCALYPSOSTG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" 
AS

BEGIN

   EXECUTE IMMEDIATE ' TRUNCATE TABLE RBL_STGDB.reversefeed_calypso_STG ';
   INSERT INTO RBL_STGDB.reversefeed_calypso_STG
     ( Date_of_data, source_system_name, branch_code, ucic_id, issuerId, issuuerName, Ref_Txn_Sys_Cust_ID, PAN, ISSUER_CATEGORY_CODE, GrpEntityOfBank, CP_HOLIDAY, CP_EXTERNAL_REF, CP_FINANCIAL, CP_PARENT, CP_COMMENT, CP_STATUS, COUNTERPARTY_SHORTNAME, COUNTERPARTY_FULLNAME, COUNTERPARTY_ROLE1, COUNTERPARTY_COUNTRY, COUNTERPARTY_ROLE2, COUNTERPARTY_ROLE3, COUNTERPARTY_ROLE4, COUNTERPARTY_ROLE5, CIF_ID, ENPA_ASSET_CODE, ENPA_DESCRIPTION, ENPA_ASSET_CODE_DATE, ENPA_D2K_NPA_DATE )
     ( SELECT Date_of_data ,
              source_system_name ,
              branch_code ,
              ucic_id ,
              issuerId ,
              issuuerName ,
              Ref_Txn_Sys_Cust_ID ,
              PAN ,
              ISSUER_CATEGORY_CODE ,
              GrpEntityOfBank ,
              CP_HOLIDAY ,
              CP_EXTERNAL_REF ,
              CP_FINANCIAL ,
              CP_PARENT ,
              CP_COMMENT ,
              CP_STATUS ,
              COUNTERPARTY_SHORTNAME ,
              COUNTERPARTY_FULLNAME ,
              COUNTERPARTY_ROLE1 ,
              COUNTERPARTY_COUNTRY ,
              COUNTERPARTY_ROLE2 ,
              COUNTERPARTY_ROLE3 ,
              COUNTERPARTY_ROLE4 ,
              COUNTERPARTY_ROLE5 ,
              CIF_ID ,
              ENPA_ASSET_CODE ,
              ENPA_DESCRIPTION ,
              ENPA_ASSET_CODE_DATE ,
              ENPA_D2K_NPA_DATE 
       FROM DWH_STG.reversefeed_calypso 
        WHERE  Date_of_data IN ( SELECT MAX(date_of_data)  
                                 FROM DWH_STG.reversefeed_calypso  )
      );

EXCEPTION WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
            WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSEFEEDCALYPSOSTG" TO "ADF_CDR_RBL_STGDB";
