--------------------------------------------------------
--  DDL for Table ADVACRELATIONS
--------------------------------------------------------

  CREATE TABLE "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" 
   (	"ENTITYKEY" NUMBER(19,0), 
	"BRANCHCODE" VARCHAR2(10 CHAR), 
	"RELATIONENTITYID" NUMBER(10,0), 
	"CUSTOMERENTITYID" NUMBER(10,0), 
	"ACCOUNTENTITYID" NUMBER(10,0), 
	"RELATIONTYPEALT_KEY" NUMBER(5,0), 
	"RELATIONSRNO" NUMBER(5,0), 
	"RELATIONSHIPAUTHORITYCODEALT_KEY" NUMBER(5,0), 
	"INWARDNO" NUMBER(10,0), 
	"FACILITYNO" VARCHAR2(10 CHAR), 
	"GUARANTEEVALUE" NUMBER(16,2), 
	"REFCUSTOMERID" VARCHAR2(20 CHAR), 
	"REFSYSTEMACID" VARCHAR2(30 CHAR), 
	"AUTHORISATIONSTATUS" VARCHAR2(2 CHAR), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"CREATEDBY" VARCHAR2(50 CHAR), 
	"DATECREATED" DATE, 
	"MODIFIEDBY" VARCHAR2(20 CHAR), 
	"DATEMODIFIED" DATE, 
	"APPROVEDBY" VARCHAR2(20 CHAR), 
	"DATEAPPROVED" DATE, 
	"D2KTIMESTAMP" DATE, 
	"STATUSACTIONTAKEN" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "MAIN_PRO";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_STGDB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "CURDAT_RBL_MISDB_PROD"."ADVACRELATIONS" TO "ADF_CDR_RBL_STGDB";
