--------------------------------------------------------
--  DDL for Table ACCOUNT_ALL_SOURCE_SYSTEM
--------------------------------------------------------

  CREATE TABLE "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" 
   (	"DATEOFDATA" VARCHAR2(200 CHAR), 
	"SOURCESYSTEM" VARCHAR2(30 CHAR), 
	"BRANCHCODE" VARCHAR2(10 CHAR), 
	"UCIC_ID" VARCHAR2(20 CHAR), 
	"CUSTOMERID" VARCHAR2(30 CHAR), 
	"CUSTOMERACID" VARCHAR2(30 CHAR), 
	"ACOPENDT" VARCHAR2(200 CHAR), 
	"SCHEMETYPE" VARCHAR2(30 CHAR), 
	"SCHEME_PRODUCTCODE" VARCHAR2(30 CHAR), 
	"ACSEGMENTCODE" VARCHAR2(30 CHAR), 
	"FACILITYTYPE" VARCHAR2(10 CHAR), 
	"GLCODE" VARCHAR2(30 CHAR), 
	"SECTOR" VARCHAR2(50 CHAR), 
	"PURPOSEOFADVANCE" VARCHAR2(100 CHAR), 
	"INDUSTRYCODE" VARCHAR2(10 CHAR), 
	"FIRSTDTOFDISB" VARCHAR2(200 CHAR), 
	"INTTRATE" NUMBER(4,2), 
	"BANKINGARRANGEMENT" VARCHAR2(50 CHAR), 
	"CURRENCYCODE" VARCHAR2(10 CHAR), 
	"UNHEDGEDFCYAMOUNT" NUMBER(16,2), 
	"BALANCEOUTSTANDINGINR" NUMBER(16,2), 
	"BALANCEINACTUALACCURRENCY" NUMBER(16,2), 
	"ADVANCERECOVERYAMOUNT" NUMBER(16,2), 
	"CURQTRCREDIT" NUMBER(16,2), 
	"CURQTRINT" NUMBER(16,2), 
	"CURRENTLIMIT" NUMBER(16,2), 
	"CURRENTLIMITDATE" VARCHAR2(200 CHAR), 
	"DRAWINGPOWER" NUMBER(16,2), 
	"ADHOCAMT" NUMBER(16,2), 
	"ADHOCDATE" VARCHAR2(200 CHAR), 
	"ADHOCEXPIRYDATE" VARCHAR2(200 CHAR), 
	"CONTIEXCESSDATE" VARCHAR2(200 CHAR), 
	"DEBITSINCEDATE" VARCHAR2(200 CHAR), 
	"DFVAMT" NUMBER(16,2), 
	"GOVTGTYAMT" NUMBER(16,2), 
	"INTNOTSERVICEDDATE" VARCHAR2(200 CHAR), 
	"LASTCREDITDATE" VARCHAR2(200 CHAR), 
	"POSBALANCE" NUMBER(16,2), 
	"PRINCIPALOVERDUEAMT" NUMBER(16,2), 
	"PRINCIPALOVERDUESINCEDT" VARCHAR2(200 CHAR), 
	"INTERESTOVERDUEAMT" NUMBER(16,2), 
	"INTERESTOVERDUESINCEDT" VARCHAR2(200 CHAR), 
	"OTHCHARGESOVERDUEAMT" NUMBER(16,2), 
	"OTHCHANGESOVERDUESINCEDT" VARCHAR2(200 CHAR), 
	"REVIEW_RENEWDUEDT" VARCHAR2(200 CHAR), 
	"LIMITEXPIRYDATE" VARCHAR2(200 CHAR), 
	"STOCKSTATEMENTDT" VARCHAR2(200 CHAR), 
	"UNAPPLIEDINTERESTAMT" NUMBER(16,2), 
	"TWODATE" VARCHAR2(200 CHAR), 
	"TWOAMOUNT" NUMBER(16,2), 
	"ASSETCLASSNORM" VARCHAR2(10 CHAR), 
	"ACCATEGORY" NUMBER(3,0), 
	"SECUREDSTATUS" VARCHAR2(20 CHAR), 
	"ASSETCLASSCODE" VARCHAR2(15 CHAR), 
	"NPADATE" VARCHAR2(200 CHAR), 
	"DBT_LOSDATE" VARCHAR2(200 CHAR), 
	"STDPROVISIONCATEGORY" VARCHAR2(20 CHAR), 
	"FRAUDCOMMITTED" VARCHAR2(20 CHAR), 
	"FRAUDDATE" VARCHAR2(200 CHAR), 
	"ISIBPCEXPOSURE" VARCHAR2(20 CHAR), 
	"ISSECURTISEDEXPOSURE" VARCHAR2(20 CHAR), 
	"ACRMNAME_ID" VARCHAR2(50 CHAR), 
	"ACTLNAME_ID" VARCHAR2(50 CHAR), 
	"PUIMARKED" VARCHAR2(20 CHAR), 
	"RFAMARKED" VARCHAR2(20 CHAR), 
	"ISNONCOPERATIVE" VARCHAR2(20 CHAR), 
	"CURRQTRSECURITYVALUE" NUMBER(16,0), 
	"PRVQTRSECURITYVALUE" NUMBER(16,0), 
	"CORPORATEUCICID" VARCHAR2(20 CHAR), 
	"CORPORATECUSTOMERID" VARCHAR2(20 CHAR), 
	"LIABILITY" VARCHAR2(20 CHAR), 
	"CD" NUMBER(10,0), 
	"BUCKET" VARCHAR2(20 CHAR), 
	"ACCOUNTSTATUS" VARCHAR2(20 CHAR), 
	"ACCOUNTBLKCODE1" VARCHAR2(20 CHAR), 
	"ACCOUNTBLKCODE2" VARCHAR2(20 CHAR), 
	"CHARGEOFFY_N" CHAR(1 CHAR), 
	"CHARGEOFFTYPE" VARCHAR2(20 CHAR), 
	"CHARGEOFFAMOUNT" NUMBER(16,2), 
	"CHARGEOFFDATE" VARCHAR2(200 CHAR), 
	"PRINCIPALOS" NUMBER(16,2), 
	"INTERESTOS" NUMBER(16,2), 
	"OTHERCHARGESOS" NUMBER(16,2), 
	"ST_GSTTAXOS" NUMBER(16,2), 
	"INTEREST_DUE" NUMBER(18,6), 
	"OTHER_DUES" NUMBER(18,6), 
	"PENAL_DUE" NUMBER(18,6), 
	"INT_RECEIVABLE" NUMBER(18,6), 
	"PENAL_INT_RECEIVABLE" NUMBER(18,6), 
	"DPD" NUMBER(10,0), 
	"ACCURED_INTEREST" NUMBER(16,2), 
	"SETTLEMENT_FLAG" VARCHAR2(1 CHAR), 
	"SETTLEMENT_DATE" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."ACCOUNT_ALL_SOURCE_SYSTEM" TO "ADF_CDR_RBL_STGDB";
