--------------------------------------------------------
--  DDL for Table CALYPSO_INVESTMENTFINANCIALDETA_23062021
--------------------------------------------------------

  CREATE TABLE "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" 
   (	"DATE_OF_DATA" NVARCHAR2(255), 
	"SOURCE_SYSTEM_NAME" NVARCHAR2(255), 
	"ISIN" NVARCHAR2(255), 
	"ISSUER_ID" NVARCHAR2(255), 
	"INV_ID" NVARCHAR2(255), 
	"HOLDING_NATURE" NVARCHAR2(255), 
	"CURRENCYALT_KEY" NVARCHAR2(255), 
	"CURRENCY_CONV_RATE" NVARCHAR2(255), 
	"BOOK_TYPE" NVARCHAR2(255), 
	"BOOKVALUE" NVARCHAR2(255), 
	"BOOKVALUEINR" NVARCHAR2(255), 
	"MTMVALUE" NVARCHAR2(255), 
	"MTMVALUEINR" NVARCHAR2(255), 
	"ENCUMBEREDMTM" NVARCHAR2(255), 
	"ASSETCLASS_ALTKEY" NVARCHAR2(255), 
	"NPIDT" NVARCHAR2(255), 
	"DBTDT" NVARCHAR2(255), 
	"LATEST_BS_DATE" NVARCHAR2(255), 
	"INTEREST_DIVIDEND_OVERDUE_DATE" NVARCHAR2(255), 
	"INTEREST_DIVIDEND_OVERDUE_AMOUNT" NVARCHAR2(255), 
	"PARTIAL_REDUMPTION_DUE_DATE" NVARCHAR2(255), 
	"PARTIAL_REDUMPTION_PROCEED_SETTLED_Y_N" NVARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021"."DATE_OF_DATA" IS 'ORIGINAL NAME:Date of Data';
   COMMENT ON COLUMN "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021"."LATEST_BS_DATE" IS 'ORIGINAL NAME:Latest BS Date';
   COMMENT ON COLUMN "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021"."INTEREST_DIVIDEND_OVERDUE_DATE" IS 'ORIGINAL NAME:Interest / Dividend Overdue Date';
   COMMENT ON COLUMN "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021"."INTEREST_DIVIDEND_OVERDUE_AMOUNT" IS 'ORIGINAL NAME:Interest / Dividend Overdue Amount';
   COMMENT ON COLUMN "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021"."PARTIAL_REDUMPTION_DUE_DATE" IS 'ORIGINAL NAME:Partial Redumption Due Date';
   COMMENT ON COLUMN "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021"."PARTIAL_REDUMPTION_PROCEED_SETTLED_Y_N" IS 'ORIGINAL NAME:Partial Redumption Proceed Settled Y / N';
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."CALYPSO_INVESTMENTFINANCIALDETA_23062021" TO "ADF_CDR_RBL_STGDB";
