--------------------------------------------------------
--  DDL for Table PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024
--------------------------------------------------------

  CREATE TABLE "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" 
   (	"SCHM_CODE" VARCHAR2(5 CHAR), 
	"DEL_FLG" VARCHAR2(1 CHAR), 
	"SCHM_DESC" VARCHAR2(100 CHAR), 
	"SYST_GEN_ACCT_NUM_FLG" VARCHAR2(1 CHAR), 
	"ACCT_PREFIX" VARCHAR2(2 CHAR), 
	"NEXT_ACCT_NUM_PREFIX" VARCHAR2(5 CHAR), 
	"ACCT_OPN_FORM_NAME" VARCHAR2(8 CHAR), 
	"ACCT_CLS_FORM_NAME" VARCHAR2(8 CHAR), 
	"INT_PAID_BACID" VARCHAR2(16 CHAR), 
	"INT_COLL_BACID" VARCHAR2(16 CHAR), 
	"SERV_CHRG_BACID" VARCHAR2(16 CHAR), 
	"TURNOVER_FREQ_TYPE" VARCHAR2(1 CHAR), 
	"TURNOVER_FREQ_WEEK_NUM" VARCHAR2(1 CHAR), 
	"TURNOVER_FREQ_WEEK_DAY" NUMBER(3,0), 
	"TURNOVER_FREQ_START_DD" NUMBER(3,0), 
	"TURNOVER_HLDY_STAT" VARCHAR2(1 CHAR), 
	"TURNOVER_RCRE_DATE" VARCHAR2(200 CHAR), 
	"GL_SUB_HEAD_CODE" VARCHAR2(5 CHAR), 
	"TRAN_RPT_CODE_FLG" VARCHAR2(1 CHAR), 
	"TRAN_REF_NUM_FLG" VARCHAR2(1 CHAR), 
	"CHQ_ALWD_FLG" VARCHAR2(1 CHAR), 
	"ACCT_TURNOVER_DET_FLG" VARCHAR2(1 CHAR), 
	"SCHM_SUPR_USER_ID" VARCHAR2(15 CHAR), 
	"TOT_MOD_TIMES" NUMBER(10,0), 
	"SERV_CHRG_COLL_FLG" VARCHAR2(1 CHAR), 
	"BACK_DATE_TRAN_EXCP_CODE" VARCHAR2(3 CHAR), 
	"VAL_DATE_TRAN_EXCP_CODE" VARCHAR2(3 CHAR), 
	"INVALID_INSTRMNT_EXCP_CODE" VARCHAR2(3 CHAR), 
	"STALE_INSTRMNT_EXCP_CODE" VARCHAR2(3 CHAR), 
	"ACCT_FREZ_EXCP_CODE" VARCHAR2(3 CHAR), 
	"ACCT_IN_DR_BAL_EXCP_CODE" VARCHAR2(3 CHAR), 
	"ACCT_IN_CR_BAL_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CHQ_STOP_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CHQ_CAUTN_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CHQ_NOT_ISSU_EXCP_CODE" VARCHAR2(3 CHAR), 
	"INVALID_RPT_CODE_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CLG_TRAN_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CASH_TRAN_EXCP_CODE" VARCHAR2(3 CHAR), 
	"XFER_TRAN_EXCP_CODE" VARCHAR2(3 CHAR), 
	"EMP_OWN_ACCT_EXCP_CODE" VARCHAR2(3 CHAR), 
	"OVERRIDE_DEF_EXCP_CODE" VARCHAR2(3 CHAR), 
	"INTROD_NOT_CUST_EXCP_CODE" VARCHAR2(3 CHAR), 
	"INTROD_NEW_CUST_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CHQ_NOT_ALWD_EXCP_CODE" VARCHAR2(3 CHAR), 
	"SI_PRE_FIX_CHRG_EXCP_CODE" VARCHAR2(3 CHAR), 
	"DR_AGAINST_CC_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CLS_PEND_INT_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CLS_PEND_SI_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CLS_PEND_CC_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CLS_PEND_CHQ_EXCP_CODE" VARCHAR2(3 CHAR), 
	"ACCT_OPN_MATRIX_EXCP_CODE" VARCHAR2(3 CHAR), 
	"MEMO_PAD_EXISTS_EXCP_CODE" VARCHAR2(3 CHAR), 
	"SANCT_LIM_EXP_EXCP_CODE" VARCHAR2(3 CHAR), 
	"SANCT_EXCEED_LIM_EXCP_CODE" VARCHAR2(3 CHAR), 
	"LIAB_EXCEED_GROUP_LIM_EXCP" VARCHAR2(3 CHAR), 
	"ACCT_MAINT_FORM_NAME" VARCHAR2(8 CHAR), 
	"OFTI_SCHM_RTN_NAME" VARCHAR2(19 CHAR), 
	"MINOR_CHQ_ISSU_EXCP_CODE" VARCHAR2(3 CHAR), 
	"NEW_ACCT_DURATION" NUMBER(5,0), 
	"DORM_ACCT_CRITERIA" NUMBER(5,0), 
	"MIN_POSTING_WORKCLASS" VARCHAR2(3 CHAR), 
	"SCHM_TYPE" VARCHAR2(3 CHAR), 
	"INT_PAID_FLG" VARCHAR2(1 CHAR), 
	"INT_COLL_FLG" VARCHAR2(1 CHAR), 
	"STAFF_SCHM_FLG" VARCHAR2(1 CHAR), 
	"NRE_SCHM_FLG" VARCHAR2(1 CHAR), 
	"MERGE_INT_PTRAN_FLG" VARCHAR2(1 CHAR), 
	"LCHG_USER_ID" VARCHAR2(15 CHAR), 
	"RCRE_USER_ID" VARCHAR2(15 CHAR), 
	"LCHG_TIME" VARCHAR2(200 CHAR), 
	"RCRE_TIME" VARCHAR2(200 CHAR), 
	"MICR_CHQ_CHRG_BACID" VARCHAR2(16 CHAR), 
	"INSUFF_AVAIL_BAL_EXCP_CODE" VARCHAR2(3 CHAR), 
	"FD_CR_BACID" VARCHAR2(16 CHAR), 
	"FD_DR_BACID" VARCHAR2(16 CHAR), 
	"FX_TRAN_FLG" VARCHAR2(1 CHAR), 
	"STP_CR_DR_IND" VARCHAR2(1 CHAR), 
	"FCNR_FLG" VARCHAR2(1 CHAR), 
	"INT_PANDL_BACID" VARCHAR2(16 CHAR), 
	"PARKING_BACID" VARCHAR2(16 CHAR), 
	"INT_PAID_COLL_CRNCY_FLG" VARCHAR2(1 CHAR), 
	"CASH_WD_WO_CHQ_EXCP_CODE" VARCHAR2(3 CHAR), 
	"ACCT_NAME_CHANGED_EXCP_CODE" VARCHAR2(3 CHAR), 
	"XFER_IN_INT_DETAILS_FLG" VARCHAR2(1 CHAR), 
	"ACCT_REFERENCE_EXCP_CODE" VARCHAR2(3 CHAR), 
	"DR_OPER_ACCT_IF_NO_BAL_FLG" VARCHAR2(1 CHAR), 
	"INT_DR_CUST_DIFF_EXCP_CODE" VARCHAR2(3 CHAR), 
	"INT_CR_CUST_DIFF_EXCP_CODE" VARCHAR2(3 CHAR), 
	"ISO_USER_TOD_GRNT_EXCP_CODE" VARCHAR2(3 CHAR), 
	"ISO_AUTO_TOD_GRNT_EXCP_CODE" VARCHAR2(3 CHAR), 
	"INTER_SOL_CLOSURE_ALWD_FLG" VARCHAR2(1 CHAR), 
	"LEVY_TAX_PCNT_1" NUMBER(25,6), 
	"LEVY_TAX_PCNT_2" NUMBER(25,6), 
	"LEVY_TAX_PCNT_3" NUMBER(25,6), 
	"LEVY_TAX_DESC_1" VARCHAR2(30 CHAR), 
	"LEVY_TAX_DESC_2" VARCHAR2(30 CHAR), 
	"LEVY_TAX_DESC_3" VARCHAR2(30 CHAR), 
	"LEVY_TAX_BACID_1" VARCHAR2(16 CHAR), 
	"LEVY_TAX_BACID_2" VARCHAR2(16 CHAR), 
	"LEVY_TAX_BACID_3" VARCHAR2(16 CHAR), 
	"LEVY_TAX_MERGE_PTRAN_FLG" VARCHAR2(1 CHAR), 
	"PEG_INT_FOR_AC_FLG" VARCHAR2(1 CHAR), 
	"MOD_OF_PEG_INT_ALLOWED_FLG" VARCHAR2(1 CHAR), 
	"PEG_REVIEW_PREF_FROM_CUST" VARCHAR2(1 CHAR), 
	"DFLT_INT_PAR_CHNG_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CLS_PEND_REVERSAL_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CHQ_ISSUED_ACK_EXCP_CODE" VARCHAR2(3 CHAR), 
	"ACCT_CLOSURE_CHRG_DAYS" NUMBER(5,0), 
	"ACCT_CLOSURE_CHRG_MNTHS" NUMBER(5,0), 
	"ACCT_MAINT_PERIOD" VARCHAR2(1 CHAR), 
	"MIN_COMMIT_CHRG_UTIL_PCNT" NUMBER(25,6), 
	"COMMIT_CALC_METHOD" VARCHAR2(1 CHAR), 
	"INACTIVE_ACCT_CHRG_DAYS" NUMBER(5,0), 
	"INACTIVE_ACCT_CHRG_MNTHS" NUMBER(5,0), 
	"DORMANT_ACCT_CHRG_DAYS" NUMBER(5,0), 
	"DORMANT_ACCT_CHRG_MNTHS" NUMBER(5,0), 
	"PARTITION_MANDATORY_FLG" VARCHAR2(1 CHAR), 
	"BOOK_TRAN_SCRIPT" VARCHAR2(30 CHAR), 
	"INTCALC_TRAN_SCRIPT" VARCHAR2(30 CHAR), 
	"ADVANCE_INT_BACID" VARCHAR2(16 CHAR), 
	"TDS_PARKING_BACID" VARCHAR2(16 CHAR), 
	"PENAL_PANDL_BACID" VARCHAR2(16 CHAR), 
	"DFLT_CLG_TRAN_CODE" VARCHAR2(3 CHAR), 
	"DFLT_INST_TYPE" VARCHAR2(5 CHAR), 
	"CHQ_UNUSABLE_EXCP_CODE" VARCHAR2(3 CHAR), 
	"INT_PANDL_BACID_CR" VARCHAR2(16 CHAR), 
	"INT_PANDL_BACID_DR" VARCHAR2(16 CHAR), 
	"BEL_MIN_BAL_EXCP_CODE" VARCHAR2(3 CHAR), 
	"PEN_CHRG_NCALC_EXCP_CODE" VARCHAR2(3 CHAR), 
	"INT_FREQ_TYPE_CR" VARCHAR2(1 CHAR), 
	"INT_FREQ_WEEK_NUM_CR" VARCHAR2(1 CHAR), 
	"INT_FREQ_WEEK_DAY_CR" NUMBER(3,0), 
	"INT_FREQ_START_DD_CR" NUMBER(3,0), 
	"INT_FREQ_HLDY_STAT_CR" VARCHAR2(1 CHAR), 
	"INT_FREQ_TYPE_DR" VARCHAR2(1 CHAR), 
	"INT_FREQ_WEEK_NUM_DR" VARCHAR2(1 CHAR), 
	"INT_FREQ_WEEK_DAY_DR" NUMBER(3,0), 
	"INT_FREQ_START_DD_DR" NUMBER(3,0), 
	"INT_FREQ_HLDY_STAT_DR" VARCHAR2(1 CHAR), 
	"PD_GL_SUB_HEAD_CODE" VARCHAR2(5 CHAR), 
	"PD_INT_CALC_EXCP_CODE" VARCHAR2(3 CHAR), 
	"PD_DR_TRAN_EXCP_CODE" VARCHAR2(3 CHAR), 
	"LIM_LEVEL_INT_FLG" VARCHAR2(1 CHAR), 
	"EEFC_FLG" VARCHAR2(1 CHAR), 
	"TS_CNT" NUMBER(10,0), 
	"CS_SCHM_MESG1" VARCHAR2(75 CHAR), 
	"CS_SCHM_MESG2" VARCHAR2(75 CHAR), 
	"PS_FREQ_TYPE" VARCHAR2(1 CHAR), 
	"PS_FREQ_WEEK_NUM" VARCHAR2(1 CHAR), 
	"PS_FREQ_WEEK_DAY" NUMBER(3,0), 
	"PS_FREQ_START_DD" NUMBER(3,0), 
	"PS_FREQ_HLDY_STAT" VARCHAR2(1 CHAR), 
	"AUTO_RENEWAL_PERIOD_FLG" VARCHAR2(1 CHAR), 
	"PRODUCT_GROUP" VARCHAR2(5 CHAR), 
	"PRINCIPAL_LOSSLINE_BACID" VARCHAR2(16 CHAR), 
	"RECOVER_LOSSLINE_BACID" VARCHAR2(16 CHAR), 
	"CHRGE_OFF_BACID" VARCHAR2(16 CHAR), 
	"DEALER_CONTR_BACID" VARCHAR2(16 CHAR), 
	"INT_WAIVER_BACID" VARCHAR2(16 CHAR), 
	"DAILY_COMP_INT_FLG" VARCHAR2(1 CHAR), 
	"QIS_INT_FLG" VARCHAR2(1 CHAR), 
	"STOCK_INT_FLG" VARCHAR2(1 CHAR), 
	"UNVERIFIED_SPP_EXCP_CODE" VARCHAR2(3 CHAR), 
	"OVDU_INT_PAID_BACID" VARCHAR2(16 CHAR), 
	"OVDU_INT_PANDL_BACID_CR" VARCHAR2(16 CHAR), 
	"COMP_DATE_FLG" VARCHAR2(1 CHAR), 
	"DISC_RATE_FLG" VARCHAR2(1 CHAR), 
	"START_DATE" VARCHAR2(200 CHAR), 
	"END_DATE" VARCHAR2(200 CHAR), 
	"SET_ID" VARCHAR2(8 CHAR), 
	"CS_SCHM_NATL_MESG1" VARCHAR2(75 CHAR), 
	"CS_SCHM_NATL_MESG2" VARCHAR2(75 CHAR), 
	"STP_DR_INT_RECALC" VARCHAR2(1 CHAR), 
	"STP_CR_INT_RECALC" VARCHAR2(1 CHAR), 
	"FIXEDTERM_MNTHS" NUMBER(5,0), 
	"FIXEDTERM_YEARS" NUMBER(5,0), 
	"REPRICING_PLAN" VARCHAR2(1 CHAR), 
	"REPRICING_FREQ_MNTHS" NUMBER(5,0), 
	"REPRICING_FREQ_DAYS" NUMBER(5,0), 
	"REPRICING_YEAR_IND" VARCHAR2(1 CHAR), 
	"FLOAT_INT_TBL_CODE" VARCHAR2(5 CHAR), 
	"REPRICING_EXCP_CODE" VARCHAR2(3 CHAR), 
	"FLOAT_REPRICING_FREQ_MNTHS" NUMBER(5,0), 
	"FLOAT_REPRICING_FREQ_DAYS" NUMBER(5,0), 
	"SCRIPT_VALUE_DATE_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CUST_MIN_AGE" NUMBER(5,0), 
	"CUST_MAX_AGE" NUMBER(5,0), 
	"AGE_RANGE_EXCP_CODE" VARCHAR2(3 CHAR), 
	"SCHM_SHORT_NAME" VARCHAR2(15 CHAR), 
	"PREF_LANG_CODE" VARCHAR2(10 CHAR), 
	"PREF_LANG_SCHM_DESC" VARCHAR2(100 CHAR), 
	"PREF_LANG_SCHM_SHORT_NAME" VARCHAR2(15 CHAR), 
	"TENOR_IND_FLG" VARCHAR2(1 CHAR), 
	"RULE_CODE" VARCHAR2(5 CHAR), 
	"SECURED_FLG" VARCHAR2(1 CHAR), 
	"LOOKBACK_PERD_FOR_PASTDUE" NUMBER(10,0), 
	"BANK_ID" VARCHAR2(8 CHAR), 
	"NEGATIVE_LIEN_EXCP_CODE" VARCHAR2(3 CHAR), 
	"CHQ_REJECT_EXCP_CODE" VARCHAR2(3 CHAR), 
	"PEN_COLL_FLG" VARCHAR2(1 CHAR), 
	"SYN_AGENT_SCHEME" VARCHAR2(1 CHAR), 
	"PEN_COLL_BACID" VARCHAR2(16 CHAR), 
	"PRODUCT_CONCEPT" VARCHAR2(5 CHAR), 
	"ACCT_LINKED_INVT_ID_EXCP_CODE" VARCHAR2(3 CHAR), 
	"PENAL_INT_COLL_BACID" VARCHAR2(16 CHAR), 
	"PAST_DUE_INT_COLL_BACID" VARCHAR2(16 CHAR), 
	"PAST_DUE_PENAL_INT_COLL_BACID" VARCHAR2(16 CHAR), 
	"SCHM_NATURE" VARCHAR2(1 CHAR), 
	"PS_FREQ_CAL_BASE" VARCHAR2(2 CHAR), 
	"ADDITIONAL_CAL_BASE" VARCHAR2(2 CHAR), 
	"INT_FREQ_CAL_BASE_CR" VARCHAR2(2 CHAR), 
	"INT_FREQ_CAL_BASE_DR" VARCHAR2(2 CHAR), 
	"MUD_POOL_PROD_FLG" VARCHAR2(1 CHAR), 
	"ALT1_SCHM_SHORT_NAME" VARCHAR2(15 CHAR), 
	"ALT1_SCHM_DESC" VARCHAR2(100 CHAR), 
	"PRODUCT_SRL_NUM" VARCHAR2(12 CHAR), 
	"PRODUCT_ID" VARCHAR2(25 CHAR), 
	"ISLAMIC_PRODUCT_TYPE" VARCHAR2(1 CHAR), 
	"PRODUCT_TYPE" VARCHAR2(1 CHAR), 
	"INT_COMPOUNDING_FRQ_CR" VARCHAR2(1 CHAR), 
	"INT_COMPOUNDING_REST_FLG_CR" VARCHAR2(1 CHAR), 
	"DISC_RATE_FLG_CR" VARCHAR2(1 CHAR), 
	"KONFORMNA_FLG" VARCHAR2(1 CHAR), 
	"OVERIDE_DEF_MIN_BAL_PARAM_EXCP" VARCHAR2(3 CHAR), 
	"CHQ_PROV_BY_BANK_FLG" VARCHAR2(1 CHAR), 
	"PRODUCT_CODE" VARCHAR2(5 CHAR), 
	"INT_FREQ_MONTHS_DR" NUMBER(5,0), 
	"INT_FREQ_DAYS_DR" NUMBER(5,0), 
	"NR_SCHM_TYPE" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."PRODUCT_CODE_MASTER_FINACLE_STG_JAN2024" TO "ADF_CDR_RBL_STGDB";
