--------------------------------------------------------
--  DDL for Table REVERSE_FEED_CALYPSO_STG
--------------------------------------------------------

  CREATE TABLE "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" 
   (	"DATE_OF_DATA" VARCHAR2(30 CHAR), 
	"SOURCE_SYSTEM_NAME" VARCHAR2(30 CHAR), 
	"BRANCH_CODE" VARCHAR2(30 CHAR), 
	"UCIC_ID" VARCHAR2(30 CHAR), 
	"ISSUERID" VARCHAR2(30 CHAR), 
	"ISSUUERNAME" VARCHAR2(100 CHAR), 
	"REF_TXN_SYS_CUST_ID" VARCHAR2(25 CHAR), 
	"PAN" VARCHAR2(30 CHAR), 
	"ISSUER_CATEGORY_CODE" VARCHAR2(20 CHAR), 
	"GRPENTITYOFBANK" VARCHAR2(20 CHAR), 
	"CP_HOLIDAY" VARCHAR2(30 CHAR), 
	"CP_EXTERNAL_REF" VARCHAR2(30 CHAR), 
	"CP_FINANCIAL" VARCHAR2(30 CHAR), 
	"CP_PARENT" VARCHAR2(30 CHAR), 
	"CP_COMMENT" VARCHAR2(30 CHAR), 
	"CP_STATUS" VARCHAR2(30 CHAR), 
	"COUNTERPARTY_SHORTNAME" VARCHAR2(30 CHAR), 
	"COUNTERPARTY_FULLNAME" VARCHAR2(30 CHAR), 
	"COUNTERPARTY_ROLE1" VARCHAR2(30 CHAR), 
	"COUNTERPARTY_COUNTRY" VARCHAR2(30 CHAR), 
	"COUNTERPARTY_ROLE2" VARCHAR2(30 CHAR), 
	"COUNTERPARTY_ROLE3" VARCHAR2(30 CHAR), 
	"COUNTERPARTY_ROLE4" VARCHAR2(30 CHAR), 
	"COUNTERPARTY_ROLE5" VARCHAR2(30 CHAR), 
	"CIF_ID" VARCHAR2(30 CHAR), 
	"ENPA_ASSET_CODE" VARCHAR2(30 CHAR), 
	"ENPA_DESCRIPTION" VARCHAR2(30 CHAR), 
	"ENPA_ASSET_CODE_DATE" VARCHAR2(200 CHAR), 
	"ENPA_D2K_NPA_DATE" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_STGDB"."REVERSE_FEED_CALYPSO_STG" TO "ADF_CDR_RBL_STGDB";
