--------------------------------------------------------
--  DDL for Index ACCOUNTCAL_MAIN_ACCOUNTENTITYID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAIN_PRO"."ACCOUNTCAL_MAIN_ACCOUNTENTITYID" ON "MAIN_PRO"."ACCOUNTCAL_MAIN" ("ACCOUNTENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
