--------------------------------------------------------
--  DDL for Index CUSTOMERCAL_MAIN_CUSTOMERENTITYID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAIN_PRO"."CUSTOMERCAL_MAIN_CUSTOMERENTITYID" ON "MAIN_PRO"."CUSTOMERCAL_MAIN" ("CUSTOMERENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
