--------------------------------------------------------
--  DDL for Function GETPOTENTIALNPADT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" 
--===============================================================================================
 -- Created by       : Shivendra Kumar Yadav
 -- Created Date     : 08-08-2013
 -- Description      : To find Potantial NPA Date.
 -- Form/Report Name : 
 --===============================================================================================
 --===============================================================================================
 --===============================  ALTER HISTORY ================================================
 --===============================================================================================
 --       Name             Date                    Reason                       Change
 -- 1.  
 -- 2.  
 -- 3.  
 --===============================================================================================
 /*
  Hard Coded Fields Description: 
                                  Feild Name              Value             Significance
                               1. 
                               2. 
                               3. 

*/
(
  v_TimeKey IN NUMBER
)
RETURN VARCHAR2
AS
   v_PotentialNPADt VARCHAR2(200);
   v_temp NUMBER(1, 0) := 0;

BEGIN
   BEGIN
      SELECT 1 INTO v_temp
        FROM DUAL
       WHERE EXISTS ( SELECT 1 
                      FROM RBL_MISDB_PROD.SysDataMatrix A
                       WHERE  A.TimeKey = A.Qtr_key /* If the prcessing date is qtr end date than potantialnpadate will be next qtr end date */ );
   EXCEPTION
      WHEN OTHERS THEN
         NULL;
   END;

   IF v_temp = 1 THEN
    SELECT DataEffectiveToDate 

     INTO v_PotentialNPADt
     FROM RBL_MISDB_PROD.SysDataMatrix 
    WHERE  TimeKey = ( SELECT MIN(TimeKey)  
                       FROM RBL_MISDB_PROD.SysDataMatrix A
                        WHERE  A.TimeKey = A.Qtr_key
                                 AND A.TimeKey > v_TimeKey );
   ELSE /* If the prcessing date is within qtr date than potantialnpadate will be qtr end date */
      SELECT B.DataEffectiveToDate 

        INTO v_PotentialNPADt
        FROM RBL_MISDB_PROD.SysDataMatrix A
               JOIN RBL_MISDB_PROD.SysDataMatrix B   ON A.Qtr_key = B.TimeKey
       WHERE  A.TimeKey = v_TimeKey;
   END IF;
   RETURN v_PotentialNPADt;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "MAIN_PRO";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "MAIN_PRO";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "RBL_STGDB";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "RBL_STGDB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "RBL_TEMPDB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "ACL_RBL_MISDB_PROD"."GETPOTENTIALNPADT" TO "ADF_CDR_RBL_STGDB";
