--------------------------------------------------------
--  DDL for Sequence TT_SQ_OAOLMASTERUPLOADDATA__4
--------------------------------------------------------

   CREATE SEQUENCE  "RBL_MISDB_PROD"."TT_SQ_OAOLMASTERUPLOADDATA__4"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
