--------------------------------------------------------
--  DDL for Table CO_BORROWER_DATA_UAT_BKUP_04082023
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" 
   (	"SCHEME_TYPE" VARCHAR2(50 CHAR), 
	"SCHEME_CODE" VARCHAR2(50 CHAR), 
	"ACCT_BUSINESS_SEGMENT" VARCHAR2(50 CHAR), 
	"ACCOUNT_NO" CHAR(20 CHAR), 
	"CUSTOMER_CODE" CHAR(20 CHAR), 
	"CUSTOMER_NAME" VARCHAR2(150 CHAR), 
	"CUSTOMER_TYPE" VARCHAR2(50 CHAR), 
	"UCIC" VARCHAR2(50 CHAR), 
	"POS" VARCHAR2(50 CHAR), 
	"CUSTID" VARCHAR2(30 CHAR), 
	"ACCT_CUST_CODE" VARCHAR2(20 CHAR), 
	"COBORR_CUSTID" VARCHAR2(20 CHAR), 
	"ACASSETCLASSALT_KEY" NUMBER(5,0), 
	"ACCT_CUST_CODE_ASSETCLASSALT_KEY" NUMBER(5,0), 
	"COBORR_ACASSETCLASSALT_KEY" NUMBER(5,0), 
	"BALANCE" NUMBER(18,2), 
	"PRINCIPAL_OS" NUMBER(18,2), 
	"TOTALPROV" NUMBER(18,2), 
	"SOURCENAME" VARCHAR2(20 CHAR), 
	"RELATIONALACCOUNTNO" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."CO_BORROWER_DATA_UAT_BKUP_04082023" TO "ADF_CDR_RBL_STGDB";
