--------------------------------------------------------
--  DDL for Table DIMADDRESSCATEGORY
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" 
   (	"ADDRESSCATEGORY_KEY" NUMBER(5,0), 
	"ADDRESSCATEGORYALT_KEY" NUMBER(5,0), 
	"ADDRESSCATEGORYORDERKEY" NUMBER(5,0), 
	"ADDRESSCATEGORYNAME" VARCHAR2(50 CHAR), 
	"ADDRESSCATEGORYSHORTNAME" VARCHAR2(20 CHAR), 
	"ADDRESSCATEGORYSHORTNAMEENUM" VARCHAR2(20 CHAR), 
	"ADDRESSCATEGORYGROUP" VARCHAR2(50 CHAR), 
	"ADDRESSCATEGORYSUBGROUP" VARCHAR2(50 CHAR), 
	"ADDRESSCATEGORYSEGMENT" VARCHAR2(50 CHAR), 
	"ISCOMPULSORY" CHAR(1 CHAR), 
	"ALLOWMULTIPLE" CHAR(1 CHAR), 
	"ADDRESSCATEGORYVALIDCODE" CHAR(1 CHAR), 
	"SRCSYSADDRESSCATEGORYCODE" VARCHAR2(50 CHAR), 
	"SRCSYSADDRESSCATEGORYNAME" VARCHAR2(50 CHAR), 
	"DESTSYSADDRESSCATEGORYCODE" VARCHAR2(10 CHAR), 
	"SUBMITTOCIBIL" CHAR(1 CHAR), 
	"CIBILCODE" VARCHAR2(5 CHAR), 
	"CIBILDESCRIPTION" VARCHAR2(50 CHAR), 
	"AUTHORISATIONSTATUS" VARCHAR2(2 CHAR), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"CREATEDBY" VARCHAR2(20 CHAR), 
	"DATECREATED" DATE, 
	"MODIFIEDBY" VARCHAR2(20 CHAR), 
	"DATEMODIFIED" DATE, 
	"APPROVEDBY" VARCHAR2(20 CHAR), 
	"DATEAPPROVED" VARCHAR2(200 CHAR), 
	"D2KTIMESTAMP" RAW(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."DIMADDRESSCATEGORY" TO "ADF_CDR_RBL_STGDB";
