--------------------------------------------------------
--  DDL for Table GTT_ACCOUNT_POSTMOC_1
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."GTT_ACCOUNT_POSTMOC_1" 
   (	"ACCOUNTENTITYID" NUMBER(10,0), 
	"ACCOUNTID" VARCHAR2(30 CHAR), 
	"BALANCE" NUMBER(16,2), 
	"INTTSERVICED" CHAR(1 CHAR), 
	"FLGFITL" CHAR(1 CHAR), 
	"DFVAMT" NUMBER(16,2), 
	"REPOSSESSION" CHAR(1 CHAR), 
	"REPOSSESSIONDATE" VARCHAR2(200 CHAR), 
	"SARFAESI" CHAR(1 CHAR), 
	"ADDLPROVISION" NUMBER(16,2), 
	"FLGMOC" CHAR(1 CHAR), 
	"UCICID" VARCHAR2(50 CHAR), 
	"AUTHORISATIONSTATUS" VARCHAR2(5 BYTE), 
	"CREATEDBY" VARCHAR2(250 BYTE), 
	"DATECREATED" DATE, 
	"MODIFIEDBY" VARCHAR2(250 BYTE), 
	"DATEMODIFIED" DATE, 
	"APPROVEDBY" VARCHAR2(250 BYTE), 
	"DATEAPPROVED" DATE
   ) ON COMMIT DELETE ROWS ;
