--------------------------------------------------------
--  DDL for Table GTT_DPD
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."GTT_DPD" 
   (	"CUSTOMERACID" VARCHAR2(30 CHAR), 
	"ACCOUNTENTITYID" NUMBER(10,0), 
	"SOURCESYSTEMCUSTOMERID" VARCHAR2(50 CHAR), 
	"INTNOTSERVICEDDT" VARCHAR2(200 CHAR), 
	"PROCESSDATE" CHAR(10 BYTE), 
	"LASTCRDATE" VARCHAR2(200 CHAR), 
	"CONTIEXCESSDT" VARCHAR2(200 CHAR), 
	"OVERDUESINCEDT" VARCHAR2(200 CHAR), 
	"REVIEWDUEDT" VARCHAR2(200 CHAR), 
	"STOCKSTDT" VARCHAR2(200 CHAR), 
	"PRINCOVERDUESINCEDT" VARCHAR2(200 CHAR), 
	"INTOVERDUESINCEDT" VARCHAR2(200 CHAR), 
	"OTHEROVERDUESINCEDT" VARCHAR2(200 CHAR), 
	"REFPERIODINTSERVICE" NUMBER(5,0), 
	"REFPERIODNOCREDIT" NUMBER(5,0), 
	"REFPERIODOVERDRAWN" NUMBER(5,0), 
	"REFPERIODOVERDUE" NUMBER(5,0), 
	"REFPERIODREVIEW" NUMBER(5,0), 
	"REFPERIODSTKSTATEMENT" NUMBER(5,0), 
	"DEGDATE" VARCHAR2(200 CHAR), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"DPD_INTSERVICE" NUMBER(10,0), 
	"DPD_NOCREDIT" NUMBER(10,0), 
	"DPD_OVERDRAWN" NUMBER(10,0), 
	"DPD_OVERDUE" NUMBER(10,0), 
	"DPD_RENEWAL" NUMBER(10,0), 
	"DPD_STOCKSTMT" NUMBER(10,0), 
	"DPD_PRINCOVERDUE" NUMBER(10,0), 
	"DPD_INTOVERDUESINCE" NUMBER(10,0), 
	"DPD_OTHEROVERDUESINCE" NUMBER(10,0), 
	"DPD_MAX" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0)
   ) ON COMMIT DELETE ROWS ;
