--------------------------------------------------------
--  DDL for Table GTT_TMP2
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."GTT_TMP2" 
   (	"ACID" VARCHAR2(30 CHAR), 
	"REFCUSTOMERID" VARCHAR2(30 CHAR), 
	"CUSTOMERNAME" VARCHAR2(100 CHAR), 
	"UCICID" VARCHAR2(30 CHAR), 
	"AUTHORISATIONSTATUS" VARCHAR2(20 BYTE), 
	"MOCMONTHENDDATE" CHAR(10 BYTE), 
	"CUSTOMERENTITYID" NUMBER(10,0), 
	"TABLENAME" CHAR(19 BYTE), 
	"ROWNUMBER" NUMBER
   ) ON COMMIT DELETE ROWS ;
