--------------------------------------------------------
--  DDL for Table GTT_ACCT_NPA_QTR_NO_REPORT
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."GTT_ACCT_NPA_QTR_NO_REPORT" 
   (	"UCIFENTITYID" NUMBER(10,0), 
	"CUSTOMERENTITYID" NUMBER(10,0), 
	"ACCOUNTENTITYID" NUMBER(10,0), 
	"FINALASSETCLASSALT_KEY" NUMBER(10,0), 
	"PROVISIONALT_KEY" NUMBER(5,0), 
	"PROVISIONSECURED" NUMBER(5,2), 
	"PROVISIONUNSECURED" NUMBER(5,2), 
	"SEGMENT" VARCHAR2(20 CHAR), 
	"PROVISIONRULE" VARCHAR2(20 CHAR), 
	"LOWERDPD" NUMBER(10,0), 
	"UPPERDPD" NUMBER(10,0), 
	"NPA_QTR_NO" CHAR(2 BYTE), 
	"ACBUREVISEDSEGMENTCODE" VARCHAR2(20 CHAR), 
	"SECUREDUNSECURED" VARCHAR2(9 BYTE)
   ) ON COMMIT DELETE ROWS ;
