--------------------------------------------------------
--  DDL for Table GTT_TEMP
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."GTT_TEMP" 
   (	"SOURCEALT_KEY" NUMBER(5,0), 
	"SOURCENAME" VARCHAR2(50 CHAR), 
	"ACBUSEGMENTCODE" VARCHAR2(20 CHAR), 
	"ACBUSEGMENTDESCRIPTION" VARCHAR2(100 CHAR), 
	"ACBUREVISEDSEGMENTCODE" VARCHAR2(20 CHAR), 
	"AUTHORISATIONSTATUS" VARCHAR2(20 CHAR), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"CREATEDBY" VARCHAR2(20 CHAR), 
	"DATECREATED" DATE, 
	"MODIFYBY" VARCHAR2(20 CHAR), 
	"DATEMODIFIED" VARCHAR2(200 CHAR), 
	"APPROVEDBY" VARCHAR2(20 CHAR), 
	"DATEAPPROVED" DATE, 
	"ACBUSEGMENTALT_KEY" NUMBER(5,0), 
	"ACBUSEGMENT_KEY" NUMBER(5,0), 
	"CRMODBY" VARCHAR2(20 CHAR), 
	"CRMODDATE" VARCHAR2(200 CHAR), 
	"CRAPPBY" VARCHAR2(20 CHAR), 
	"CRAPPDATE" DATE, 
	"MODAPPBY" VARCHAR2(20 CHAR), 
	"MODAPPDATE" DATE, 
	"CHANGEFIELDS" CHAR(1 BYTE)
   ) ON COMMIT DELETE ROWS ;
