--------------------------------------------------------
--  DDL for Table INVESTMENT_DATA
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."INVESTMENT_DATA" 
   (	"PROCESS_DATE" NVARCHAR2(30), 
	"BRANCHCODE" VARCHAR2(10 CHAR), 
	"ISSUERID" VARCHAR2(30 CHAR), 
	"ISSUERNAME" VARCHAR2(100 CHAR), 
	"REF_TXN_SYS_CUST_ID" VARCHAR2(100 CHAR), 
	"ISSUER_CATEGORY_CODE" VARCHAR2(50 CHAR), 
	"UCIFID" VARCHAR2(30 CHAR), 
	"PANNO" VARCHAR2(10 CHAR), 
	"INVID" VARCHAR2(30 CHAR), 
	"ISIN" VARCHAR2(12 CHAR), 
	"INSTRUMENTTYPENAME" VARCHAR2(100 CHAR), 
	"INSTRNAME" VARCHAR2(100 CHAR), 
	"INVESTMENTNATURE" VARCHAR2(25 CHAR), 
	"EXPOSURETYPE" VARCHAR2(25 CHAR), 
	"MATURITYDT" VARCHAR2(200 CHAR), 
	"HOLDINGNATURE" CHAR(3 CHAR), 
	"BOOKTYPE" VARCHAR2(25 CHAR), 
	"BOOKVALUE" NUMBER(18,2), 
	"MTMVALUE" NUMBER(18,2), 
	"INTEREST_DIVIDENDDUEDATE" VARCHAR2(200 CHAR), 
	"INTEREST_DIVIDENDDUEAMOUNT" NUMBER(16,2), 
	"DPD" NUMBER(10,0), 
	"FLGDEG" CHAR(1 CHAR), 
	"DEGREASON" VARCHAR2(500 CHAR), 
	"FLGUPG" CHAR(1 CHAR), 
	"UPGDATE" VARCHAR2(200 CHAR), 
	"TOTALPROVISON" NUMBER(18,2), 
	"ASSETCLASS" VARCHAR2(20 CHAR), 
	"PARTIALREDUMPTIONDUEDATE" VARCHAR2(200 CHAR), 
	"PARTIALREDUMPTIONSETTLEDY_N" CHAR(1 CHAR), 
	"NPIDT" VARCHAR2(200 CHAR), 
	"BALANCESHEETDATE" VARCHAR2(200 CHAR), 
	"LISTEDSHARES" VARCHAR2(10 CHAR), 
	"DPD_BS_DATE" NUMBER(5,0), 
	"BOOKVALUEINR" NUMBER(18,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."INVESTMENT_DATA" TO "ADF_CDR_RBL_STGDB";
