--------------------------------------------------------
--  DDL for Table RBL_RESTR_DATA
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."RBL_RESTR_DATA" 
   (	"RESTRUCTURESTAGE" NVARCHAR2(255), 
	"SOURCE_SYSTEM" NVARCHAR2(255), 
	"REFCUSTOMERID" NVARCHAR2(255), 
	"REFSYSTEMACID" NVARCHAR2(255), 
	"RESTRUCTUREFACILITYTYPEALT_KEY" NVARCHAR2(255), 
	"INVOCATIONDATE" DATE, 
	"RESTRUCTUREDT" DATE, 
	"PRINCREPAYSTARTDATE" DATE, 
	"INTTREPAYSTARTDATE" DATE, 
	"SP_EXPIREDATE" DATE, 
	"MP_EXPIREDATE" DATE, 
	"PRERESTRUCTUREASSETCLASSALT_KEY" NVARCHAR2(255), 
	"CURRENT_STATUS" NVARCHAR2(255), 
	"PRERESTRUCTURENPA_DATE" DATE, 
	"POST_RESTRUCTURE_SLIPPAGE_DATE" DATE, 
	"PROVPERONRESTRUCURE" FLOAT(126), 
	"RESTRUCTURETYPEALT_KEY" NVARCHAR2(255), 
	"COVID_OTR_CATGALT_KEY" NVARCHAR2(255), 
	"FLGMORAT" NVARCHAR2(255), 
	"FLGINVESTMENTGRADE" FLOAT(126), 
	"RESTRUCTRETOS" FLOAT(126), 
	"RESTRUCTUREPOS" FLOAT(126), 
	"CURRENTPOS" FLOAT(126), 
	"DPD_30_90_BREACH_DATE" DATE, 
	"DEFAULTDATE" FLOAT(126), 
	"ZERODPD_DATE" DATE, 
	"SP_EXTENDEDDATE" DATE, 
	"UPGRADEDATE" DATE, 
	"SURVILANCEPERIODDATE" NVARCHAR2(255), 
	"F30" NVARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RBL_MISDB_PROD"."RBL_RESTR_DATA"."SOURCE_SYSTEM" IS 'ORIGINAL NAME:Source System';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."RBL_RESTR_DATA"."CURRENT_STATUS" IS 'ORIGINAL NAME:Current Status';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."RBL_RESTR_DATA"."POST_RESTRUCTURE_SLIPPAGE_DATE" IS 'ORIGINAL NAME:Post restructure slippage date';
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RBL_RESTR_DATA" TO "ADF_CDR_RBL_STGDB";
