--------------------------------------------------------
--  DDL for Table RESTRUCTURE_REPORT_2
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" 
   (	"UCIC" VARCHAR2(50 CHAR), 
	"CUSTOMERID" VARCHAR2(50 CHAR), 
	"CUSTOMERACID" VARCHAR2(50 CHAR), 
	"FACILITYTYPE" VARCHAR2(50 CHAR), 
	"ACOPENDT" VARCHAR2(50 CHAR), 
	"RESTRUCTUREFACILITY" VARCHAR2(50 CHAR), 
	"TYPEOFRESTRUCTURE" VARCHAR2(50 CHAR), 
	"COVID_CATEGORY" VARCHAR2(50 CHAR), 
	"FLGMORAT" VARCHAR2(50 CHAR), 
	"RESTRUCTUREDT" VARCHAR2(50 CHAR), 
	"PRE_RESTR_ASSETCLASS" VARCHAR2(50 CHAR), 
	"PRERESTRUCTURENPA_PROV" VARCHAR2(50 CHAR), 
	"PRERESTRUCTURENPA_DATE" VARCHAR2(50 CHAR), 
	"CURRENT_ASSETCLASS" VARCHAR2(50 CHAR), 
	"CURRENTNPA_DATE" VARCHAR2(50 CHAR), 
	"DPD_MAX" VARCHAR2(50 CHAR), 
	"DPD_MAXFIN" VARCHAR2(50 CHAR), 
	"DPD_MAXNONFIN" VARCHAR2(50 CHAR), 
	"DPD_OVERDRAWN" VARCHAR2(50 CHAR), 
	"DPD_BREACH_DATE" VARCHAR2(50 CHAR), 
	"ZERODPD_DATE" VARCHAR2(50 CHAR), 
	"RES_POS_TO_CURRENTPOS_PER" VARCHAR2(50 CHAR), 
	"RESTRUCTURESTAGE" VARCHAR2(50 CHAR), 
	"ASSETCLASS_ON_IINVOCATION" VARCHAR2(50 CHAR), 
	"PROVPERONRESTRUCURE" VARCHAR2(50 CHAR), 
	"NETBALANCE" VARCHAR2(50 CHAR), 
	"RESTRUCTUREPOS" VARCHAR2(50 CHAR), 
	"CURRENTPOS" VARCHAR2(50 CHAR), 
	"BALANCE" VARCHAR2(50 CHAR), 
	"PRINCREPAYSTARTDATE" VARCHAR2(50 CHAR), 
	"INTTREPAYSTARTDATE" VARCHAR2(50 CHAR), 
	"SP_EXPIRYDATE" VARCHAR2(50 CHAR), 
	"SP_EXPIRYEXTENDEDDATE" VARCHAR2(50 CHAR), 
	"PREDEGPROVPER" VARCHAR2(50 CHAR), 
	"UPGRADEDATE" VARCHAR2(50 CHAR), 
	"DEGDURSP_PERIODPROVPER" VARCHAR2(50 CHAR), 
	"RESTR_FLGDEG" VARCHAR2(50 CHAR), 
	"RESTR_FLGUPG" VARCHAR2(50 CHAR), 
	"NPA_REASON" VARCHAR2(50 CHAR), 
	"DEGREASON" VARCHAR2(50 CHAR), 
	"SECUREDAMT" VARCHAR2(50 CHAR), 
	"UNSECUREDAMT" VARCHAR2(50 CHAR), 
	"RESTRPROVPER" VARCHAR2(50 CHAR), 
	"PROVRELEASEPER" VARCHAR2(50 CHAR), 
	"APPLIEDNORMALPROVPER" VARCHAR2(50 CHAR), 
	"RESTRFINALPROVPER" VARCHAR2(50 CHAR), 
	"RESTRUCTUREPROVISION" VARCHAR2(50 CHAR), 
	"RESTR_SECUREDPROVISION" VARCHAR2(50 CHAR), 
	"RESTR_UNSECUREDPROVISION" VARCHAR2(50 CHAR), 
	"BANKTOTALPROVISION" VARCHAR2(50 CHAR), 
	"RBITOTALPROVISION" VARCHAR2(50 CHAR), 
	"TOTALPROVISION" VARCHAR2(50 CHAR), 
	"APPLIEDPROVPER" VARCHAR2(50 CHAR), 
	"CREATEDDATE" VARCHAR2(50 CHAR), 
	"ASSET_NORM" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTURE_REPORT_2" TO "ADF_CDR_RBL_STGDB";
