--------------------------------------------------------
--  DDL for Table RESTRUCTUREASSET_UPLOAD_MOD
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" 
   (	"ACCOUNTID" VARCHAR2(50 CHAR), 
	"ACCOUNTENTITYID" NUMBER(10,0), 
	"UPLOADID" NUMBER(10,0), 
	"RESTRUCTUREFACILITY" VARCHAR2(100 CHAR), 
	"REVISEDBUSINESSSEG" VARCHAR2(50 CHAR), 
	"DISBURSEMENTDATE" VARCHAR2(200 CHAR), 
	"REFERENCEDATE" VARCHAR2(200 CHAR), 
	"INVOCATIONDATE" VARCHAR2(200 CHAR), 
	"DATEOFCONVERSIONINTOEQUITY" VARCHAR2(200 CHAR), 
	"PRINRPYMNTSTARTDATE" VARCHAR2(200 CHAR), 
	"INTTRPYMNTSTARTDATE" VARCHAR2(200 CHAR), 
	"ASSETCLASSATRSTRCTR" VARCHAR2(50 CHAR), 
	"IFNPANPADATE" VARCHAR2(200 CHAR), 
	"NPAQUARTER" VARCHAR2(20 CHAR), 
	"TYPEOFRESTRUCTURING" VARCHAR2(50 CHAR), 
	"COVIDMORATORIAMMSME" VARCHAR2(50 CHAR), 
	"COVIDOTRCATEGORY" VARCHAR2(50 CHAR), 
	"BANKINGRELATIONSHIP" VARCHAR2(50 CHAR), 
	"DATEOFRESTRUCTURING" VARCHAR2(200 CHAR), 
	"RESTRUCTURINGAPPROVINGAUTH" VARCHAR2(50 CHAR), 
	"DATEOFISTDEFAULTONCRILIC" VARCHAR2(200 CHAR), 
	"REPORTINGBANK" VARCHAR2(50 CHAR), 
	"DATEOFSIGNINGICA" VARCHAR2(200 CHAR), 
	"INVESTMENTGRADE" VARCHAR2(50 CHAR), 
	"CREDITPROVISIONRS" NUMBER(18,2), 
	"DFVPROVISIONRS" NUMBER(18,2), 
	"MTMPROVISIONRS" NUMBER(18,2), 
	"SHEETNAME" VARCHAR2(255 CHAR), 
	"AUTHORISATIONSTATUS" VARCHAR2(2 CHAR), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"CREATEDBY" VARCHAR2(20 CHAR), 
	"DATECREATED" DATE, 
	"MODIFIEDBY" VARCHAR2(20 CHAR), 
	"DATEMODIFIED" DATE, 
	"APPROVEDBY" VARCHAR2(20 CHAR), 
	"DATEAPPROVED" DATE, 
	"D2KTIMESTAMP" RAW(50), 
	"SRNO" NUMBER(10,0), 
	"OSASONDATEOFRSTRCTR" NUMBER(18,2), 
	"POSASONDATEOFRSTRCTR" NUMBER(18,2), 
	"ACTION" CHAR(2 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."RESTRUCTUREASSET_UPLOAD_MOD" TO "ADF_CDR_RBL_STGDB";
