--------------------------------------------------------
--  DDL for Table SECURITY_ISSUE
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."SECURITY_ISSUE" 
   (	"REPORT_DATE" DATE, 
	"UCIC" NVARCHAR2(255), 
	"CIF_ID" NVARCHAR2(255), 
	"BORROWER_NAME" NVARCHAR2(255), 
	"BRANCH_CODE" NVARCHAR2(255), 
	"BRANCH_NAME" NVARCHAR2(255), 
	"ACCOUNT_NO" NVARCHAR2(255), 
	"SOURCE_SYSTEM" NVARCHAR2(255), 
	"FACILITY" NVARCHAR2(255), 
	"SCHEME_TYPE" NVARCHAR2(255), 
	"SCHEME_CODE" NVARCHAR2(255), 
	"SCHEME_DESCRIPTION" NVARCHAR2(255), 
	"SECURED_UNSECURED" NVARCHAR2(255), 
	"SEG_CODE" NVARCHAR2(255), 
	"SEGMENT_DESCRIPTION" NVARCHAR2(255), 
	"BUSINESS_SEGMENT" NVARCHAR2(255), 
	"ACCOUNT_DPD" FLOAT(126), 
	"CYCLE_PAST_DUE" NVARCHAR2(255), 
	"NPA_DATE" DATE, 
	"ASSET_CLASSIFICATION" NVARCHAR2(255), 
	"NPA_NORMS" FLOAT(126), 
	"BALANCE_OUTSTANDING" FLOAT(126), 
	"CUSTOMER_SECURITY_VALUE" FLOAT(126), 
	"SECURITY_VALUE_APPROPRIATED" FLOAT(126), 
	"SECURED_OUTSTANDING" FLOAT(126), 
	"UNSECURED_OUTSTANDING" FLOAT(126), 
	"PROVISION_TOTAL" FLOAT(126), 
	"PROVISION_SECURED" FLOAT(126), 
	"PROVISION_UNSECURED" FLOAT(126), 
	"NET_NPA" FLOAT(126), 
	"PROVISIONSECURED" FLOAT(126), 
	"PROVISIONUNSECURED" FLOAT(126), 
	"PROVISIONTOTAL" FLOAT(126)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."REPORT_DATE" IS 'ORIGINAL NAME:Report Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."CIF_ID" IS 'ORIGINAL NAME:CIF ID';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."BORROWER_NAME" IS 'ORIGINAL NAME:Borrower Name';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."BRANCH_CODE" IS 'ORIGINAL NAME:Branch Code';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."BRANCH_NAME" IS 'ORIGINAL NAME:Branch Name';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."ACCOUNT_NO" IS 'ORIGINAL NAME:Account No ';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."SOURCE_SYSTEM" IS 'ORIGINAL NAME:Source System';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."SCHEME_TYPE" IS 'ORIGINAL NAME:Scheme Type';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."SCHEME_CODE" IS 'ORIGINAL NAME:Scheme Code';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."SCHEME_DESCRIPTION" IS 'ORIGINAL NAME:Scheme Description';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."SECURED_UNSECURED" IS 'ORIGINAL NAME:Secured Unsecured';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."SEG_CODE" IS 'ORIGINAL NAME:Seg Code';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."SEGMENT_DESCRIPTION" IS 'ORIGINAL NAME:Segment Description';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."BUSINESS_SEGMENT" IS 'ORIGINAL NAME:Business Segment';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."ACCOUNT_DPD" IS 'ORIGINAL NAME:Account DPD';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."CYCLE_PAST_DUE" IS 'ORIGINAL NAME:Cycle Past due';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."NPA_DATE" IS 'ORIGINAL NAME:NPA Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."ASSET_CLASSIFICATION" IS 'ORIGINAL NAME:Asset Classification';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."NPA_NORMS" IS 'ORIGINAL NAME:NPA Norms';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."BALANCE_OUTSTANDING" IS 'ORIGINAL NAME:Balance Outstanding';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."CUSTOMER_SECURITY_VALUE" IS 'ORIGINAL NAME:Customer Security Value';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."SECURITY_VALUE_APPROPRIATED" IS 'ORIGINAL NAME:Security Value Appropriated';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."SECURED_OUTSTANDING" IS 'ORIGINAL NAME:Secured Outstanding';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."UNSECURED_OUTSTANDING" IS 'ORIGINAL NAME:Unsecured Outstanding';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."PROVISION_TOTAL" IS 'ORIGINAL NAME:Provision Total';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."PROVISION_SECURED" IS 'ORIGINAL NAME:Provision Secured';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."PROVISION_UNSECURED" IS 'ORIGINAL NAME:Provision Unsecured';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."NET_NPA" IS 'ORIGINAL NAME:Net NPA';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."PROVISIONSECURED" IS 'ORIGINAL NAME:ProvisionSecured%';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."PROVISIONUNSECURED" IS 'ORIGINAL NAME:ProvisionUnSecured%';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SECURITY_ISSUE"."PROVISIONTOTAL" IS 'ORIGINAL NAME:ProvisionTotal%';
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SECURITY_ISSUE" TO "ADF_CDR_RBL_STGDB";
