--------------------------------------------------------
--  DDL for Table SMA_OTHER
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."SMA_OTHER" 
   (	"REPORT_DATE" VARCHAR2(50 CHAR), 
	"UCIC" VARCHAR2(50 CHAR), 
	"CIF_ID" VARCHAR2(50 CHAR), 
	"BORROWER_NAME" VARCHAR2(200 CHAR), 
	"BRANCH_CODE" VARCHAR2(50 CHAR), 
	"BRANCH_NAME" VARCHAR2(50 CHAR), 
	"BRANCHSTATENAME" VARCHAR2(50 CHAR), 
	"REGION" VARCHAR2(50 CHAR), 
	"ACCOUNT_NO" VARCHAR2(50 CHAR), 
	"PAN" VARCHAR2(50 CHAR), 
	"SOURCE_SYSTEM" VARCHAR2(50 CHAR), 
	"FACILITY" VARCHAR2(50 CHAR), 
	"SCHEME_TYPE" VARCHAR2(50 CHAR), 
	"SCHEME_CODE" VARCHAR2(50 CHAR), 
	"SCHEME_DESCRIPTION" VARCHAR2(200 CHAR), 
	"SEG_CODE" VARCHAR2(50 CHAR), 
	"SEGMENT_DESCRIPTION" VARCHAR2(50 CHAR), 
	"BUSINESS_SEGMENT" VARCHAR2(50 CHAR), 
	"WHOLESALE_RETAIL" VARCHAR2(50 CHAR), 
	"BALANCE_OUTSTANDING" VARCHAR2(50 CHAR), 
	"PRINCIPAL_OUTSTANDING" VARCHAR2(50 CHAR), 
	"DRAWING_POWER" VARCHAR2(50 CHAR), 
	"SANCTION_LIMIT" VARCHAR2(50 CHAR), 
	"OVERDRAWN_AMOUNT" VARCHAR2(50 CHAR), 
	"DPD_OVERDRAWN" VARCHAR2(50 CHAR), 
	"LIMIT_DP_OVERDRAWN_DATE" VARCHAR2(50 CHAR), 
	"OVERDUE_AMOUNT" VARCHAR2(50 CHAR), 
	"OVERDUESINCEDT" VARCHAR2(50 CHAR), 
	"DPD_OVERDUE" VARCHAR2(50 CHAR), 
	"BILL_PC_OVERDUE_AMOUNT" VARCHAR2(50 CHAR), 
	"OVERDUE_BILL_PC_ID" VARCHAR2(50 CHAR), 
	"BILL_PC_OVERDUE_DATE" VARCHAR2(50 CHAR), 
	"DPD_BILL_PC" VARCHAR2(50 CHAR), 
	"INTEREST_DIVIDENDDUEDATE" VARCHAR2(50 CHAR), 
	"INTEREST_DIVIDENDDUEAMOUNT" VARCHAR2(50 CHAR), 
	"DPD" VARCHAR2(50 CHAR), 
	"PARTIALREDUMPTIONDUEDATE" VARCHAR2(50 CHAR), 
	"SMA_DPD" VARCHAR2(50 CHAR), 
	"ACCOUNTFLGSMA" VARCHAR2(50 CHAR), 
	"ACCOUNTSMA_DT" VARCHAR2(50 CHAR), 
	"ACCOUNTSMA_ASSETCLASS" VARCHAR2(50 CHAR), 
	"SMA_REASON" VARCHAR2(50 CHAR), 
	"DPD_UCIF_ID" VARCHAR2(50 CHAR), 
	"UCICFLGSMA" VARCHAR2(50 CHAR), 
	"UCICSMA_DT" VARCHAR2(50 CHAR), 
	"UCICSMA_ASSETSTATUS" VARCHAR2(50 CHAR), 
	"FIRST_TIME_SMA_CLASSIFICATION_DATE" VARCHAR2(50 CHAR), 
	"IN_DEFAULT_Y_N" VARCHAR2(50 CHAR), 
	"IN_DEFAULT_DATE" VARCHAR2(50 CHAR), 
	"OUT_OF_DEFAULT_Y_N" VARCHAR2(50 CHAR), 
	"OUT_OF_DEFAULT_DATE" VARCHAR2(50 CHAR), 
	"MOVEMENTFROMDATE" VARCHAR2(50 CHAR), 
	"MOVEMENTFROMSTATUS" VARCHAR2(50 CHAR), 
	"MOVEMENTTOSTATUS" VARCHAR2(50 CHAR), 
	"ASSET_NORM" VARCHAR2(50 CHAR), 
	"NPA_NORMS" VARCHAR2(50 CHAR), 
	"FDOD_FLAG" VARCHAR2(50 CHAR), 
	"LIMIT_EXPIRY_DATE" VARCHAR2(50 CHAR), 
	"DPD_LIMIT_EXPIRY" VARCHAR2(50 CHAR), 
	"STOCK_STATEMENT_VALUATION_DATE" VARCHAR2(50 CHAR), 
	"DPD_STOCK_STATEMENT_EXPIRY" VARCHAR2(50 CHAR), 
	"DEBIT_BALANCE_SINCE_DATE" VARCHAR2(50 CHAR), 
	"LAST_CREDIT_DATE" VARCHAR2(50 CHAR), 
	"DPD_NO_CREDIT" VARCHAR2(50 CHAR), 
	"CURRENT_QUARTER_CREDIT" VARCHAR2(50 CHAR), 
	"CURRENT_QUARTER_INTEREST" VARCHAR2(50 CHAR), 
	"INTEREST_NOT_SERVICED" VARCHAR2(50 CHAR), 
	"DPD_OUT_OF_ORDER" VARCHAR2(50 CHAR), 
	"CC_OD_INTEREST_SERVICE_DATE" VARCHAR2(50 CHAR), 
	"PRINCIPAL_OVERDUE" VARCHAR2(50 CHAR), 
	"PRINCIPAL_OVERDUE_DATE" VARCHAR2(50 CHAR), 
	"DPD_PRINCIPAL_OVERDUE" VARCHAR2(50 CHAR), 
	"INTEREST_OVERDUE" VARCHAR2(50 CHAR), 
	"INTEREST_OVERDUE_DATE" VARCHAR2(50 CHAR), 
	"DPD_INTEREST_OVERDUE" VARCHAR2(50 CHAR), 
	"OTHER_OVERDUE" VARCHAR2(50 CHAR), 
	"OTHER_OVERDUE_DATE" VARCHAR2(50 CHAR), 
	"DPD_OTHER_OVERDUE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."REPORT_DATE" IS 'ORIGINAL NAME:Report Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."CIF_ID" IS 'ORIGINAL NAME:CIF ID';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."BORROWER_NAME" IS 'ORIGINAL NAME:Borrower Name';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."BRANCH_CODE" IS 'ORIGINAL NAME:Branch Code';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."BRANCH_NAME" IS 'ORIGINAL NAME:Branch Name';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."ACCOUNT_NO" IS 'ORIGINAL NAME:Account No ';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."SOURCE_SYSTEM" IS 'ORIGINAL NAME:Source System';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."SCHEME_TYPE" IS 'ORIGINAL NAME:Scheme Type';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."SCHEME_CODE" IS 'ORIGINAL NAME:Scheme Code';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."SCHEME_DESCRIPTION" IS 'ORIGINAL NAME:Scheme Description';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."SEG_CODE" IS 'ORIGINAL NAME:Seg Code';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."SEGMENT_DESCRIPTION" IS 'ORIGINAL NAME:Segment Description';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."BUSINESS_SEGMENT" IS 'ORIGINAL NAME:Business Segment';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."WHOLESALE_RETAIL" IS 'ORIGINAL NAME:Wholesale   Retail';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."BALANCE_OUTSTANDING" IS 'ORIGINAL NAME:Balance Outstanding';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."PRINCIPAL_OUTSTANDING" IS 'ORIGINAL NAME:Principal Outstanding';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DRAWING_POWER" IS 'ORIGINAL NAME:Drawing Power';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."SANCTION_LIMIT" IS 'ORIGINAL NAME:Sanction Limit';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."OVERDRAWN_AMOUNT" IS 'ORIGINAL NAME:OverDrawn Amount';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."LIMIT_DP_OVERDRAWN_DATE" IS 'ORIGINAL NAME:Limit DP Overdrawn Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."OVERDUE_AMOUNT" IS 'ORIGINAL NAME:Overdue Amount';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."BILL_PC_OVERDUE_AMOUNT" IS 'ORIGINAL NAME:Bill PC Overdue Amount';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."OVERDUE_BILL_PC_ID" IS 'ORIGINAL NAME:Overdue Bill PC ID';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."BILL_PC_OVERDUE_DATE" IS 'ORIGINAL NAME:Bill PC Overdue Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DPD_BILL_PC" IS 'ORIGINAL NAME:DPD Bill PC';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."FIRST_TIME_SMA_CLASSIFICATION_DATE" IS 'ORIGINAL NAME:First Time SMA Classification Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."IN_DEFAULT_Y_N" IS 'ORIGINAL NAME:in_default (Y N)';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."IN_DEFAULT_DATE" IS 'ORIGINAL NAME:in_default date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."OUT_OF_DEFAULT_Y_N" IS 'ORIGINAL NAME:out_of_default (Y N)';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."OUT_OF_DEFAULT_DATE" IS 'ORIGINAL NAME:out_of_default date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."NPA_NORMS" IS 'ORIGINAL NAME:NPA Norms';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."FDOD_FLAG" IS 'ORIGINAL NAME:FDOD Flag';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."LIMIT_EXPIRY_DATE" IS 'ORIGINAL NAME:Limit Expiry Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DPD_LIMIT_EXPIRY" IS 'ORIGINAL NAME:DPD_Limit Expiry';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."STOCK_STATEMENT_VALUATION_DATE" IS 'ORIGINAL NAME:Stock Statement valuation date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DPD_STOCK_STATEMENT_EXPIRY" IS 'ORIGINAL NAME:DPD_Stock Statement expiry';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DEBIT_BALANCE_SINCE_DATE" IS 'ORIGINAL NAME:Debit Balance Since Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."LAST_CREDIT_DATE" IS 'ORIGINAL NAME:Last Credit Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DPD_NO_CREDIT" IS 'ORIGINAL NAME:DPD_No Credit';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."CURRENT_QUARTER_CREDIT" IS 'ORIGINAL NAME:Current quarter credit';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."CURRENT_QUARTER_INTEREST" IS 'ORIGINAL NAME:Current quarter interest';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."INTEREST_NOT_SERVICED" IS 'ORIGINAL NAME:Interest Not Serviced';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DPD_OUT_OF_ORDER" IS 'ORIGINAL NAME:DPD_out of order';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."CC_OD_INTEREST_SERVICE_DATE" IS 'ORIGINAL NAME:CC OD Interest Service Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."PRINCIPAL_OVERDUE" IS 'ORIGINAL NAME:Principal Overdue';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."PRINCIPAL_OVERDUE_DATE" IS 'ORIGINAL NAME:Principal Overdue Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DPD_PRINCIPAL_OVERDUE" IS 'ORIGINAL NAME:DPD_Principal Overdue';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."INTEREST_OVERDUE" IS 'ORIGINAL NAME:Interest Overdue';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."INTEREST_OVERDUE_DATE" IS 'ORIGINAL NAME:Interest Overdue Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DPD_INTEREST_OVERDUE" IS 'ORIGINAL NAME:DPD_Interest Overdue';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."OTHER_OVERDUE" IS 'ORIGINAL NAME:Other Overdue';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."OTHER_OVERDUE_DATE" IS 'ORIGINAL NAME:Other OverDue Date';
   COMMENT ON COLUMN "RBL_MISDB_PROD"."SMA_OTHER"."DPD_OTHER_OVERDUE" IS 'ORIGINAL NAME:DPD_Other Overdue';
   COMMENT ON TABLE "RBL_MISDB_PROD"."SMA_OTHER"  IS 'ORIGINAL NAME:SMA Other';
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OTHER" TO "ADF_CDR_RBL_STGDB";
