--------------------------------------------------------
--  DDL for Table SMA_OUTPUT_REPORT_AUTOMATE
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" 
   (	"CURRENTPROCESSINGDATE" VARCHAR2(10 CHAR), 
	"SRNO" NUMBER(19,0), 
	"BRANCHCODE" VARCHAR2(20 CHAR), 
	"BRANCHNAME" VARCHAR2(50 CHAR), 
	"BRANCHSTATENAME" VARCHAR2(50 CHAR), 
	"SOURCENAME" VARCHAR2(50 CHAR), 
	"CUSTOMERID" VARCHAR2(50 CHAR), 
	"SOURCESYSTEMCUSTOMERID" VARCHAR2(50 CHAR), 
	"UCIF_ID" VARCHAR2(50 CHAR), 
	"CUSTOMERACID" VARCHAR2(30 CHAR), 
	"PANNO" VARCHAR2(12 CHAR), 
	"CUSTOMERNAME" VARCHAR2(225 CHAR), 
	"CUSTSEGMENTCODE" VARCHAR2(10 CHAR), 
	"FACILITYTYPE" VARCHAR2(10 CHAR), 
	"PRODUCTCODE" VARCHAR2(20 CHAR), 
	"PRODUCTNAME" VARCHAR2(200 CHAR), 
	"ACTSEGMENTCODE" VARCHAR2(30 CHAR), 
	"ACBUREVISEDSEGMENTCODE" VARCHAR2(20 CHAR), 
	"SCHEMETYPE" VARCHAR2(20 CHAR), 
	"BALANCE" NUMBER(16,2), 
	"PRINCOUTSTD" NUMBER(18,2), 
	"PRINCOVERDUE" NUMBER(18,2), 
	"INTOVERDUE" NUMBER(18,2), 
	"OTHEROVERDUE" NUMBER(18,2), 
	"OVERDUEAMT" NUMBER(18,2), 
	"CURRENTLIMIT" NUMBER(16,2), 
	"CONTIEXCESSDT" VARCHAR2(10 CHAR), 
	"STOCKSTDT" VARCHAR2(10 CHAR), 
	"LASTCRDATE" VARCHAR2(10 CHAR), 
	"INTNOTSERVICEDDT" VARCHAR2(10 CHAR), 
	"OVERDUESINCEDT" VARCHAR2(10 CHAR), 
	"REVIEWDUEDT" VARCHAR2(10 CHAR), 
	"DPD_STOCKSTMT" NUMBER(10,0), 
	"DPD_NOCREDIT" NUMBER(10,0), 
	"DPD_INTSERVICE" NUMBER(10,0), 
	"DPD_OVERDRAWN" NUMBER(10,0), 
	"DPD_OVERDUE" NUMBER(10,0), 
	"DPD_RENEWAL" NUMBER(10,0), 
	"SMA_DPD" NUMBER(10,0), 
	"ACCOUNTFLGSMA" CHAR(1 CHAR), 
	"ACCOUNTSMA_DT" VARCHAR2(200 CHAR), 
	"ACCOUNTSMA_ASSETCLASS" VARCHAR2(5 CHAR), 
	"SMA_REASON" CLOB, 
	"DPD_UCIF_ID" NUMBER(10,0), 
	"UCICFLGSMA" CHAR(1 CHAR), 
	"UCICSMA_DT" VARCHAR2(200 CHAR), 
	"UCICSMA_ASSETSTATUS" VARCHAR2(10 CHAR), 
	"MOVEMENTFROMDATE" VARCHAR2(200 CHAR), 
	"MOVEMENTFROMSTATUS" VARCHAR2(10 CHAR), 
	"MOVEMENTTOSTATUS" VARCHAR2(10 CHAR), 
	"ASSET_NORM" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("SMA_REASON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "MAIN_PRO";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "RBL_MISDB_PROD"."SMA_OUTPUT_REPORT_AUTOMATE" TO "ADF_CDR_RBL_STGDB";
