--------------------------------------------------------
--  DDL for Table STAGE_TERADATA_OFFLINE_VIEWS
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."STAGE_TERADATA_OFFLINE_VIEWS" 
   (	"INDEX" NUMBER, 
	"DBNAME" VARCHAR2(256 BYTE), 
	"VIEWNAME" VARCHAR2(256 BYTE), 
	"COLNAME" VARCHAR2(256 BYTE), 
	"TYPENAME" CHAR(2 BYTE), 
	"LENGTH" NUMBER, 
	"SCALE" NUMBER, 
	"NULLS" CHAR(1 BYTE), 
	"DEFAULTVAL" VARCHAR2(2048 BYTE)
   ) ON COMMIT PRESERVE ROWS ;
