--------------------------------------------------------
--  DDL for Table SYB12_SYSDATABASES
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."SYB12_SYSDATABASES" 
   (	"DB_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"DBID" NUMBER(10,0), 
	"DB_SUID" NUMBER(10,0), 
	"STATUS" NUMBER(10,0), 
	"VERSION" NUMBER(10,0), 
	"LOGPTR" NUMBER(12,0), 
	"CRDATE" VARCHAR2(255 BYTE), 
	"DUMPTRDATE" VARCHAR2(255 BYTE), 
	"STATUS2" NUMBER(10,0), 
	"AUDFLAGS" NUMBER(10,0), 
	"DEFTABAUD" NUMBER(10,0), 
	"DEFVWAUD" NUMBER(10,0), 
	"DEFPRAUD" NUMBER(10,0), 
	"DEF_REMOTE_TYPE" NUMBER(10,0), 
	"DEF_REMOTE_LOC" VARCHAR2(255 BYTE), 
	"STATUS3" NUMBER(10,0), 
	"STATUS4" NUMBER(10,0)
   ) ON COMMIT PRESERVE ROWS ;
