--------------------------------------------------------
--  DDL for Table SYSDATAMATRIX
--------------------------------------------------------

  CREATE TABLE "RBL_MISDB_PROD"."SYSDATAMATRIX" 
   (	"MONTHFIRSTDATE" VARCHAR2(10 CHAR), 
	"MONTHLASTDATE" VARCHAR2(10 CHAR), 
	"TIMEKEY" NUMBER(10,0), 
	"MONTHNAME" VARCHAR2(15 CHAR), 
	"MONTH" VARCHAR2(50 CHAR), 
	"YEAR" VARCHAR2(4 CHAR), 
	"LASTFRIDAY" VARCHAR2(10 CHAR), 
	"LASTREPORTINGFRIDAY" VARCHAR2(10 CHAR), 
	"CURRENTSTATUS" CHAR(1 CHAR), 
	"PREV_MONTH_KEY" NUMBER(10,0), 
	"PREV_QTR_KEY" NUMBER(10,0), 
	"PREV_FISCAL_HALFYEAR_KEY" NUMBER(10,0), 
	"PREV_FISCAL_YEAR_KEY" NUMBER(10,0), 
	"DATAEFFECTIVEFROMDATE" VARCHAR2(10 CHAR), 
	"DATAEFFECTIVETODATE" VARCHAR2(10 CHAR), 
	"DATAEFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"ASSETCLASSIFICATIONDT" VARCHAR2(10 CHAR), 
	"WEEK_KEY" NUMBER(10,0), 
	"FORTNIGHT_KEY" NUMBER(10,0), 
	"MONTH_KEY" NUMBER(10,0), 
	"QTR_KEY" NUMBER(10,0), 
	"FISCAL_HALFYEAR_KEY" NUMBER(10,0), 
	"FISCAL_YEAR_KEY" NUMBER(10,0), 
	"ISCLOSINGDAY" CHAR(1 CHAR), 
	"MOC_INITIALISED" CHAR(1 CHAR), 
	"MOC_FROZEN" CHAR(1 CHAR), 
	"QTR_INITIALISED" CHAR(1 CHAR), 
	"QTR_FROZEN" CHAR(1 CHAR), 
	"BS_MASTERFREEZE" CHAR(1 CHAR), 
	"PROCESSINGDONE" CHAR(1 CHAR), 
	"EXTDATE" VARCHAR2(10 CHAR), 
	"RBSPROCESSCOMPLETED" CHAR(1 CHAR), 
	"RBSFREEZEDDONE" CHAR(1 CHAR), 
	"RBSFREEZEDBY" VARCHAR2(20 CHAR), 
	"RBSFREEZEDDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
