--------------------------------------------------------
--  DDL for Table TT_ACCOUNTLEVELMOC_MOD_6
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_ACCOUNTLEVELMOC_MOD_6" 
   (	"ACCOUNTID" VARCHAR2(30 CHAR), 
	"CHANGEFIELD" CLOB, 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"CREATEDBY" VARCHAR2(100 CHAR), 
	"DATECREATED" DATE, 
	"APPROVEDBYFIRSTLEVEL" VARCHAR2(100 CHAR), 
	"DATEAPPROVEDFIRSTLEVEL" VARCHAR2(200 CHAR), 
	"APPROVEDBY" VARCHAR2(100 CHAR), 
	"DATEAPPROVED" VARCHAR2(200 CHAR)
   ) ON COMMIT DELETE ROWS 
 LOB ("CHANGEFIELD") STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE ) ;
