--------------------------------------------------------
--  DDL for Table TT_ACCOUNT_POSTMOC_2
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_ACCOUNT_POSTMOC_2" 
   (	"ACCOUNTENTITYID" NUMBER(10,0), 
	"ACCOUNTID" VARCHAR2(30 CHAR), 
	"POS" NUMBER(18,2), 
	"INTERESTRECEIVABLE" NUMBER(18,2), 
	"FLGFITL" CHAR(1 CHAR), 
	"DFVAMOUNT" NUMBER(16,2), 
	"ADDITIONALPROVISIONABSOLUTE" NUMBER(16,2), 
	"FRAUDACCOUNTFLAG" CHAR(1 CHAR), 
	"FRAUDDATE" VARCHAR2(200 CHAR), 
	"TWOFLAG" CHAR(1 CHAR), 
	"TWODATE" VARCHAR2(200 CHAR), 
	"MOCREASON" VARCHAR2(500 CHAR), 
	"TWOAMOUNT" NUMBER(18,2), 
	"UCICID" VARCHAR2(4000 BYTE), 
	"AUTHORISATIONSTATUS" CHAR(1 BYTE), 
	"CREATEDBY" CHAR(1 BYTE), 
	"DATECREATED" CHAR(1 BYTE), 
	"MODIFIEDBY" CHAR(1 BYTE), 
	"DATEMODIFIED" CHAR(1 BYTE), 
	"APPROVEDBY" CHAR(1 BYTE), 
	"DATEAPPROVED" CHAR(1 BYTE), 
	"MOCSOURCE" CHAR(1 BYTE), 
	"APPROVEDBYFIRSTLEVEL" CHAR(1 BYTE), 
	"DATEAPPROVEDFIRSTLEVEL" CHAR(1 BYTE), 
	"MOC_TYPEFLAG" CHAR(4 BYTE)
   ) ON COMMIT DELETE ROWS ;
