--------------------------------------------------------
--  DDL for Table TT_ACCOUNT_MOVEMENT_HISTORY_10
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_ACCOUNT_MOVEMENT_HISTORY_10" 
   (	"ENTITYKEY" NUMBER(19,0), 
	"UCIF_ID" VARCHAR2(50 CHAR), 
	"REFCUSTOMERID" VARCHAR2(50 CHAR), 
	"SOURCESYSTEMCUSTOMERID" VARCHAR2(50 CHAR), 
	"CUSTOMERACID" VARCHAR2(30 CHAR), 
	"FINALASSETCLASSALT_KEY" NUMBER(10,0), 
	"FINALNPADT" VARCHAR2(200 CHAR), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"MOVEMENTFROMDATE" VARCHAR2(200 CHAR), 
	"MOVEMENTFROMSTATUS" VARCHAR2(10 CHAR), 
	"MOVEMENTTOSTATUS" VARCHAR2(10 CHAR), 
	"MOVEMENTTODATE" VARCHAR2(200 CHAR), 
	"TOTOSACC" NUMBER(18,2)
   ) ON COMMIT DELETE ROWS ;
