--------------------------------------------------------
--  DDL for Table TT_CALCUALTEINITIALBALANCE
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_CALCUALTEINITIALBALANCE" 
   (	"CUSTOMERACID" VARCHAR2(20 CHAR), 
	"STATUSDATE" VARCHAR2(200 CHAR), 
	"TIMEKEY" NUMBER, 
	"ATTHETIMEOFWRITEOFF_TIMEKEY" VARCHAR2(20 CHAR)
   ) ON COMMIT DELETE ROWS ;
