--------------------------------------------------------
--  DDL for Table TT_DIMACBUSEGMENT
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_DIMACBUSEGMENT" 
   (	"RN" NUMBER, 
	"ACBUSEGMENTCODE" VARCHAR2(20 CHAR), 
	"ACBUREVISEDSEGMENTCODE" VARCHAR2(20 CHAR), 
	"ACBUSEGMENTDESCRIPTION" VARCHAR2(100 CHAR)
   ) ON COMMIT DELETE ROWS ;
