--------------------------------------------------------
--  DDL for Table TT_MASTERINFO
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_MASTERINFO" 
   (	"CREATEDBY" VARCHAR2(20 BYTE), 
	"DATECREATED" DATE, 
	"MODIFIEDBY" VARCHAR2(20 BYTE), 
	"DATEMODIFIED" DATE, 
	"DELSTATUS" CHAR(2 BYTE), 
	"ENTITYKEY" NUMBER(10,0), 
	"AUTHORISATIONSTATUS" CHAR(2 BYTE), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0)
   ) ON COMMIT DELETE ROWS ;
