--------------------------------------------------------
--  DDL for Table TT_PREMOC_5
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_PREMOC_5" 
   (	"BALANCEOSPOS" NUMBER(16,2), 
	"BALANCEOSINTTRECEIVABLE" NUMBER(18,2), 
	"RESTRUCTUREFLAG" CHAR(1 CHAR), 
	"RESTRUCTUREDATE" VARCHAR2(200 CHAR), 
	"FITLFLAG" CHAR(1 CHAR), 
	"DFVAMT" NUMBER(16,2), 
	"REPOSSESSIONFLAG" CHAR(1 CHAR), 
	"REPOSSESSIONDATE" VARCHAR2(200 CHAR), 
	"INHERENTWEAKNESSFLAG" CHAR(1 CHAR), 
	"INHERENTWEAKNESSDATE" VARCHAR2(200 CHAR), 
	"SARFAESIFLAG" CHAR(1 CHAR), 
	"SARFAESIDATE" VARCHAR2(200 CHAR), 
	"UNUSUALBOUNCEFLAG" CHAR(1 CHAR), 
	"UNUSUALBOUNCEDATE" VARCHAR2(200 CHAR), 
	"UNCLEAREDEFFECTFLAG" CHAR(1 CHAR), 
	"UNCLEAREDEFFECTDATE" VARCHAR2(200 CHAR), 
	"ADDITIONALPROVISIONCUSTOMERLEVEL" NUMBER, 
	"ADDITIONALPROVISIONABSOLUTE" NUMBER, 
	"MOCREASON" VARCHAR2(500 CHAR), 
	"FRAUDACCOUNTFLAG" CHAR(1 CHAR), 
	"FRAUDDATE" VARCHAR2(200 CHAR)
   ) ON COMMIT DELETE ROWS ;
