--------------------------------------------------------
--  DDL for Table TT_TEMP_83
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_TEMP_83" 
   (	"REFSYSTEMACID" VARCHAR2(50 CHAR), 
	"UCICID" VARCHAR2(12 CHAR), 
	"REFCUSTOMERID" VARCHAR2(50 CHAR), 
	"COLLATERALID" VARCHAR2(30 CHAR), 
	"COLLATERALVALUEATSANCTIONINRS" NUMBER(18,2), 
	"COLLATERALVALUEASONNPADATEINRS" NUMBER(18,2), 
	"COLLATERALVALUEATTHETIMEOFLASTREVIEWINRS" NUMBER(16,2), 
	"VALUATIONDATE" VARCHAR2(4000 BYTE), 
	"LATESTCOLLATERALVALUEINRS" NUMBER(16,2), 
	"EXPIRYBUSINESSRULE" VARCHAR2(100 CHAR), 
	"PERIODINMONTH" NUMBER(10,0), 
	"VALUEEXPIRATIONDATE" VARCHAR2(4000 BYTE), 
	"TAGGINGALT_KEY" NUMBER(10,0), 
	"AUTHORISATIONSTATUS" VARCHAR2(2 CHAR), 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0), 
	"CREATEDBY" VARCHAR2(20 CHAR), 
	"DATECREATED" DATE, 
	"APPROVEDBY" VARCHAR2(20 CHAR), 
	"DATEAPPROVED" DATE, 
	"MODIFIEDBY" VARCHAR2(20 CHAR), 
	"DATEMODIFIED" DATE, 
	"TAGGINGID" VARCHAR2(50 CHAR), 
	"TABLENAME" CHAR(24 BYTE)
   ) ON COMMIT DELETE ROWS ;
