--------------------------------------------------------
--  DDL for Table TT_TEMPINSERT_7
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_TEMPINSERT_7" 
   (	"PD_CUST_ID" VARCHAR2(100 BYTE), 
	"PD_ACCOUNT_ID" VARCHAR2(100 BYTE), 
	"PD_UCIC" VARCHAR2(100 BYTE), 
	"CD_CUST_ID" VARCHAR2(100 BYTE), 
	"CD_ACCOUNT_ID" VARCHAR2(100 BYTE), 
	"CD_UCIC" VARCHAR2(100 BYTE), 
	"SOURCESYSTEM" VARCHAR2(100 BYTE), 
	"SOURCETABLEALT_KEY" NUMBER(10,0)
   ) ON COMMIT DELETE ROWS ;
