--------------------------------------------------------
--  DDL for Table TT_TMPGROUPDTL_2
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "RBL_MISDB_PROD"."TT_TMPGROUPDTL_2" 
   (	"ENTITYKEY" NUMBER(5,0), 
	"DEPTGROUPID" NUMBER(5,0), 
	"DEPTGROUPNAME" VARCHAR2(48 BYTE), 
	"DEPTGROUPDESC" VARCHAR2(200 CHAR), 
	"MENUS" VARCHAR2(1000 CHAR), 
	"AUTHORISATIONSTATUS" VARCHAR2(2 CHAR), 
	"CREATEDBY" VARCHAR2(20 CHAR), 
	"DATECREATED" DATE, 
	"MODIFIEDBY" VARCHAR2(20 CHAR), 
	"DATEMODIFIED" DATE, 
	"APPROVEDBY" VARCHAR2(20 CHAR), 
	"DATEAPPROVED" DATE, 
	"EFFECTIVEFROMTIMEKEY" NUMBER(10,0), 
	"EFFECTIVETOTIMEKEY" NUMBER(10,0)
   ) ON COMMIT DELETE ROWS ;
