--------------------------------------------------------
--  Constraints for Table ACCELERATEDPROVISION_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ACCELERATEDPROVISION_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCELERATEDPROVISION_MOD" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCELERATEDPROVISION_MOD" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
