--------------------------------------------------------
--  Constraints for Table ACCOUNTCAL_BKUP_2023_JUL
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_JUL" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_JUL" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_JUL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_JUL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
