--------------------------------------------------------
--  Constraints for Table ACCOUNTCAL_BKUP_2023_MAIN
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_MAIN" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_MAIN" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_MAIN" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_MAIN" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
