--------------------------------------------------------
--  Constraints for Table ACCOUNTCAL_HIST_BACKUP
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_HIST_BACKUP" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_HIST_BACKUP" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_HIST_BACKUP" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_HIST_BACKUP" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
