--------------------------------------------------------
--  Constraints for Table ACCOUNTCAL_BKUP_2023_MAR
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_MAR" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_MAR" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_MAR" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_MAR" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
