--------------------------------------------------------
--  Constraints for Table ACCOUNTSECURITYWORKFLOW
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTSECURITYWORKFLOW" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTSECURITYWORKFLOW" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTSECURITYWORKFLOW" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
