--------------------------------------------------------
--  Constraints for Table ACCOUNTCAL_BKUP_2023_FEB
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_FEB" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_FEB" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_FEB" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_FEB" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
