--------------------------------------------------------
--  Constraints for Table ACCOUNTCAL_BKUP_2023_JAN
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_JAN" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_JAN" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_JAN" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ACCOUNTCAL_BKUP_2023_JAN" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
