--------------------------------------------------------
--  Constraints for Table ADVACBASICDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_MOD" MODIFY ("AC_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_MOD" MODIFY ("BRANCHCODE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_MOD" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_MOD" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
