--------------------------------------------------------
--  Constraints for Table ADVACBASICDETAIL_BACKUP
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_BACKUP" MODIFY ("AC_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_BACKUP" MODIFY ("BRANCHCODE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_BACKUP" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_BACKUP" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_BACKUP" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_BACKUP" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBASICDETAIL_BACKUP" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
