--------------------------------------------------------
--  Constraints for Table ADVACBALANCEDETAIL_BACKUP_17_07_2024
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP_17_07_2024" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP_17_07_2024" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP_17_07_2024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP_17_07_2024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
