--------------------------------------------------------
--  Constraints for Table ADVACOTHERFINANCIALDETAIL_17082023
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVACOTHERFINANCIALDETAIL_17082023" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACOTHERFINANCIALDETAIL_17082023" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACOTHERFINANCIALDETAIL_17082023" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACOTHERFINANCIALDETAIL_17082023" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
