--------------------------------------------------------
--  Constraints for Table ADVACBALANCEDETAIL_BKPPREACLEIFS16042024
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BKPPREACLEIFS16042024" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BKPPREACLEIFS16042024" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BKPPREACLEIFS16042024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BKPPREACLEIFS16042024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
