--------------------------------------------------------
--  Constraints for Table ADVACCASEWISEBALANCEDETAILS_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVACCASEWISEBALANCEDETAILS_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVACCASEWISEBALANCEDETAILS_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
