--------------------------------------------------------
--  Constraints for Table ADVCUSTFINANCIALDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVCUSTFINANCIALDETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVCUSTFINANCIALDETAIL_MOD" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVCUSTFINANCIALDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
