--------------------------------------------------------
--  Constraints for Table ADVCUSTNPADETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVCUSTNPADETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVCUSTNPADETAIL_MOD" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVCUSTNPADETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
