--------------------------------------------------------
--  Constraints for Table ADVCUSTCOMMUNICATIONDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
