--------------------------------------------------------
--  Constraints for Table ADVFACCREDITCARDDETAIL_BACKUP_09082024
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_09082024" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_09082024" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_09082024" MODIFY ("CREDITCARDENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_09082024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_09082024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_09082024" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
