--------------------------------------------------------
--  Constraints for Table ADVFACCREDITCARDDETAIL_BACKUP_13082024_DAY2
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_13082024_DAY2" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_13082024_DAY2" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_13082024_DAY2" MODIFY ("CREDITCARDENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_13082024_DAY2" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_13082024_DAY2" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL_BACKUP_13082024_DAY2" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
