--------------------------------------------------------
--  Constraints for Table ADVFACDLDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVFACDLDETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACDLDETAIL_MOD" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACDLDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
