--------------------------------------------------------
--  Constraints for Table ADVFACNFDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVFACNFDETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACNFDETAIL_MOD" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACNFDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
