--------------------------------------------------------
--  Constraints for Table ADVFACBILLDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVFACBILLDETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACBILLDETAIL_MOD" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACBILLDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
