--------------------------------------------------------
--  Constraints for Table ADVFACCCDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCCDETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCCDETAIL_MOD" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVFACCCDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
