--------------------------------------------------------
--  Constraints for Table ADVSECURITYVALUEDETAIL_BACKUP_ALL_17072023
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_BACKUP_ALL_17072023" MODIFY ("SECURITYENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_BACKUP_ALL_17072023" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_BACKUP_ALL_17072023" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
