--------------------------------------------------------
--  Constraints for Table ADVSECURITYCRMDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVSECURITYCRMDETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVSECURITYCRMDETAIL_MOD" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVSECURITYCRMDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
