--------------------------------------------------------
--  Constraints for Table ADVSECURITYVALUEDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MOD" MODIFY ("SECURITYENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MOD" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MOD" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
