--------------------------------------------------------
--  Constraints for Table BACKDATEDPROCMONITORSTATUS
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."BACKDATEDPROCMONITORSTATUS" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."BACKDATEDPROCMONITORSTATUS" ADD CONSTRAINT "PK__BACKDATE__9EC07B8EEA2910B0" PRIMARY KEY ("ENTITYKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
