--------------------------------------------------------
--  Constraints for Table CALYPSOMOCMONITORSTATUS
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."CALYPSOMOCMONITORSTATUS" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CALYPSOMOCMONITORSTATUS" ADD CONSTRAINT "PK__CALYPSOM__9EC07B8E64307A78" PRIMARY KEY ("ENTITYKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
