--------------------------------------------------------
--  Constraints for Table CUSTOMERCAL_BKUP_2023_JUN
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_JUN" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_JUN" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_JUN" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_JUN" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
