--------------------------------------------------------
--  Constraints for Table CUSTOMERCAL_BKUP_2023_AUG
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_AUG" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_AUG" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_AUG" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_AUG" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
