--------------------------------------------------------
--  Constraints for Table CUSTOMERCAL_BKUP_2023_DEC
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_DEC" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_DEC" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_DEC" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."CUSTOMERCAL_BKUP_2023_DEC" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
