--------------------------------------------------------
--  Constraints for Table DEGRADE_CHECK_MOC_CUSTOMER_31072023
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DEGRADE_CHECK_MOC_CUSTOMER_31072023" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DEGRADE_CHECK_MOC_CUSTOMER_31072023" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DEGRADE_CHECK_MOC_CUSTOMER_31072023" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DEGRADE_CHECK_MOC_CUSTOMER_31072023" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
