--------------------------------------------------------
--  Constraints for Table DEMO
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DEMO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DEMO" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DEMO" ADD CONSTRAINT "PK__DEMO__3213E83F1EE6294F" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RBL_MISDB_PROD"."DEMO" ADD CONSTRAINT "CHECKGENDER" CHECK (
   ( GENDER = 'F'
                  OR GENDER = 'M' )
) ENABLE;
