--------------------------------------------------------
--  Constraints for Table DIMACBUSEGMENT_BKP_10072024
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMACBUSEGMENT_BKP_10072024" MODIFY ("ACBUSEGMENT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMACBUSEGMENT_BKP_10072024" MODIFY ("ACBUSEGMENTALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMACBUSEGMENT_BKP_10072024" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
