--------------------------------------------------------
--  Constraints for Table DIMASSETCLASS_FIS
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMASSETCLASS_FIS" MODIFY ("ASSETCLASS_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMASSETCLASS_FIS" MODIFY ("ASSETCLASSALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMASSETCLASS_FIS" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
