--------------------------------------------------------
--  Constraints for Table DIMACBUSEGMENT_BACKUP_04042024
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMACBUSEGMENT_BACKUP_04042024" MODIFY ("ACBUSEGMENT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMACBUSEGMENT_BACKUP_04042024" MODIFY ("ACBUSEGMENTALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMACBUSEGMENT_BACKUP_04042024" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
