--------------------------------------------------------
--  Constraints for Table DIMCONSTITUTION
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMCONSTITUTION" MODIFY ("CONSTITUTION_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMCONSTITUTION" MODIFY ("CONSTITUTIONALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMCONSTITUTION" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
