--------------------------------------------------------
--  Constraints for Table DIMLEGALNATUREOFACTIVITY
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMLEGALNATUREOFACTIVITY" MODIFY ("LEGALNATUREOFACTIVITY_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMLEGALNATUREOFACTIVITY" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMLEGALNATUREOFACTIVITY" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
