--------------------------------------------------------
--  Constraints for Table DIMMISCSUIT
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMMISCSUIT" MODIFY ("LEGALMISCSUIT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMMISCSUIT" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMMISCSUIT" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
