--------------------------------------------------------
--  Constraints for Table DIMPROVISION_SEG
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMPROVISION_SEG" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMPROVISION_SEG" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMPROVISION_SEG" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
