--------------------------------------------------------
--  Constraints for Table DIMPRODUCTDUMMY_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMPRODUCTDUMMY_MOD" MODIFY ("PRODUCT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMPRODUCTDUMMY_MOD" MODIFY ("PRODUCTALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMPRODUCTDUMMY_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
