--------------------------------------------------------
--  Constraints for Table DIMPRODUCT_23052023
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMPRODUCT_23052023" MODIFY ("PRODUCTALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMPRODUCT_23052023" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMPRODUCT_23052023" MODIFY ("PRODUCT_KEY" NOT NULL ENABLE);
