--------------------------------------------------------
--  Constraints for Table DIMREGION_06052024
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMREGION_06052024" MODIFY ("REGION_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMREGION_06052024" MODIFY ("REGIONALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMREGION_06052024" MODIFY ("REGIONNAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMREGION_06052024" MODIFY ("ZONEALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMREGION_06052024" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
