--------------------------------------------------------
--  Constraints for Table DIMSOURCEDB
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMSOURCEDB" MODIFY ("SOURCE_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSOURCEDB" MODIFY ("RECORDSTATUS" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSOURCEDB" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSOURCEDB" MODIFY ("APPROVEDBY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSOURCEDB" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
