--------------------------------------------------------
--  Constraints for Table DIMSTATE
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."DIMSTATE" MODIFY ("STATE_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSTATE" MODIFY ("STATEALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSTATE" MODIFY ("STATEALT2_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSTATE" MODIFY ("STATENAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSTATE" MODIFY ("TERRITORYALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSTATE" MODIFY ("TERRITORYNAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."DIMSTATE" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
