--------------------------------------------------------
--  Constraints for Table ETL_ACLFAILREQUESTDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."ETL_ACLFAILREQUESTDETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ETL_ACLFAILREQUESTDETAIL_MOD" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ETL_ACLFAILREQUESTDETAIL_MOD" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."ETL_ACLFAILREQUESTDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
