--------------------------------------------------------
--  Constraints for Table INVESTMENTFINANCIALDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_MOD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_MOD" MODIFY ("INVENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_MOD" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_MOD" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
