--------------------------------------------------------
--  Constraints for Table METADYNAMICMASTERFILTER
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."METADYNAMICMASTERFILTER" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."METADYNAMICMASTERFILTER" MODIFY ("MASTERFILTERGRPKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."METADYNAMICMASTERFILTER" MODIFY ("MASTERFILTERKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."METADYNAMICMASTERFILTER" MODIFY ("CONTROLID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."METADYNAMICMASTERFILTER" MODIFY ("FILTERMASTERCONTROLNAME" NOT NULL ENABLE);
