--------------------------------------------------------
--  Constraints for Table METAQUARTERLYFIELDDETAIL
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."METAQUARTERLYFIELDDETAIL" MODIFY ("LASTUPDATED" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."METAQUARTERLYFIELDDETAIL" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."METAQUARTERLYFIELDDETAIL" MODIFY ("VIABLEFORSCD2" NOT NULL ENABLE);
