--------------------------------------------------------
--  Constraints for Table SALETOARCACFLAGGINGDETAIL_MOD
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."SALETOARCACFLAGGINGDETAIL_MOD" MODIFY ("ENTITY_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SALETOARCACFLAGGINGDETAIL_MOD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
