--------------------------------------------------------
--  Constraints for Table SECURITY
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("REPORT_DATE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("UCIC" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("CIF_ID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("BORROWER_NAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("BRANCH_CODE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("BRANCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("ACCOUNT_NO" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("SOURCE_SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("FACILITY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("SCHEME_TYPE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("SCHEME_CODE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("SCHEME_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("SECURED_UNSECURED" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("SEG_CODE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("BUSINESS_SEGMENT" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("ACCOUNT_DPD" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("NPA_DATE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("MAR_22_ACL" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("ASSET_CLASSIFICATION" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("REMARKS" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("NPA_NORMS" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("BALANCE_OUTSTANDING" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("SECURITY_VALUE_APPROPRIATED" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("SECURED_OUTSTANDING" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("UNSECURED_OUTSTANDING" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SECURITY" MODIFY ("PROVISION_TOTAL" NOT NULL ENABLE);
