--------------------------------------------------------
--  Constraints for Table SYSSOLUTIONPARAMETER1
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."SYSSOLUTIONPARAMETER1" MODIFY ("PARAMETER_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SYSSOLUTIONPARAMETER1" MODIFY ("PARAMETERALT_KEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SYSSOLUTIONPARAMETER1" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
