--------------------------------------------------------
--  Constraints for Table SYSUSERACTIVITYLOG
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."SYSUSERACTIVITYLOG" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SYSUSERACTIVITYLOG" MODIFY ("BRANCHCODE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SYSUSERACTIVITYLOG" MODIFY ("MENUID" NOT NULL ENABLE);
