--------------------------------------------------------
--  Constraints for Table SYSUSERACTIVITYLOG_ATTENDENCE
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."SYSUSERACTIVITYLOG_ATTENDENCE" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SYSUSERACTIVITYLOG_ATTENDENCE" MODIFY ("BRANCHCODE" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."SYSUSERACTIVITYLOG_ATTENDENCE" MODIFY ("MENUID" NOT NULL ENABLE);
