--------------------------------------------------------
--  Constraints for Table TT_TEMP_171
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_171" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_171" MODIFY ("INVENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_171" MODIFY ("ISSUERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_171" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_171" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
