--------------------------------------------------------
--  Constraints for Table TT_TEMP_169
--------------------------------------------------------

  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_169" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_169" MODIFY ("INVENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_169" MODIFY ("ISSUERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_169" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_MISDB_PROD"."TT_TEMP_169" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
