--------------------------------------------------------
--  Constraints for Table ACDAILYTXNDETAIL_03022023
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ACDAILYTXNDETAIL_03022023" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ACDAILYTXNDETAIL_03022023" MODIFY ("CUSTOMERACID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ACDAILYTXNDETAIL_03022023" MODIFY ("TXNDATE" NOT NULL ENABLE);
