--------------------------------------------------------
--  Constraints for Table ACDAILYTXNDETAIL_JAN2024
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ACDAILYTXNDETAIL_JAN2024" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ACDAILYTXNDETAIL_JAN2024" MODIFY ("CUSTOMERACID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ACDAILYTXNDETAIL_JAN2024" MODIFY ("TXNDATE" NOT NULL ENABLE);
