--------------------------------------------------------
--  Constraints for Table ADVACRESTRUCTUREDETAIL_OLD
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACRESTRUCTUREDETAIL_OLD" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACRESTRUCTUREDETAIL_OLD" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACRESTRUCTUREDETAIL_OLD" ADD CONSTRAINT "PK_ADVACRESTRUCTUREDETAIL" PRIMARY KEY ("ENTITYKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
