--------------------------------------------------------
--  Constraints for Table ADVACWODETAIL
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACWODETAIL" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACWODETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACWODETAIL" ADD CONSTRAINT "PK_ADVACWODETAIL" PRIMARY KEY ("ENTITYKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
