--------------------------------------------------------
--  Constraints for Table ADVACFINANCIALDETAIL_03022023
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACFINANCIALDETAIL_03022023" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACFINANCIALDETAIL_03022023" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACFINANCIALDETAIL_03022023" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACFINANCIALDETAIL_03022023" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACFINANCIALDETAIL_03022023" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
