--------------------------------------------------------
--  Constraints for Table ADVACBASICDETAIL
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" MODIFY ("AC_KEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" MODIFY ("BRANCHCODE" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" ADD CONSTRAINT "ADVACBASICDETAIL_ACCOUNTENTITYID" PRIMARY KEY ("ACCOUNTENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" ADD CONSTRAINT "CK__ADVACBASI__EFFEC__75516BED" CHECK (
   ( EffectiveToTimeKey = (49999) )
) ENABLE;
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL" ADD CONSTRAINT "CK__ADVACBASI__EFFEC__5F622ACE" CHECK (
   ( EffectiveToTimeKey = (49999) )
) ENABLE;
