--------------------------------------------------------
--  Constraints for Table ADVACBASICDETAIL_FEB2024_BKUP
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL_FEB2024_BKUP" MODIFY ("AC_KEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL_FEB2024_BKUP" MODIFY ("BRANCHCODE" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL_FEB2024_BKUP" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL_FEB2024_BKUP" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL_FEB2024_BKUP" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL_FEB2024_BKUP" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBASICDETAIL_FEB2024_BKUP" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
