--------------------------------------------------------
--  Constraints for Table ADVACBALANCEDETAIL_BACKUP
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP" ADD CONSTRAINT "ADVACBALANCEDETAILBACKUP_CUR_ACCOUNTENTITYID" PRIMARY KEY ("ACCOUNTENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVACBALANCEDETAIL_BACKUP" ADD CONSTRAINT "CK__ADVACBALA__EFFEC__67CA2641" CHECK (
   ( EffectiveToTimeKey = (49999) )
) ENABLE;
