--------------------------------------------------------
--  Constraints for Table ADVCREDITCARDBALANCEDETAIL_BK
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCREDITCARDBALANCEDETAIL_BK" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCREDITCARDBALANCEDETAIL_BK" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCREDITCARDBALANCEDETAIL_BK" MODIFY ("CREDITCARDENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCREDITCARDBALANCEDETAIL_BK" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCREDITCARDBALANCEDETAIL_BK" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCREDITCARDBALANCEDETAIL_BK" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
