--------------------------------------------------------
--  Constraints for Table ADVCUSTOTHERDETAIL_BK
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTOTHERDETAIL_BK" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTOTHERDETAIL_BK" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTOTHERDETAIL_BK" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTOTHERDETAIL_BK" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
