--------------------------------------------------------
--  Constraints for Table ADVCUSTFINANCIALDETAIL
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTFINANCIALDETAIL" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTFINANCIALDETAIL" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTFINANCIALDETAIL" MODIFY ("BRANCHCODE" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTFINANCIALDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTFINANCIALDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTFINANCIALDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
