--------------------------------------------------------
--  Constraints for Table ADVCUSTRELATIONSHIP
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTRELATIONSHIP" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTRELATIONSHIP" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTRELATIONSHIP" MODIFY ("RELATIONENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTRELATIONSHIP" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTRELATIONSHIP" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTRELATIONSHIP" ADD CONSTRAINT "ADVCUSTRELATIONSHIP_CUSTOMERENTITYID" PRIMARY KEY ("RELATIONENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTRELATIONSHIP" ADD CONSTRAINT "CK__ADVCUSTRE__EFFEC__742FFD26" CHECK (
   ( EffectiveToTimeKey = (49999) )
) ENABLE;
