--------------------------------------------------------
--  Constraints for Table ADVCUSTCOMMUNICATIONDETAIL
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" MODIFY ("RELATIONENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" MODIFY ("RELATIONADDENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" ADD CONSTRAINT "ADVCUSTCOMMUNICATIONDETAIL_CUSTOMERENTITYID" PRIMARY KEY ("CUSTOMERENTITYID", "RELATIONADDENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" ADD CONSTRAINT "CK__ADVCUSTCO__EFFEC__705F6C42" CHECK (
   ( EffectiveToTimeKey = (49999) )
) ENABLE;
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVCUSTCOMMUNICATIONDETAIL" ADD CONSTRAINT "CK__ADVCUSTCO__EFFEC__7153907B" CHECK (
   ( EffectiveToTimeKey = (49999) )
) ENABLE;
