--------------------------------------------------------
--  Constraints for Table ADVFACCREDITCARDDETAIL
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL" MODIFY ("CREDITCARDENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL" ADD CONSTRAINT "ADVFACCREDITCARDDETAIL_ACCOUNTENTITYID" PRIMARY KEY ("ACCOUNTENTITYID", "CREDITCARDENTITYID", "EFFECTIVEFROMTIMEKEY", "EFFECTIVETOTIMEKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCREDITCARDDETAIL" ADD CONSTRAINT "CK__ADVFACCRE__EFFEC__4E0294A2" CHECK (
   ( EffectiveToTimeKey = (49999) )
) ENABLE;
