--------------------------------------------------------
--  Constraints for Table ADVFACCCDETAIL_JAN2024
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCCDETAIL_JAN2024" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCCDETAIL_JAN2024" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCCDETAIL_JAN2024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVFACCCDETAIL_JAN2024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
