--------------------------------------------------------
--  Constraints for Table ADVSECURITYVALUEDETAIL_14022024
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_14022024" MODIFY ("SECURITYENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_14022024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_14022024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
