--------------------------------------------------------
--  Constraints for Table CUSTOMERBASICDETAIL_FEB2024
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB2024" MODIFY ("CUSTOMER_KEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB2024" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB2024" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB2024" MODIFY ("CUSTOMERNAME" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB2024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB2024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB2024" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
