--------------------------------------------------------
--  Constraints for Table CUSTOMERBASICDETAIL_03022023
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_03022023" MODIFY ("CUSTOMER_KEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_03022023" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_03022023" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_03022023" MODIFY ("CUSTOMERNAME" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_03022023" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_03022023" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_03022023" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
