--------------------------------------------------------
--  Constraints for Table CUSTOMERBASICDETAIL_FEB20241
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB20241" MODIFY ("CUSTOMER_KEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB20241" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB20241" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB20241" MODIFY ("CUSTOMERNAME" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB20241" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB20241" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."CUSTOMERBASICDETAIL_FEB20241" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
