--------------------------------------------------------
--  Constraints for Table DERIVATIVEDETAIL_25042023
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."DERIVATIVEDETAIL_25042023" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."DERIVATIVEDETAIL_25042023" MODIFY ("DERIVATIVEENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."DERIVATIVEDETAIL_25042023" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."DERIVATIVEDETAIL_25042023" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
