--------------------------------------------------------
--  Constraints for Table INVESTMENTFINANCIALDETAIL_BK
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_BK" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_BK" MODIFY ("INVENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_BK" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_BK" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
