--------------------------------------------------------
--  Constraints for Table INVESTMENTFINANCIALDETAIL_25042023
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_25042023" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_25042023" MODIFY ("INVENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_25042023" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTFINANCIALDETAIL_25042023" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
