--------------------------------------------------------
--  Constraints for Table INVESTMENTBASICDETAIL_03022023
--------------------------------------------------------

  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTBASICDETAIL_03022023" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTBASICDETAIL_03022023" MODIFY ("INVENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTBASICDETAIL_03022023" MODIFY ("ISSUERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTBASICDETAIL_03022023" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "CURDAT_RBL_MISDB_PROD"."INVESTMENTBASICDETAIL_03022023" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
