--------------------------------------------------------
--  DDL for Table CUSTOMER_MASTER
--------------------------------------------------------

  CREATE TABLE "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" 
   (	"ID" NUMBER(10,0), 
	"CUSTOMER_SOURCE" VARCHAR2(12 CHAR), 
	"ISINCREMENTAL" VARCHAR2(10 CHAR), 
	"CUSTOMER_CODE" VARCHAR2(30 CHAR), 
	"SOURCE_SYSTEM" VARCHAR2(30 CHAR), 
	"DATE_OF_DATA" VARCHAR2(200 CHAR), 
	"PAN" VARCHAR2(30 CHAR), 
	"BUSINESS_SEGMENT" VARCHAR2(30 CHAR), 
	"GENDER" VARCHAR2(30 CHAR), 
	"CUSTOMER_NAME" VARCHAR2(30 CHAR), 
	"UCIC" VARCHAR2(30 CHAR), 
	"SEGMENT" VARCHAR2(30 CHAR), 
	"SUBSEGMENT" VARCHAR2(30 CHAR), 
	"CONSTITUTION_DESC" VARCHAR2(30 CHAR), 
	"CONSTITUTION_CODE" VARCHAR2(30 CHAR), 
	"GEND_CODE" VARCHAR2(30 CHAR), 
	"GEND_DESCR" VARCHAR2(30 CHAR), 
	"FIN_INDUSTRY_CODE" VARCHAR2(30 CHAR), 
	"FIN_INDUSTRY_DESC" VARCHAR2(30 CHAR), 
	"ATTRRIBUTE_CODE" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER"."PAN" IS 'ORIGINAL NAME:pan ';
   COMMENT ON COLUMN "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER"."BUSINESS_SEGMENT" IS 'ORIGINAL NAME:business_segment  ';
   COMMENT ON COLUMN "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER"."GENDER" IS 'ORIGINAL NAME:gender ';
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT ALTER ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT DELETE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT INDEX ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT INSERT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT SELECT ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT UPDATE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT REFERENCES ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT READ ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT ON COMMIT REFRESH ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT QUERY REWRITE ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ROLE_ALL_DB";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CC_CDR_RBL_STGDB";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "MAIN_PRO";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_BI_RBL_STGDB";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ALERT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ACL_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "QPI_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "CURDAT_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "PREMOC_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BSG_READ_RBL_STGDB";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STD_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "BS_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_STGDB";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DWH_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "RBL_TEMPDB";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "STG_FIN_RBL_STGDB";
  GRANT FLASHBACK ON "ADF_CDR_RBL_STGDB"."CUSTOMER_MASTER" TO "DATAUPLOAD_RBL_MISDB_PROD";
