--------------------------------------------------------
--  DDL for Index PK_ADVACRESTRUCTUREDETAIL_NEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "RBL_MISDB_PROD"."PK_ADVACRESTRUCTUREDETAIL_NEW" ON "RBL_MISDB_PROD"."ADVACRESTRUCTUREDETAIL_MOD" ("ENTITYKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
