--------------------------------------------------------
--  DDL for Table GTT_RBL_SECURITY_CAL_STOCK
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "ETL_TEMP_RBL_TEMPDB"."GTT_RBL_SECURITY_CAL_STOCK" 
   (	"DATEOFDATA" VARCHAR2(200 CHAR), 
	"SOURCESYSTEM" VARCHAR2(30 CHAR), 
	"ACCOUNTID" VARCHAR2(30 CHAR), 
	"COLLATERALID" VARCHAR2(30 CHAR), 
	"SECURITYCODE" VARCHAR2(10 CHAR), 
	"SECURITYVALUE" NUMBER(16,2), 
	"VALUATIONDATE" VARCHAR2(200 CHAR), 
	"SECURITYCHARGESTATUS" VARCHAR2(10 CHAR), 
	"VALUATIONEXPIRYDATE" VARCHAR2(200 CHAR), 
	"STOCK_AUDIT_DATE" VARCHAR2(200 CHAR), 
	"CUSTOMER_ID" VARCHAR2(20 CHAR), 
	"COLLATERAL_TYPE" VARCHAR2(36 CHAR), 
	"VALUATION_SOURCE" VARCHAR2(10 CHAR), 
	"APPORTIONED_VALUE" NUMBER(16,2), 
	"SEC_PERF_FLG" VARCHAR2(50 CHAR), 
	"TYPE_OF_CURRENCY" VARCHAR2(20 CHAR), 
	"MAINSECURITYVALUE" NUMBER(16,2), 
	"SECVALUE_FINAL" NUMBER(16,2), 
	"FLG_MULTI_CUST_COLLID" CHAR(1 BYTE), 
	"VALUATIONEXPIRYDATE_NEW" VARCHAR2(200 BYTE), 
	"STOCK_AUDIT_DATE_NEW" VARCHAR2(200 BYTE), 
	"CUST_OS" NUMBER(18,2)
   ) ON COMMIT DELETE ROWS ;
