--------------------------------------------------------
--  Constraints for Table ADVACOTHERFINANCIALDETAIL_JAN2024
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."ADVACOTHERFINANCIALDETAIL_JAN2024" MODIFY ("ENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."ADVACOTHERFINANCIALDETAIL_JAN2024" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."ADVACOTHERFINANCIALDETAIL_JAN2024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."ADVACOTHERFINANCIALDETAIL_JAN2024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."ADVACOTHERFINANCIALDETAIL_JAN2024" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
