--------------------------------------------------------
--  Constraints for Table MD_TARGET_ALL_ERRORS
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."MD_TARGET_ALL_ERRORS" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."MD_TARGET_ALL_ERRORS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."MD_TARGET_ALL_ERRORS" MODIFY ("SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."MD_TARGET_ALL_ERRORS" MODIFY ("LINE" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."MD_TARGET_ALL_ERRORS" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."MD_TARGET_ALL_ERRORS" MODIFY ("TEXT" NOT NULL ENABLE);
