--------------------------------------------------------
--  Constraints for Table TEMPADVFACPCDETAIL
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACPCDETAIL" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACPCDETAIL" MODIFY ("PCREFNO" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACPCDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACPCDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACPCDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
