--------------------------------------------------------
--  Constraints for Table TEMPADVACOTHERDETAIL
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVACOTHERDETAIL" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVACOTHERDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVACOTHERDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVACOTHERDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
