--------------------------------------------------------
--  Constraints for Table TEMPADVCUSTNPADETAIL
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTNPADETAIL" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTNPADETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTNPADETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
