--------------------------------------------------------
--  Constraints for Table TEMPHOSTSYSTEMSTATUS
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" MODIFY ("CR_DR" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPHOSTSYSTEMSTATUS" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
