--------------------------------------------------------
--  Constraints for Table TEMPADVSECURITYVALUEDETAIL_BACKUP_11062024
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYVALUEDETAIL_BACKUP_11062024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYVALUEDETAIL_BACKUP_11062024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
