--------------------------------------------------------
--  Constraints for Table TEMPADVACFINANCIALDETAIL
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVACFINANCIALDETAIL" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVACFINANCIALDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVACFINANCIALDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVACFINANCIALDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
