--------------------------------------------------------
--  Constraints for Table TEMPADVSECURITYDETAIL_JAN2024
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYDETAIL_JAN2024" MODIFY ("SECURITYENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYDETAIL_JAN2024" MODIFY ("REFCUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYDETAIL_JAN2024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYDETAIL_JAN2024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
