--------------------------------------------------------
--  Constraints for Table TEMPADVCUSTRELATIONSHIP
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTRELATIONSHIP" MODIFY ("RELATIONENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTRELATIONSHIP" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTRELATIONSHIP" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTRELATIONSHIP" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
