--------------------------------------------------------
--  Constraints for Table TEMPADVCUSTCOMMUNICATIONDETAIL
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTCOMMUNICATIONDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTCOMMUNICATIONDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTCOMMUNICATIONDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
