--------------------------------------------------------
--  Constraints for Table TEMPADVFACDLDETAIL_JAN2024
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACDLDETAIL_JAN2024" MODIFY ("ACCOUNTENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACDLDETAIL_JAN2024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACDLDETAIL_JAN2024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
