--------------------------------------------------------
--  Constraints for Table TEMPADVCUSTOTHERDETAIL_JAN2024
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTOTHERDETAIL_JAN2024" MODIFY ("CUSTOMERENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTOTHERDETAIL_JAN2024" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTOTHERDETAIL_JAN2024" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVCUSTOTHERDETAIL_JAN2024" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
