--------------------------------------------------------
--  Constraints for Table TEMPADVFACCREDITCARDDETAIL
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACCREDITCARDDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACCREDITCARDDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACCREDITCARDDETAIL" MODIFY ("DATECREATED" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVFACCREDITCARDDETAIL" MODIFY ("ISCHANGED" NOT NULL ENABLE);
