--------------------------------------------------------
--  Constraints for Table TEMPCUSTOMERBASICDETAIL
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPCUSTOMERBASICDETAIL" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPCUSTOMERBASICDETAIL" MODIFY ("CUSTOMERNAME" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPCUSTOMERBASICDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPCUSTOMERBASICDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPCUSTOMERBASICDETAIL" MODIFY ("D2KTIMESTAMP" NOT NULL ENABLE);
