--------------------------------------------------------
--  Constraints for Table TEMPADVSECURITYDETAIL
--------------------------------------------------------

  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYDETAIL" MODIFY ("SECURITYENTITYID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYDETAIL" MODIFY ("REFCUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYDETAIL" MODIFY ("EFFECTIVEFROMTIMEKEY" NOT NULL ENABLE);
  ALTER TABLE "RBL_TEMPDB"."TEMPADVSECURITYDETAIL" MODIFY ("EFFECTIVETOTIMEKEY" NOT NULL ENABLE);
